### ISSUE TITLE
Reset file field after uploading?

### ISSUE THREAD

**Issue by rmanalo623** [nervgh/angular-file-upload#100]
Hello,

Thank you for such an awesome plugin. I'm using this plugin that allows people to attach an image to a comment and I have this working but after its submitted and the file is uploaded how do I reset or clear the file field after uploading?

After uploading, it still shows the file name of the image next to the button and I would like to return that to its default state. I added the "removeAfterUpload" property and set it to true, but the text doesn't change back to "No file chosen". Is there another way to do this?

Also, is there a way to modify that default text?

Thanks!

**Comment by zbindenren** [comment]
@kevinrenskers you saved my day, thx

**Comment by hmudassir** [comment]
Please help me,
when I remove the file and try to select that file again, it doesn't adding file in queue.

Thanks
