### ISSUE TITLE
using this for single file upload?

### ISSUE THREAD

**Issue by simkimsia** [nervgh/angular-file-upload#101]
Hi there, 

I am using this plugin for single file upload.

I have a problem to replace the last selected file before upload.

I manage to get this resolved. But I suspect the way I did it is not best way.

``` javascript
var uploader = $scope.uploader = $fileUploader.create({
      scope: $scope,
      url: '/users/my_profile_pic',
      queueLimit: 2
  });
  // ADDING FILTERS
  // Images only
  uploader.filters.push(function(item /*{File|HTMLInputElement}*/) {
      // this helps to ensure that when user keeps adding
      // it keeps replacing
      if (uploader.queue.length == 1) {
        uploader.removeFromQueue(0);
      }
```

This is the user interface.

![screen shot 2014-04-04 at 10 36 26 am](https://cloud.githubusercontent.com/assets/245021/2611360/fb822a60-bba1-11e3-9ac4-b732f65048fa.png)

What happens is that I want my queue to only have the last selected image no matter how many times the user repeatedly selects different images using the + PROFILE PIC button you see above.

**Comment by aaronbc** [comment]
For the newer version I use:

```javascript
uploader.onAfterAddingAll = function () {
  if (uploader.getNotUploadedItems().length > 1)
  {
    uploader.removeFromQueue(0);
  }
};
```
Clearing the queue on ng-click as proposed above doesn't work as expected if the user cancels the new file selection.
