### ISSUE TITLE
How to work with different and dynamic url for file upload?

### ISSUE THREAD

**Issue by simkimsia** [nervgh/angular-file-upload#106]
I am using angular-file-upload at the following scenario.

when I want to add images at an album creation, say /albums/add.

My logic is:

a) first send a $http to /albums/add to get the new Album id. which will be 3 in the json response from the server
b) then send the images to /albums/3/photos where 3 is the new Album id.

How do I do that? I am looking at your examples. No similar examples. What can I do?

**Comment by saj-mits** [comment]
Directly add your data to the following
uploader.queue[0].formData = [ //Data Array ];
uploader.uploadAll();
