### ISSUE TITLE
removing files on the server

### ISSUE THREAD

**Issue by eugenekgn** [nervgh/angular-file-upload#109]
```
   <button type="button" class="btn btn-danger btn-xs" ng-click="item.remove()">
                                <span class="glyphicon glyphicon-trash"></span> Remove
                            </button>
```

clicked the file get removed from the client but there is no call or url to specify to remove that file from the server, can is this possible to do - it does not seem as if there an even to bind to that can do this.

The same is true for the following call uploader.clearQueue()

Thanks for writing this plug in.

Eugene

**Comment by faisalwebpro** [comment]
add removeFile('{{ item.file.name }}') in ng-click
<button type="button" class="btn btn-danger btn-xs" ng-click="item.remove(); removeFile('{{ item.file.name }}')">
                                <span class="glyphicon glyphicon-trash"></span> Remove
                            </button>

add this code in js controller below this code .controller('AppController', ['$scope', 'FileUploader', '$http', function($scope, FileUploader, $http) {
        var uploader = $scope.uploader = new FileUploader({
            url: 'upload.php'
        });

	$scope.removeFile = function (attachment){
	  var path = 'delete.php';

$http({
url : path,
data : attachment,
method : 'POST',	
headers: {
'Content-Type': undefined
}
})
.success(function(result){
//alert(result);
});
    } 
make another php file delete.php and put this code in delete php 

<?php


$postdata = file_get_contents("php://input");
$path="uploads/".$postdata;   // change path as per your requirment

unlink($path);


?>

**Comment by sirissksv** [comment]
I have added like above to delete file on server using delete.php but I couldnot get anything in POST. Please help
