### ISSUE TITLE
Chrome re-add issue

### ISSUE THREAD

**Issue by ScottWye** [nervgh/angular-file-upload#115]
You can't add a file once you remove it in Chrome.
1. Add file to queue.
2. Remove file from queue.(It doesn't matter if the file is uploaded or not)
3. Try to re-add the file.
4. File doesn't show in queue
5. Select different file.
   6 Remove that file.
   7 Add original file.(only after adding a different file can the original file be added again)

Please let me know if anyone has had this issue or knows a work around.

**Comment by gerome0123** [comment]
@skynet-tx do you use that FAQ??
