### ISSUE TITLE
FormData just before uploading

### ISSUE THREAD

**Issue by agronom413** [nervgh/angular-file-upload#123]
I want to send form data along with a file however it doesn't pick up a dynamically added data. Please advice.

var uploader = $scope.uploader = $fileUploader.create({
...
uploader.formData.push({ name: 'will-be-sent' });
$scope.uploadFile = function() {
            uploader.formData.push({ name: 'wont-be-sent' });
            uploader.uploadAll();
};

**Comment by saj-mits** [comment]
Directly add your data to the following
uploader.queue[0].formData = [ //Data Array ];
uploader.uploadAll();
