### ISSUE TITLE
How do you disable dropzone?

### ISSUE THREAD

**Issue by eugenekgn** [nervgh/angular-file-upload#126]
Can you please tell me how to disable dropzone just like the following command 

```
As other widgets based on jQuery UI Widget, the File Upload widget can be disabled/enabled:

$('#fileupload').fileupload('disable');
$('#fileupload').fileupload('enable');
```

https://github.com/blueimp/jQuery-File-Upload/wiki/API

**Comment by mrn-aglic** [comment]
will this option be added anytime in the future?
