### ISSUE TITLE
Change URL

### ISSUE THREAD

**Issue by nanox77** [nervgh/angular-file-upload#128]
Hello,

I have a problem with url and parameters:

I want to upload a file (file) with parameters (file name and folder name), but when creating the Uploader still do not know the final path of EACH file to upload (multiple files).

I tried to implement events such as 'afteraddingfile' and 'beforeupload' and change the FormData but it did not work.

What should be the way to dynamically change the url? 

Thank you very much!

PS: sorry for my English!

**Comment by Webbrother** [comment]
+1 to this question!
Where can I see it? 
Can you give direct link to faq/documentation?

**Comment by nervgh** [comment]
https://github.com/nervgh/angular-file-upload/wiki/FAQ#2-how-to-update-fileitem-options-before-uploading

https://github.com/nervgh/angular-file-upload/issues/112
https://github.com/nervgh/angular-file-upload/wiki
