### ISSUE TITLE
IE 9 - After file upload browser prompts to save or download the response from the server

### ISSUE THREAD

**Issue by rmanalo623** [nervgh/angular-file-upload#137]
After much trail and error, I have gotten the file upload to work in IE 9. The problem I'm having now is that IE 9 displays a prompt to save or download the response from the server. 

See: http://stackoverflow.com/questions/6114360/stupid-ie-prompts-to-open-or-save-json-result-which-comes-from-server

Please let me know if you have any ideas on how to fix this?

**Comment by robsongdev** [comment]
hi @monkeymonk 

Can you show some sample code for fix this issue?

**Comment by monkeymonk** [comment]
Hi @robsongdev, 

the sources are not in my hands right now but its quite simple.

Your backend need to send the response with a `content-type="text/plain"` then you parse that plain text to JSON:
```
uploader.bind('success', onUploadSuccess);

function onUploadSuccess(event, xhr, item) {
    $scope.fileUploaded = angular.fromJson(xhr.response); // or $.parseJSON(xhr.response);
}
```

**Comment by wmfairuz** [comment]
I'm having the same issue and solved it using proposed solution by @monkeymonk . When changing the content-type to plain/text, IE stops prompting to save a file.
