### ISSUE TITLE
How to use two file-upload in one page?

### ISSUE THREAD

**Issue by renanaragao** [nervgh/angular-file-upload#144]
When I use the file-upload twice on the same page only works the first added.

**Comment by m-marko** [comment]
Hello. I have the same issue. I use FileUploader(initialized as new FileUploader())  inside of the directive with isolated scope. When I have multiple directives on the same page, only FileUploader callbacks on first directive are fired. Any ideas?

**Comment by renanaragao** [comment]
Check my comment of the day 29 May 2014

**Comment by demoalex** [comment]
@nervgh closed this in https://github.com/nervgh/angular-file-upload/commit/6e5cc251a3110eb7fc68bd38d7229b81966cb665 but it still doesn't work. Should be reopend?

**Comment by demoalex** [comment]
Sorry, I've got why this happend.

I've initialized all uploaders on app.run
like this
```javascript
angularApp.run(function($rootScope){
     $(":file").filestyle({
         input: false,
         icon: "glyphicon-cloud-upload",
         buttonText: "Upload files",
         buttonName: "btn btn-sm btn-primary",
         badge: false
     });
});
```

when I switched to inline initialization, all works fine:
```html
<input type="file" nv-file-select="" 
  uploader="lang.uploader" multiple="multiple" class="filestyle" 
  data-input="false" data-buttonName="btn-primary" 
  data-iconName="glyphicon-cloud-upload" data-buttonText=" Upload files"/>
