### ISSUE TITLE
Send File in formData key

### ISSUE THREAD

**Issue by Zaylril** [nervgh/angular-file-upload#161]
Hey,

Is there an easy to include the sent file within the formData request object for example:

```
formData : {
  file : fileData,
  resource_type : 'image',
  format: "jpg"
}
```

As opposed to sending the file direct along with the formData?

Thanks

**Comment by kavishwedcraze** [comment]
@Zaylril hi I am trying to send file with some more data but it's not working
Below is my code:
`var uploader = $scope.uploader = new FileUploader({`
`  ` `         url: SERVER_URL + '/app/upload_photos/',`
`  ` `         headers: {'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}`
   ` });`
`uploader.onBeforeUploadItem = function(item) {`
`  ` `      item.formData = {data: 'someID', file: item.file.name};`
`  ` `        // item.formData.push({data: albumID}, {file: item.file.name});`
`  ` `      console.log('onBeforeUploadItem',item);`
`    };`


I have tried every method but it's not sending any data to backend
