### ISSUE TITLE
get the server response

### ISSUE THREAD

**Issue by melofon** [nervgh/angular-file-upload#162]
Hello!
I'm trying to use your module to upload data files into web application database. Server returns some statistics about uploaded file. How can I get this response from client side?

**Comment by sieira** [comment]
I'm getting `Error: uploader.bind is not a function` when doing that

**Comment by sieira** [comment]
It may be a good idea to make upload() return a promise...

**Comment by sieira** [comment]
Ok, sorry, I just saw this :https://github.com/nervgh/angular-file-upload/wiki/Module-API#directives
