### ISSUE TITLE
uploader.clearQueue() does not clear the input field.

### ISSUE THREAD

**Issue by espizo** [nervgh/angular-file-upload#166]
I upgraded from 0.3.1 to 0.5.7 and I noticed that `uploader.clearQueue()` no longer removes the file name from the input field.

It still says `[Browse...] previously_selected_file.jpg` where it earlier would say `[Browse...] No file selected.` after calling `uploader.clearQueue()`.

I'm using angular-file-upload with single files only.

**Comment by plmetz** [comment]
I just started using angular-file-upload and it seems like in the newest version (1.1.5) this issue remains. I was looking for the same functionality to have the input field cleared upon calling `uploader.clearQueue()` but when using a single file upload input `<input type="file" nv-file-select="" uploader="uploader">` the input remains populated.

**Comment by totycro** [comment]
I'm experiencing this as well with 1.1.5 and would appreciate a fix very much.

**Comment by al-nkow** [comment]
input(type="file", ng2FileSelect, [uploader]="uploader", (change)="$event.target.value = ''")

**Comment by theo4u** [comment]
@al-nkow  don't understand your comment here

**Comment by xgqfrms** [comment]
1. `document.getElementById("uploadCaptureInputFile").value = "";`

2. `input.replaceWith(input.val('').clone(true));`
