### ISSUE TITLE
Processing item objects one at at time when selecting multiple files

### ISSUE THREAD

**Issue by fernandofmarte** [nervgh/angular-file-upload#178]
Hey,

Great uploader, by the way.  Seems to be working great, but I'm not sure if there is something built in for this, but I haven't been able to figure it out.  

I want to allow a user to upload multiple files at time.  After they choose their photos, I want to insert the item information (file name, size, etc) before I upload.  I need to update a database after the file is added to the queue.  After I get a response back from the db that the info is inserted, then I call item.upload() to send the file.   I added this logic into the 'afteraddingfile' binding.

The issue that I'm running into is that if I select multiple files, the 'afteraddingfile' event gets fired simultaneously for all the items, causing a collision in the database.  

Is there a way to trigger that event synchronously?  I was trying little hacks by adding a timeout, but that wasn't working.  I was also looking into adding my logic into the 'afteraddingall' event, but then it fires off the same actions for items already in the queue.

Thanks for your help.  I don't think this is a bug, just a question.  Below is a small example of what I'm trying to achieve, but fails for multiple images selected (I added the timeout to see if it would help, but doesn't): 

 uploader.bind('afteraddingfile', function (event, item) {  
    var url = '/add_to_db?filename=' + item.file.name+ '&callback=JSON_CALLBACK';
    $http.jsonp( commerceUrl )
        .success(function(data) {
            var dbId = data.dbId;
            item.dbId = db.Id; // want to use the upload queue to store all my info.
            setTimeout( function(){item.upload()},500 ); 
        })
        .error(function(data) {
            console.log( 'nope, got an error', JSON.stringify(data));
    });
});

**Comment by itorian** [comment]
Hi nervgh,
Sorry I would like to ask a question related to this issue.
When I select x images to upload I see x number of POST requests hitting server. But I wish to send x images in one POST request.
Angular code is really well written here which I appreciate but I novice :(
![post requests](https://cloud.githubusercontent.com/assets/3646552/8644125/1d9453cc-295a-11e5-8bf7-5abd4555ea87.png)
Please help me on minimum changes in the code to achieve this.
