### ISSUE TITLE
Sending File's Metadata to C#

### ISSUE THREAD

**Issue by ArjaaAine** [nervgh/angular-file-upload#179]
Great tool by the way.. Saved me a LOT of work!
I am using IE9.. so unfortunately I can't use the Html5 File API. 

What I am trying to do is, have the user attach files to the UI.. they then go ahead and fill out the rest of the form and if they click submit.. I used the attached files information and submit it to the server. 

I want to pass the file information through a $http call.. But I am not sure what should I pass through the $http so that my C# controller gets the file's metadata and not just the name. 

Thanks!

**Comment by zinduyaar** [comment]
Hi nervgh the above link https://github.com/nervgh/angular-file-upload/blob/master/src/module.js#L437 you mentioned is not working.
Please suggest something as I am facing the same issue, how I can use your plugin for MVC C# controller thanks

**Comment by Govind15** [comment]
@ArjaaAine  even i am facing same issue, I am calling my c# web api controller to upload files. I have 2 text boxes , checkbox and file upload control, but the service call not at all hitting the wep api. Can you say how did you solve the problem.
Service:
var save = function(newMessage)
    {
        return $http.post("api/proposal/saveMessage",newMessage);
    };
In Controller doing like this,
angular.forEach(uploader.queue.FileItem, function (item) {
                $scope.message.files.push({
                    file: item.file
              })
            });
