### ISSUE TITLE
Upgrade to 1.x.x - TypeError: "Uploader" must be an instance of FileUploader

### ISSUE THREAD

**Issue by davidwparker** [nervgh/angular-file-upload#183]
When migrating, following the guide: https://github.com/nervgh/angular-file-upload/wiki/Migrate-from-0.x.x-to-1.x.x

I now get the following error whenever I use any of the directives:

```
TypeError: "Uploader" must be an instance of FileUploader
    at link (http://localhost:3000/assets/angular/angular-file-upload.js?body=1:1231:27)
    at nodeLinkFn (http://localhost:3000/assets/angular/angular.js?body=1:6228:13)
    at compositeLinkFn (http://localhost:3000/assets/angular/angular.js?body=1:5638:15)
    at compositeLinkFn (http://localhost:3000/assets/angular/angular.js?body=1:5641:13)
    at nodeLinkFn (http://localhost:3000/assets/angular/angular.js?body=1:6222:24)
    at http://localhost:3000/assets/angular/angular.js?body=1:6422:13
    at http://localhost:3000/assets/angular/angular.js?body=1:7574:11
    at wrappedCallback (http://localhost:3000/assets/angular/angular.js?body=1:10950:81)
    at wrappedCallback (http://localhost:3000/assets/angular/angular.js?body=1:10950:81)
    at http://localhost:3000/assets/angular/angular.js?body=1:11036:26
```

The element:

``` html
<input nv-file-select uploader="{{uploader}}" type="file" multiple="" class="hidden-file" id="attachment{{uploader._timestamp}}">
```

Any thoughts on what I should be looking at?

**Comment by elise-fastpay** [comment]
What was the solution to this problem?

**Comment by davidwparker** [comment]
@elise-fastpay -

I have the following template (used in a directive "A"):
```html
<input nv-file-select uploader="uploader" type="file" multiple class="hidden-file" id="attachment{{uploader._timestamp}}" />
```

With that directive being called from another template in another directive "B":
```html
        <attachments-bar uploader="uploader"></attachments-bar>
```

And the uploader being created in directive "B" compile/pre:
```javascript
compile: function() {
      return {
        pre: function(scope, element, attrs) {
          scope.uploader = new FileUploader();
        },
```

**Comment by jackhsu978** [comment]
@nervgh the `ng-if` trick works for me. thanks!

**Comment by daleholborow** [comment]
I think, to avoid confusion, in @davidwparker 's solution, the uploader=uploader attribute on the attachments-bar directive definition is unnecessary, the nv-file-select uploader=x refers to the scope.x = new FileUploader... i was able to get this working without the additional attribute but found it confusing figuring out which "uploader" was which giving the same name being used all throughout the code. Hope this helps make it even clearer. Thanks guys, i was tearing my hair out for a while on this problem

**Comment by davidwparker** [comment]
@daleholborow - I only had to do that because I had an inner directive that needed access to the same Uploader as the parent directive. Works pretty well and is necessary for the two to talk.

**Comment by daleholborow** [comment]
Ooooh... then that might come in handy for me as well - I hadn't realised that subtlety. Cheers mate!

**Comment by cesarmarinhorj** [comment]
this was my first error when trying make things work.
basically, the code in example must be in first line of controller function. when i write it inside a function of my controller, gave me this error.
writing exactly like the code in example, in firsts lines of controller, and no error was found.
thanks!

**Comment by owenXin** [comment]
The ng-if = "uploader" works for me. @nervgh  Thanks very much. I'm integrate this upload to angular-formly, and it works fine in formlyConfig.setType().

**Comment by paresh-icoder** [comment]
var uploader = vm.uploader = new FileUploader({
              url: 'server/upload.php'
      });

**Comment by ishwarpohani** [comment]
@paresh-icoder 

See: https://github.com/nervgh/angular-file-upload/issues/574

You need to change references from "uploader" to "vm.uploader" in html file.

**Comment by Tailent** [comment]
ng-if also works for me.@nervgh,ありがとう :)
