### ISSUE TITLE
Error after angular.copy of a File object

### ISSUE THREAD

**Issue by nlwillia** [nervgh/angular-file-upload#186]
I've logged this against [angular directly](https://github.com/angular/angular.js/issues/8312), but I wanted to mention it here in case anyone runs into the same problem I did.  You won't see it in the [sample app](http://nervgh.github.io/pages/angular-file-upload/examples/simple/) because it's loading an older version of angular, but with angular 1.3.x, something about angular.copy results in an object that you can't access the name and size properties through in IE and Firefox.  So, given a FileItem, item.file.name causes an error, but item._file.name does not.

**Comment by radiart** [comment]
I have that issue with Angular 1.4.3
