### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by rcaval** [nervgh/angular-file-upload#189]
Is it possible to unit test my controller that uses angular-file-upload and check state after onBeforeUploadItem and onSuccessItem. Are there any examples we could start from?

**Comment by nottinhill** [comment]
@rcaval @nercgh This is exactly what I need. Do we have more code examples on this, I mean could someone provide some exemplary Jasmine test for unit testing angular-file-upload? Would be great not to re-invent the wheel for me in case you already have a working solution.

**Comment by nottinhill** [comment]
Ok I have implemented `addToQueue`which works and fires event handler but `.uploadAll`method does throw errors. Here is the code of what is working so far in case somebody wants to build tests for this module, too:


      it 'should add textfile to upload queue and fire event listeners', ->

        spyOn(mockScope.uploader,'onAfterAddingFile')
        spyOn(mockScope.uploader,'onAfterAddingAll')

        mockScope.uploader.addToQueue
          lastModifiedDate: new Date()
          size: 1e6
          type: 'text/plain'
          name: '/ci/unitTest.txt'

        $httpBackend.flush()

        expect(mockScope.uploader.onAfterAddingFile).toHaveBeenCalled()
        expect(mockScope.uploader.onAfterAddingAll.calls.argsFor(0)).toMatch(/[unitTest]/i)

Note the use of Jasmine's Regular Expressions, which parses through all the returned JSON tree successfully.

**Comment by nottinhill** [comment]
Now I want to fire from inside my tests:

    mockScope.uploader.uploadAll()

in order to 

    expect(mockScope.uploader.onCompleteAll).toHaveBeenCalled()

However calling `uploadAll()` seems not to fire. Any ideas how to do this from inside my testing suite?
