### ISSUE TITLE
Unknown provider: FileUploaderProvider <- FileUploader

### ISSUE THREAD

**Issue by jarandaf** [nervgh/angular-file-upload#199]
This used to work (older version) but now I'm getting this error which seems I can't get rid of.

I import scripts in the following order:

``` javascript
<script src="components/es5-shim/es5-shim.js"></script>
<script src="components/es5-shim/es5-sham.js"></script>
<script src="components/angular/angular.js"></script>
<script src="components/angular-file-upload/angular-file-upload.js"></script>
```

And my app also uses this dependency (between others):

``` javascript
myApp = angular.module('myApp', ['angularFileUpload']);
```

My controller:

``` javascript
myController = myApp.controller('MyController', ['FileUploader', function(FileUploader){
     var uploader = new FileUploader();
     // some other stuff...
}]);
```

Any hints what might be causing this?

**Comment by UltimateFighter** [comment]
i have the problem too. Here is my simple snipplet.

angular.module('myModule').factory('uploadhandler', function (FileUploader) {
});

this ist the error message:
"Error: [$injector:unpr] Unknown provider: FileUploaderProvider <- FileUploader <- uploadhandler" 

this i added to my bower line:
    "angular-file-upload": "~1.1.5",

**Comment by deepaksisodiya** [comment]
hey guys
I am facing the same problem
any any clue, what it error means?

**Comment by AnthonyAkentiev** [comment]
@deepaksisodiya Try using https://github.com/danialfarid/ng-file-upload ))

**Comment by Lemez** [comment]
@deepaksisodiya and to anyone else getting this issue. Fixing it for me was as simple as removing the dependency 'angularFileUpload' from app.js and instead moving it to the uploadController.js, like this: 

angular.module('MyApp',[
```
	'angularFileUpload'
	]).controller('uploadController', function($scope, FileUploader) {
        $scope.uploader = new FileUploader();
    });
```
