### ISSUE TITLE
ngThumb more dynamic

### ISSUE THREAD

**Issue by jswhisperer** [nervgh/angular-file-upload#206]
ngThumb works great in the repeat directive.

For some reason you can't use it outside of an ng-repeat?
ex div ng-thumb="{ file: uploader.queue[0]._file, height: 100 }"

Would like to have one large image preview of the most recent uploaded image along with the list of smaller thumbs.

**Comment by forcewill** [comment]
However ngThumb is included as part of the library

**Comment by gregbenner** [comment]
@forcewill I agree with the Author it's not the plugins main function using canvas can be found here: http://www.html5rocks.com/en/tutorials/file/dndfiles/

**Comment by sevkettayyip** [comment]
I can't use ng-thumb. Can someone help me?

**Comment by sevkettayyip** [comment]
How to use ng-thumb. Can someone upload jsfiddler link.

**Comment by emranch31** [comment]
ngthumb is not previewing image file over 15mb
