### ISSUE TITLE
allow upload of blob

### ISSUE THREAD

**Issue by bettysteger** [nervgh/angular-file-upload#208]
hey I just used https://github.com/alexk111/ngImgCrop to crop an image before uploading.. and now I did this to upload the blob with angular-file-upload:

```
  uploader.onBeforeUploadItem = function(item) {
    var blob = dataURItoBlob($scope.croppedImage);
    item._file = blob;
  };
```

This works just fine, but the file name is ignored because of this line: (and because of that the server doesn't recognize the file extension)

```
form.append(item.alias, item._file);
-->
------WebKitFormBoundaryGD5fYyZwXHVXxfZ4
Content-Disposition: form-data; name="avatar"; filename="blob"
Content-Type: image/png
```

It would be possible to add the name as third parameter, see https://developer.mozilla.org/en-US/docs/Web/API/FormData

what do you think of adding a third parameter or allow to upload a Blob in the first place?

btw: you made a really cool plugin!

**Comment by chin2** [comment]
Hi @nervgh
Is there any way to trigger upload image event? Actually i want to upload the image after inserting/updating the data?

**Comment by lpsBetty** [comment]
Hi @chin2, there is a property called ``autoUpload``, see https://github.com/nervgh/angular-file-upload/wiki/Module-API

**Comment by chin2** [comment]
Thanks @lpsBetty :+1:

**Comment by chin2** [comment]
Hi, @lpsBetty, 
Yes one thing is that i want to load a default image while rendering the FileUpload, is it possible?

**Comment by lpsBetty** [comment]
@chin2 So you want a image already in the queue? why do you want that?

**Comment by chin2** [comment]
@lpsBetty Actually while edit form, the uploaded image should be rendered. Have you got idea what is want exactly?

**Comment by lpsBetty** [comment]
@chin2  so you want a preview? just use the `result-image` like this:

````
 <!-- crop area if uploaded image-->
 <img-crop ng-show="image" image="image" result-image="croppedImage" area-type="square" result-image-size="150"></img-crop>
<!-- preview -->
<img alt="avatar_preview" ng-src="{{croppedImage}}" width="150" height="150" />
````

**Comment by jiangyanghe** [comment]
angular-file-upload how to add an parameter in url?
/**  the 'sn' is i want to  add it in the url**/
    var uploader = $scope.uploader = new FileUploader({
        url:url+'/ver/1.0/members/~/orgs/~/vas/'+sn+'/photo' ,
        autoUpload: false,
        headers:{'Authorization':accessKey+':0a632a6beaf24928b1ccfdf7bc680317','Accept':'*/*'}
    });
    uploader.onSuccessItem = function(fileItem, response, status, headers) {
        if(response.retCode == "SUCCESS"){
            $scope.vasPhoto = response.data.path;
        }else{
            alert(response.msg);
        }
    };

**Comment by amuste** [comment]
TH's @lpsBetty

**Comment by hfar** [comment]
Hi,
@lpsBetty is it possible to upload both original image and the cropped image?

**Comment by lpsBetty** [comment]
@hfar hmmm maybe with two end points?

**Comment by kkmoghe** [comment]
Hi, I want to use this uploader for uploading multiple files, I am able to do that, now new thing is when it comes to mobile I should be able to click picture & upload that, I think there is no direct way, so I used following for picture : <div class="visible-sm visible-xs form-group">
                        						<input type="file" accept="image/*" id="capture" capture="camera" > 
                        					</div>

I see the image on click of button & camera, but how to upload it now thro.' this uploader ?

**Comment by kkmoghe** [comment]
div class="visible-sm visible-xs form-group">input type="file" accept="image/*" id="capture" capture="camera">/div>

Above is the code I used, appreciate your help.

**Comment by lpsBetty** [comment]
@kkmoghe I think it should work automatically? What is your actual HTML ? you can use ```` to write code in github

**Comment by kkmoghe** [comment]
<div class="visible-sm visible-xs form-group">
	                        					 <input type="file" accept="image/*" id="captureImage" capture="camera" nv-file-select="" uploader="uploader" onchange="angular.element($('captureImage')).scope().$apply(function($scope){$scope.uploader.changeFile();});">
                        					 </div>

Above is the code.

**Comment by lpsBetty** [comment]
@kkmoghe ok this is definitely the wrong thread for your question! why do you use the ``onchange`` attribute.. there is no need for that!

First: was is your controller code?  Hopefully you define ``$scope.uploader`` ?
Second: what do you want to do? When you select an image immediately upload? Then here is the solution in your controller, just add:

````
$scope.uploader.autoUpload = true;
````

**Comment by kkmoghe** [comment]
Hi Bettina,
Sorry to post it in wrong thread, but your help is much appreciated.Sorry to post it in wrong thread, but your help is much appreciated.

yes I have $scope.uploader
My requirement is not to immediately upload, I should be able to upload multi-files in desktop as well as mobile, so for desktop it works :
I am pasting my uploader declaration & my tpl code to use that.
So desktop it works, but for photo, I used that capture tag, but some how it is ignoring it, in mobile I am displaying two buttons one for capture=camera and other like normal desktop, camera is clicking & I see the file name after that, but its not getting uploaded, so I think I am missing some thing, where it is going wrong ?






uploader is defined in controller as : 

    var uploader = $scope.uploader = new FileUploader({
        sendAllAtOnceItemsMultipleFileInputs: false,
        url: '',
        dataType: "json",
        cache: false,
        contentType: "application/json",
        aliases: 'file1,file2,file3,file4,file5,file6'
    });


									<div class="pr">
										<div class="form-group">
                        					 <div class="visible-sm visible-xs form-group">
	                        					 <input type="file" accept="image/*" id="captureImage" capture="camera" nv-file-select="" uploader="uploader" onchange="angular.element($('captureImage')).scope().$apply(function($scope){$scope.uploader.changeFile();});">
                        					 </div>
                        					<div id="ChooseBtnLabel" class="uploadfix" ng-show="checkNoOfAttachedFiles()">Select a File
                        						<input type="file" nv-file-select="" class="multi" 
                               					uploader="uploader"
                               					onchange="angular.element($('#ChooseBtnLabel')).scope().$apply(function($scope){$scope.uploader.changeFile();});"
                               					multiple />
                        					</div>
                        					
                        					<p ng-show="invalidAddFileAttemptMessage!==''" class="red">{{invalidAddFileAttemptMessage}}</p>

					                        <div class="MultiFile-list" id="files_wrap_list"
                    					         ng-repeat="item in uploader.queue">
	                            				<div ng-if="uploader.isUploading">Uploading...
	                            				</div>
					                            <div ng-hide="'NO_FILES_CHOSEN' === item.file.name">
	                				                <a class="MultiFile-remove" ng-click="removeItemFromQueue(item);">x</a>
	                                				<span class="MultiFile-label MultiFile-title" ng-bind="item.file.name"></span>
	                            				</div>
                        					</div>
   					                        
                        					</div>
                        					
                        				</div>
                        				
									</div>

**Comment by lpsBetty** [comment]
sorry I don't know why!

**Comment by lpsBetty** [comment]
@kkmoghe I don't use capture.. but maybe you should use another file uploader.. I saw that https://github.com/danialfarid/ng-file-upload supports capture!

**Comment by kkmoghe** [comment]
ok, thx. I got this uploader in my search, but nervgh uploader we are using in our existing other modules also, so my design team is reluctant to add this another uploader just for mobile photo capture, they suggest me to use nervgh or write your own plugin.

**Comment by ganu** [comment]
@lpsBetty, folowed your code but I'm getting null value in myCroppedImage on uploader.onBeforeUploadItem function. Check my following code

$scope.myImage=''; $scope.myCroppedImage='';

uploader.onAfterAddingFile = function(item) {
        var reader = new FileReader();
        reader.onload = function(event) {
          $scope.$apply(function(){
            $scope.myImage = event.target.result;            
          });
        };
        reader.readAsDataURL(item._file);
    };

    uploader.onBeforeUploadItem = function(item) {
      var blob = dataURItoBlob($scope.myCroppedImage);
      console.log(blob);
      item._file = blob;
    };

    var dataURItoBlob = function(dataURI) {
      var binary = atob(dataURI.split(',')[1]);
      var mimeString = dataURI.split(',')[0].split(':')[1].split(';')[0];
      var array = [];
      for(var i = 0; i < binary.length; i++) {
        array.push(binary.charCodeAt(i));
      }
      return new Blob([new Uint8Array(array)], {type: mimeString});
    };

Please give suggestion on this.

**Comment by hartjo** [comment]
$scope.croppedImage is Undefined

what am i missing? need help please 




var dataURItoBlob = function(dataURI) {
			var binary = atob(dataURI.split(',')[1]);
			var mimeString = dataURI.split(',')[0].split(':')[1].split(';')[0];
			var array = [];
			for(var i = 0; i < binary.length; i++) {
				array.push(binary.charCodeAt(i));
			}
			return new Blob([new Uint8Array(array)], {type: mimeString});
		};

		$scope.handleFileSelect = function (evt) {
			var file = evt.currentTarget.files[0];
			$scope.$apply(function ($scope) {
				$scope.myImage = URL.createObjectURL(file);
			});
		};

		

		var handleFileSelect=function(evt) {
			$scope.croppedImage = '';
			$scope.myImage = '';
			var file=evt.currentTarget.files[0];
			var reader = new FileReader();
			reader.onload = function (evt) {
				$scope.$apply(function($scope){
					$scope.myImage=evt.target.result;
				});
			};
			reader.readAsDataURL(file);
			console.log($scope.croppedImage);
			
		};
		angular.element(document.querySelector('#fileInput')).on('change',handleFileSelect);

		


		var uploader = $scope.uploader = new FileUploader({
            url: '/upload.php'
        });

        // FILTERS

        uploader.filters.push({
            name: 'customFilter',
            fn: function(item /*{File|FileLikeObject}*/, options) {
                return this.queue.length < 10;
            }
        });

        // CALLBACKS

        uploader.onWhenAddingFileFailed = function(item /*{File|FileLikeObject}*/, filter, options) {
            console.info('onWhenAddingFileFailed', item, filter, options);
        };
        uploader.onAfterAddingFile = function(fileItem) {

        };
        uploader.onAfterAddingAll = function(addedFileItems) {
            console.info('onAfterAddingAll', addedFileItems);
        };
        uploader.onBeforeUploadItem = function(item) {
        	console.log('=================');
        	console.log($scope.croppedImage);
        	var blob = dataURItoBlob($scope.croppedImage);
        	item._file = blob;
        };
        uploader.onProgressItem = function(fileItem, progress) {
            console.info('onProgressItem', fileItem, progress);
        };
        uploader.onProgressAll = function(progress) {
            console.info('onProgressAll', progress);
        };
        uploader.onSuccessItem = function(fileItem, response, status, headers) {
            console.info('onSuccessItem', fileItem, response, status, headers);
        };
        uploader.onErrorItem = function(fileItem, response, status, headers) {
            console.info('onErrorItem', fileItem, response, status, headers);
        };
        uploader.onCancelItem = function(fileItem, response, status, headers) {
            console.info('onCancelItem', fileItem, response, status, headers);
        };
        uploader.onCompleteItem = function(fileItem, response, status, headers) {
            console.info('onCompleteItem', fileItem, response, status, headers);
        };
        uploader.onCompleteAll = function() {
            console.info('onCompleteAll');
        };

        console.info('uploader', uploader);

**Comment by lpsBetty** [comment]
hmmm I really don't know what's the problem, but it could be a 'scope' inheritance problem, because of this I changed my cropped image model to an object to make sure that it set by the ngImgCrop! 

from ``croppedImage`` to ``cropped = {image: ''}``

Here is the full code:

````
/**
 * Show preview of cropped image
 */
uploader.onAfterAddingFile = function(item) {
  $scope.cropped = {image: ''};
  var reader = new FileReader();
  reader.onload = function(event) {
    $scope.$apply(function(){
      $scope.image = event.target.result;
    });
  };
  reader.readAsDataURL(item._file);
};

/**
 * Upload Blob (cropped image) instead of file.
 * @see
 *   https://developer.mozilla.org/en-US/docs/Web/API/FormData
 *   https://github.com/nervgh/angular-file-upload/issues/208
 */
uploader.onBeforeUploadItem = function(item) {
  var blob = dataURItoBlob($scope.cropped.image);
  item._file = blob;
};

/**
 * Converts data uri to Blob. Necessary for uploading.
 * @see
 *   http://stackoverflow.com/questions/4998908/convert-data-uri-to-file-then-append-to-formdata
 * @param  {String} dataURI
 * @return {Blob}
 */
var dataURItoBlob = function(dataURI) {
  // convert base64/URLEncoded data component to raw binary data held in a string
  var byteString;
  if (dataURI.split(',')[0].indexOf('base64') >= 0) {
    byteString = atob(dataURI.split(',')[1]);
  } else {
    byteString = decodeURI(dataURI.split(',')[1]);
  }
  var mimeString = dataURI.split(',')[0].split(':')[1].split(';')[0];
  var array = [];
  for(var i = 0; i < byteString.length; i++) {
    array.push(byteString.charCodeAt(i));
  }
  return new Blob([new Uint8Array(array)], {type: mimeString});
};
````

**Comment by madhurangaonbit** [comment]
@lpsBetty Could you please tell me how to trigger the upload  onAfterAddingFile function.
Currebtly im using this,
 $(document).on('change', '#fileInput', function(event) {
            uploader.onAfterAddingFile(event);
        });

But it is not working as it is.

**Comment by lpsBetty** [comment]
@madhurangaonbit  you don't need this JS, you can just add this line and the uploader will automatically upload the image: 

````
uploader.autoUpload = true;
`````

see https://github.com/nervgh/angular-file-upload/wiki/Module-API

**Comment by madhurangaonbit** [comment]
@lpsBetty Thank for looking to it.
But i was not able to make it right.
this is my plunker 
Please have a look.
http://plnkr.co/edit/qBrr53dQGyhm2gmRkUhN?p=preview
If you can point out some issues it will be very helpfull.

**Comment by hartjo** [comment]
im sorry for no response i have something to do on my work so.. btw thank you so much i got it work using your approach thank you so much :)

**Comment by gregui** [comment]
madhurangaonbit

        FileUploader.FileSelect.prototype.isEmptyAfterSelection = function() {
            return false;
        };

**Comment by LaneTwo** [comment]
@lpsBetty , thank you very much for your solution, finally solved my issue, I have struggled on that for several days.

**Comment by raysefo** [comment]
Hi @lpsBetty ,

On my IOS mobile application I am taking picture and then select a picture from gallery. After selecting this picture I am using ng-img-crop.js to crop this image and without saving this cropped image, trying to upload it to a server. (In this partivular example I am trying to upload local IIS) 	
I am using local IIS 7.5 and installed asp, isapi etc. Now I am getting 0 from the response. Image is not uploaded to the server and there is no error log on IIS. Would you please help me?

Best Regards.

Here is my sample js:
`angular.module('starter', ['ionic', 'ngCordova', 'ngImgCrop', 'ngFileUpload'])

.controller("ExampleController", ['$scope', '$cordovaCamera', 'Upload', '$timeout', '$cordovaFileTransfer', function ($scope, $cordovaCamera, Upload, $timeout, $cordovaFileTransfer) {

    $scope.takePhoto = function () {
        var options = {
            quality: 100,
            destinationType: Camera.DestinationType.DATA_URL,
            sourceType: Camera.PictureSourceType.CAMERA,
            allowEdit: true,
            encodingType: Camera.EncodingType.JPEG,
            targetWidth: 300,
            targetHeight: 300,
            popoverOptions: CameraPopoverOptions,
            saveToPhotoAlbum: true
        };

        $cordovaCamera.getPicture(options).then(function (imageData) {
            $scope.imgURI = "data:image/jpeg;base64," + imageData;
        }, function (err) {
            console.log(err);
            alert(err);
        });
    }

    $scope.choosePhoto = function () {
        var options = {
            quality: 100,
            destinationType: Camera.DestinationType.DATA_URL,
            sourceType: Camera.PictureSourceType.PHOTOLIBRARY,
            allowEdit: true,
            encodingType: Camera.EncodingType.JPEG,
            targetWidth: 300,
            targetHeight: 300,
            popoverOptions: CameraPopoverOptions,
            saveToPhotoAlbum: false
        };

        $cordovaCamera.getPicture(options).then(function (imageData) {
            $scope.imgURI = "data:image/jpeg;base64," + imageData;
            $scope.myImage = $scope.imgURI;

        }, function (err) {
            console.log(err);
            alert(err);
        });
    }

    $scope.myCroppedImage = '';

    $scope.upload = function (dataUrl) {

    Upload.upload({

        url: 'http://192.168.1.20/wcf/upload',
        data: {
            file: Upload.dataUrltoBlob(dataUrl)
        },

    }).then(function (response) {
        $timeout(function () {
            $scope.result = response.data;
            console.log(response.data);
            alert(response.data);
        });
        console.log(response.data);
    }, function (response) {
        if (response.status > 0) $scope.errorMsg = response.status
            + ': ' + response.data;
        alert(response.status);
    });

}

}]);`

**Comment by lpsBetty** [comment]
@raysefo what is IIS ? ;)

**Comment by raysefo** [comment]
@lpsBetty Internet Information Services (IIS) for Windows for my local PC :) Should I use file transfer plugin (https://www.npmjs.com/package/cordova-plugin-file-transfer) instead?

**Comment by raysefo** [comment]
any idea @lpsBetty ?

**Comment by lpsBetty** [comment]
hmm @raysefo  no sorry, I have no experience with IIS..

**Comment by raysefo** [comment]
Lets forget about IIS, as a result it is a server. What is the difference between file upload and file transfer? @lpsBetty

**Comment by MrSpark2591** [comment]
@lpsBetty  can we have 

                                formData = new FormData();
   				formData.append("categoryCode", $scope.category.name);
   				formData.append("request",item._file);
                                $http.post(URL,formData);

and this works great for mw when i pass it to java spring backend but the problem is it won't upddate item.progress property . 
any solution?

**Comment by lpsBetty** [comment]
@MrSpark2591 yeah that is because you are not using the fileuploader for uploading the actual image, you are just making your own POST request - if you use fileuploader with the correct functions (`uploadAll` or `uploadItem`) it works!

**Comment by 1043099804** [comment]
really helpful, thanks!

**Comment by 1043099804** [comment]
@lpsBetty ， really helpful， thanks！

**Comment by nicogaldo** [comment]
Hi @lpsBetty, It is able to upload the two images, the cropped and the original ?

**Comment by lpsBetty** [comment]
@nicogaldo yes you can send two separate requests ;)

**Comment by kolkov** [comment]
Hi! 
How to change Content-Length of cropped images?

My server log this:
```
multipart: Part Read: request declared a Content-Length of 107692 but only wrote 91307 bytes
multipart: NextPart: request declared a Content-Length of 107692 but only wrote 91307 bytes
```

**Comment by kolkov** [comment]
Poblem is self-destructed )))

**Comment by enuelmorales-snoop** [comment]
Hi, my problem is similar. " Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.". I work this plugin into Ionic 1 Framework. But i don't crop always. Please help me

**Comment by lpsBetty** [comment]
@enuelmorales-snoop where is this error coming from?
maybe you can paste the whole stacktrace!

**Comment by enuelmorales-snoop** [comment]
Okey, mi view code is:

<img-crop image="myImage"
    result-image="myCroppedImage" 					
    area-type="rectangle"		            
    change-on-fly="false"
    result-width="myCroppedImageW"
    result-height="myCroppedImageH"		            
    result-x="myCroppedImageX"
    result-y="myCroppedImageY"		             
    original-width="myOriginalW"
    original-height="myOriginalH"
    original-crop-x="myOriginalX"
    original-crop-y="myOriginalY"	            
    original-crop-width="myCroppedOriginalW"
    original-crop-height="myCroppedOriginalH">
 </img-crop>

<div id="crop">
	<img ng-src="{{myCroppedImage}}" width="{{myCroppedImageW}}" height="{{myCroppedImageH}}" class="myCroppedImage" />
</div>


The problem is when I mouseup on the corner the console log return " Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted. " and 
nothing happens and the corner does not move

**Comment by lpsBetty** [comment]
@enuelmorales-snoop I think you are posting in the wrong issue here, this is the **angular-file-upload** and not the **img-crop** repository.

**Comment by braindrained** [comment]
There is a way to get this work if autoUpload is set to true?

**Comment by lpsBetty** [comment]
@braindrained I don't understand, do you want to upload the image immediately before cropping?
Do you create the blob by yourself?

**Comment by braindrained** [comment]
@lpsBetty let me explain, I use angular file upload just for upload images, now I resize the image (maxWidth/maxHeight) in the backend.
The request now is to do it before upload the image, but with autoUpload  set to true your method doesn't work because the filereader stop to read the file after the upload.

**Comment by lpsBetty** [comment]
@braindrained Sorry, I am still not sure what you mean. 

Why do you need to upload a blob? If resizing the image in the backend you can just upload the image via autoUpload and that's it?

**Comment by braindrained** [comment]
@lpsBetty lol maybe I'm not explaining it properly (this is not my language :) ).

I've an application already working with the resize made in the backend.
The request by the customer is to do it before upload the image in order to not get the server too busy just in case of large amount of multiupload with large files.

**Comment by lpsBetty** [comment]
@braindrained and what do you use for cropping? just see this code for uploading a blob: https://gist.github.com/lpsBetty/2057e0bd0b4142d4070db0e1175ca47e

**Comment by braindrained** [comment]
@lpsBetty I've already tried your method but it does not work.
The problem is that with autoUpload set to true the onBeforeUploadItem is executed immediatly after the onAfterAddingFile and before that FileReader has ended to read the file, so the uploaded image is always the original and not the resized.

I resize the image this way:

```
uploader.onAfterAddingFile = function(item) {
    var reader = new FileReader();
    reader.onload = function (event) {
        var max_size = 1280;
        var tempImg = new Image();
        tempImg.src = reader.result;
        tempImg.onload = function () {
            if(this.width>max_size || this.height>max_size) {
                var canvas = document.createElement('canvas');
                canvas.width = max_size;
                canvas.height = max_size;
                var dimRatio = this.width / this.height;
                var padLeft = 0;
                var padTop = 0;
                if(dimRatio > 1) {
                    cropHeight = this.height;
                    cropWidth  = this.height;
                    padLeft = (this.width - this.height)/2;
                }
                if(dimRatio < 1) {
                    cropHeight = this.width;
                    cropWidth  = this.width;
                    padLeft = (this.height - this.width)/2;
                }

                document.body.appendChild(canvas);
                var ctx = canvas.getContext("2d");
                ctx.drawImage(this, padLeft, padTop, cropWidth, cropHeight, 0, 0, max_size, max_size);

                var dataURL = canvas.toDataURL("image/png", 1);
                var n = dataURL.indexOf(",");
                var data = dataURL.toString().substring(n+1);

                $scope.$apply(function () {
                    var ext = item.file.type.split("/")[1];
                    if (['jpg', 'jpeg', 'gif', 'png', 'pdf'].indexOf(ext) >= 0) {
                        var imgFile = b64toBlob(data,'image/png')
                        item._file = imgFile;
                        item.upload();
                    } else {
                        // invalid type
                    }
                });                    
            }
        };

    };
    reader.readAsDataURL(item._file);
};
```

**Comment by lpsBetty** [comment]
@braindrained I think you do not need a `$scope.$apply` and `item.upload()` here in your code. Either use `autoUpload=true` or `item.upload()` ...
Isn't this code uploading the original file and the resized file?

**Comment by braindrained** [comment]
I agree, thanks anyway.

**Comment by RobbertWolfs** [comment]
Thanks for this thread. Exactly needed this solutions 💯

**Comment by josencv** [comment]
For anyone who just wants to upload a blob file without extra data and does not care about compatibility with IE9 (and maybe IE10?) see #602

**Comment by thrinay** [comment]
I tried inserting the blob and didn't actually work with an existing image in the controller. I do will attach here the image of what the desired result should look like, and any advice or help is much more appreciated
Just the existing image should be dragged to the uploader. This is what the desired result is. Drag the image in the left corner to uploader
![screenshot from 2017-05-24 11-41-29](https://user-images.githubusercontent.com/9824922/27374624-c92edb58-566c-11e7-8c69-3ca3f419508c.png)

**Comment by blueror815** [comment]
Hi @lpsBetty 
I am going to edit existing photo of profile using angular-file-upload and img-crop.
Here is my code.
```
/**
                         * Show preview with cropping
                         */
                        uploader.onAfterAddingFile = function(item) {
                            $scope.croppedImage = '';
                            var reader = new FileReader();
                            reader.onload = function(event) {
                                $scope.$apply(function(){
                                    $scope.image = event.target.result;
                                });
                            };
                            reader.readAsDataURL(item._file);
                        };

                        /**
                         * Upload Blob (cropped image) instead of file.
                         * @see
                         *   https://developer.mozilla.org/en-US/docs/Web/API/FormData
                         *   https://github.com/nervgh/angular-file-upload/issues/208
                         */
                        uploader.onBeforeUploadItem = function(item) {
                            var blob = dataURItoBlob($scope.croppedImage);
                            item._file = blob;
                        };

                        /**
                         * Converts data uri to Blob. Necessary for uploading.
                         * @see
                         *   http://stackoverflow.com/questions/4998908/convert-data-uri-to-file-then-append-to-formdata
                         * @param  {String} dataURI
                         * @return {Blob}
                         */
                        var dataURItoBlob = function(dataURI) {
                            var binary = atob(dataURI.split(',')[1]);
                            var mimeString = dataURI.split(',')[0].split(':')[1].split(';')[0];
                            var array = [];
                            for(var i = 0; i < binary.length; i++) {
                                array.push(binary.charCodeAt(i));
                            }
                            return new Blob([new Uint8Array(array)], {type: mimeString});
                        };

                        /**
                         * @description save image for profile
                         */
                        $scope.saveImage = function() {

                            if ($scope.uploader.queue.length == 0) {
                                var blob = dataURItoBlob($scope.croppedImage);
                                var new_file = new File([blob], "default.png");
                                console.log("New File", new_file);

                                $scope.uploader.queue.push(new_file);

                                $scope.uploader.uploadItem(new_file);
                            } else {
                                $scope.uploader.uploadAll();
                            }
                        }
```
And my html is below.

```
<script type="text/ng-template" id="/selectImgModal.html">
    <div class="modal-header">
        <button type="button" data-dismiss="modal" aria-hidden="true" ng-click="cancel()" class="close">×</button>
        <h4  class="modal-title">{{'profile.SELECT_PROFILE_IMG' | translate}}</h4>
    </div>

    <div class="modal-body" style="min-height: 200px">
        <form>
            <input type="file" id="fileInput" nv-file-select="" uploader="uploader" />

            <div class="row">
                <div class="col-lg-7 col-sm-7 col-md-7">
                    <div class="cropArea">
                        <img-crop image="image" result-image="croppedImage"></img-crop>
                    </div>
                </div>

                <div class="col-lg-5 col-md-5 col-sm-7">
                    <h5 style="font-weight: bold">Your Profile Potrait</h5>
                    <div>
                        <img ng-src="{{croppedImage}}" />
                    </div>
                </div>

                <div class="row profile-img-btn-container">
                    <button type="button" class="btn btn-primary" ng-click="saveImage()">Save</button>

                    <button type="button" class="btn btn-default" ng-click="cancel()">Cancel</button>
                </div>
            </div>
        </form>
    </div>
</script>
```

So in order to edit existing photo id, user will click photo id of user.
Then new  modal to edit it will popup.
Here is my problem.
As you can see my angular code, i am making a File Object with blob and add it to queue and upload it.
But i am getting below error Msg.
```
service.js:115 TypeError: item._prepareToUploading is not a function
    at FileUploader.uploadItem (angular-file-upload.js:289)
    at ChildScope.SelectProfileImgController.$scope.saveImage (app.js:16017)
    at fn (eval at compile (service.js:115), <anonymous>:4:218)
    at expensiveCheckFn (service.js:115)
    at callback (service.js:115)
    at ChildScope.$eval (service.js:115)
    at ChildScope.$apply (service.js:115)
    at HTMLButtonElement.<anonymous> (service.js:115)
    at HTMLButtonElement.dispatch (service.js:115)
    at HTMLButtonElement.elemData.handle (service.js:115)
```

Could you please help me to fix this issue?

**Comment by lpsBetty** [comment]
@blueror815 I don't know why you need this IF `if ($scope.uploader.queue.length == 0) {` ..

shouldn't the uploader always have an item in the queue, when an user selects an image?

**Comment by FURQAN2050** [comment]
hi betty...AM just getting stuck on this. 
uploader.onAfterAddingFile = function (item) {
           //upload file right after the user adds a file
          
          
           console.info('After adding a file', item);
           $scope.croppedImage = '';
              var reader = new FileReader();
              reader.onload = function(event) {
                $scope.$apply(function(){
                  $scope.image = event.target.result;
                  console.log('scope image',$scope.image)
                });
              };
              reader.readAsDataURL(item._file);
              console.log('item file',item._file);
               uploader.uploadAll(); 
        };
        // --------------------
        uploader.onAfterAddingAll = function (items) {
          console.info('After adding all files', items);
        };
        // --------------------
        uploader.onWhenAddingFileFailed = function (item, filter, options) {
          console.info('When adding a file failed', item);
        };
        // --------------------
        uploader.onBeforeUploadItem = function (item) {
          console.log('cropImage',$scope.croppedImage);
         var blob = dataURItoBlob($scope.croppedImage);
            item._file = blob;
          console.info('Before upload', item);
          
          
        };
        // --------------------
        uploader.onProgressItem = function (item, progress) {
          console.info('Progress: ' + progress, item);
        };
        // --------------------
        uploader.onProgressAll = function (progress) {
          console.info('Total progress: ' + progress);
        };
        // --------------------
        uploader.onSuccessItem = function (item, response, status, headers) {
          console.info('Success', response, status, headers);
          // $scope.$broadcast('uploadCompleted', item);
          // $scope.load();
        };
        // --------------------
        uploader.onErrorItem = function (item, response, status, headers) {
          console.info('Error', response, status, headers);
        };
        // --------------------
        uploader.onCancelItem = function (item, response, status, headers) {
          console.info('Cancel', response, status);
        };
        uploader.onCompleteItem = function (item, response, status, headers) {
          console.info('Complete', response, status, headers);
          console.log(response.result);

          // $scope.currentContact.imageName = response.result.files.file[0].name;
          // $scope.currentContact.field = response.result.files.file[0].field;
          // $scope.currentContact.container = response.result.files.file[0].container;
          // $scope.currentContact.originalFilename = response.result.files.file[0].originalFilename;
          // $scope.currentContact.size = response.result.files.file[0].size;
          // $scope.currentContact.type = response.result.files.file[0].type;
          // $scope.tempImage=response.result.files.file[0];
          //console.log('temp image contact',$scope.tempImage);

          console.log('current afterContact uploading an image', $scope.currentContact);
          //$scope.cropImage(response.result.files.file[0]);
        };
        uploader.onCompleteAll = function () {
          console.info('Complete all');
        };

        var dataURItoBlob = function(dataURI) {
          var binary = atob(dataURI.split(',')[1]);
          var mimeString = dataURI.split(',')[0].split(':')[1].split(';')[0];
          var array = [];
          for(var i = 0; i < binary.length; i++) {
            array.push(binary.charCodeAt(i));
          }
          return new Blob([new Uint8Array(array)], {type: mimeString});
        };



HTML: <div style="  background: #E4E4E4;
                                overflow: hidden;
                                width:500px;
                                height:350px;"> <img-crop ng-show="image" image="image" result-image="croppedImage" area-type="square" result-image-size="250"></img-crop>
                                </div>
                                    <div><img ng-src="{{croppedImage}}" /></div>

**Comment by lpsBetty** [comment]
@FURQAN2050 can you please describe your problem? 
It would help to know the problem, before reading and understanding your code ;) 

I recommend using the latest solution from [here](https://gist.github.com/lpsBetty/2057e0bd0b4142d4070db0e1175ca47e)!

**Comment by FURQAN2050** [comment]
Thank you so much betty....it works perfectly fine.:)

**Comment by FURQAN2050** [comment]
betty are you there?

**Comment by FURQAN2050** [comment]
my ng file upload is not uploading the same file twice ....do you know any
thing about that?

**Comment by lpsBetty** [comment]
@FURQAN2050 do you clear the queue after uploading? is there an error or what happens when you reupload the same file?

**Comment by FURQAN2050** [comment]
There is no error when i reupload the file...but when i select the
file.then cancel it .and trying to upload the same file...it is not
showing. :(

**Comment by FURQAN2050** [comment]
can you come on skype please..just for while

**Comment by FURQAN2050** [comment]
am unable to get the error.
