### ISSUE TITLE
Programatically add files 

### ISSUE THREAD

**Issue by eugenekgn** [nervgh/angular-file-upload#211]
Is there a way to pragmatically add files? Let's say there are some files on the server when pages load and I want to add them to be displayed.

**Comment by unmanner89** [comment]
Hi guys!

How to obtain FileItem from remote URL?

I already tryed:

```
name: 'http://...
url: 'http://...
```

**Comment by emilhakobian** [comment]
I have the same issue , with displaying remote files (uploaded before) after page reload. I tried, but unfortunately it is not working.  
```javascript
 
var uploader.url = '/data/uploads/';
var fileItem = new FileUploader.FileItem(uploader, {
                        lastModifiedDate: new Date(),
                        type: 'image/jpeg',
                        size: 1311776,
                        name: 'logo.jpg'
                    });

                    fileItem.progress = 100;
                    fileItem.isUploaded = true;
                    fileItem.isSuccess = true;

                    uploader.queue.push(fileItem);

```

**Comment by mfundo** [comment]
This seemed to work for me (I'm using Angular):

Get files via $http, my JSON snippet looks like so:

"UploadedFiles": [
		{
			"name": "test.png",
			"size": 31.5,
			"dateModified": "today",
			"type": "image/png"
		},
		{
			"name": "test.png",
			"size": 31.7,
			"dateModified": "today",
			"type": "image/png"
		}
	]

for(var i = 0; i < $scope.user.UploadedFiles.length; i++ ){

	var fileItems = [];
	 fileItems[i] = new FileUploader.FileItem($scope.uploader, $scope.user.UploadedFiles[i]);

	fileItems[i].progress = 100;
	fileItems[i].isUploaded = true;
	fileItems[i].isSuccess = true;

	$scope.uploader.queue.push(fileItems[i]);

}

Hope this helps :)

**Comment by sakram80** [comment]
But where to put actual file object ? I want to preview files which are already uploaded ? Can somebody help me with this ?

**Comment by TonyLuo** [comment]
+1 how to preview the uploaded image with url ?

**Comment by TonyLuo** [comment]
finally got it. hope this code can help someone

var url = 'api/containers/comK/download/IMG_20130731_211048.jpg';
    $http.get(url,{responseType: "blob"}).
      success(function(data, status, headers, config) {
        var mimetype = data.type;
        var file = new File([data], "IMG_20130731_211048.jpg",{type:mimetype});
        var dummy = new FileUploader.FileItem(imageUploader, {
         
        });
        dummy._file = file;
        dummy.progress = 100;
        dummy.isUploaded = true;
        dummy.isSuccess = true;
        imageUploader.queue.push(dummy);

      }).
      error(function(data, status, headers, config) {
        alert("The url could not be loaded...\n (network error? non-valid url? server offline? etc?)");
      });

**Comment by sakram80** [comment]
Hi TonyLuo, 
It works for me as well thanks.

**Comment by nelsontubaina** [comment]
great plugin mate but when I add the dummy there is no event for added File. this screws up a litle my programming, I need a list of all the added files (including dummies) to edit other information in the files that will go into the database.

**Comment by nelsontubaina** [comment]
also why is the fileItem index ALWAYS null?

**Comment by tmccord** [comment]
I have been trying to show the already uploaded files into the uploader queue but it is not displaying. 

     var file;
        $http.get(url, { responseType: "blob" }).then(function(data, status, headers, config) {
            var mimetype = data.type;
            file = new File([data], "sample.jpg", { type: mimetype });
        }, function() {
        });
        var dummy = new FileUploader.FileItem(uploader, {});
        dummy._file = file;
        dummy.file.mediaId = 122;
        dummy.file.name = 'sample.jpg';
        dummy.file.type = 'image/jpeg';
        dummy.file.isProfile = false;

        dummy.progress = 100;
        dummy.size = 10000;
        dummy.isUploaded = true;
        dummy.isSuccess = true;
        uploader.queue.push(dummy);

**Comment by sakram80** [comment]
Put dummy FileItem inside get request, then it will work fine ...

**Comment by vlzkonopatov** [comment]
everything is fine but would also add to the image displayed ?

**Comment by Condor2708** [comment]
I have a requirement that requires IE11 .. The problem is File object is not supported? Do you know which object I can use in javascript to replace the File ? Thanks

**Comment by alkaj** [comment]
Hi! i have a problem trying to preview an image that is not on the same folder with my page, i would like to know if it is possible and how.
It previews normally with files(i mean image files) on the same path with the html page.
Thanks in advance...

**Comment by alvaromlg** [comment]
Maybe it helps someone. Using the plugin provided above just by adding the file to the queue it doenst tigger the event uploader.onAfterAddingFile(dummy);, you have to call it manually

**Comment by xkidro** [comment]
Hello! Sorry to bump this issue, I implemented this solution, however I couldn't not get it to refresh the list ? it does show my files if I add an item from the upload button or the drop zone.

**Comment by xkidro** [comment]
Hello guys, I managed to solve the problem, you just need to call uploader._render(); after you add to the queue.

**data** is my file array

```JavaScript
            var fileItems = [];

            for(var i in data){

                var fileItem = new FileUploader.FileItem(uploader, {
                    dateModified: 'today',
                    size: data[i].size,
                    type: data[i].type,
                    name: data[i].name
                });

                fileItem.progress = 100;
                fileItem.isUploaded = true;
                fileItem.isSuccess = true;

                fileItems.push(fileItem);
                uploader.queue.push(fileItem);
                uploader.onAfterAddingFile(fileItem);
            }

            uploader.onAfterAddingAll(fileItems);
            uploader._render();
        }
```

**Comment by thungasr** [comment]
Hi,
     I am running into some issues and couldn't able to identify how to get the dataURL for the file trying to upload. Ultimately i need to get the dataURL for each file and update in the mongoDB.

Appreciated your help on this.

**Comment by gerome0123** [comment]
@xkidro can you create a jsfiddle so i can understand more thanks 😘

**Comment by gerome0123** [comment]
@mfundo hi sir do u have a jsfiddle so i can undestand more thanks

**Comment by xkidro** [comment]
@gerome0123 I can't make a jsfiddle, here is the full controler.

`'use strict';

MetronicApp.controller('FileUploadCtrl', ['$scope', 'FileUploader', function($scope, FileUploader) {

    var id = $scope.$state.params.id;
    var api_intern = api + 'table=pdf&id='+id+'&';

    var uploader = $scope.uploader = new FileUploader({
        url: api_intern+'type=upload'
    });

    $('.file-drop-zone').on('click',function() {
      $('.file-drop-zone .hidden').click();
    });

    $.get(api_intern+'type=files',function(data){
        var data = $.parseJSON(data).data;
        if(data){
            var fileItems = [];

            for(var i in data){

                var fileItem = new FileUploader.FileItem(uploader, data[i]);

                fileItem.file.id = data[i].id;
                fileItem.progress = 100;
                fileItem.isUploaded = true;
                fileItem.isSuccess = true;

                fileItems.push(fileItem);
                uploader.queue.push(fileItem);
                uploader._onAfterAddingFile(fileItem);
            }

            uploader._onAfterAddingAll(fileItems);
            uploader._render();
        }
    });

    // CALLBACKS

    uploader.onWhenAddingFileFailed = function(item /*{File|FileLikeObject}*/ , filter, options) {
        //console.info('onWhenAddingFileFailed', item, filter, options);
    };
    uploader.onAfterAddingFile = function(fileItem) {
        //console.info('onAfterAddingFile', fileItem);
    };
    uploader.onAfterAddingAll = function(addedFileItems) {
        //console.info('onAfterAddingAll', addedFileItems);
    };
    uploader.onBeforeUploadItem = function(item) {
        //console.info('onBeforeUploadItem', item);
    };
    uploader.onBeforeRemoveItem = function(item) {
        if(item.isUploaded){
            $.get(api_intern+'type=delete_file&file_id='+item.file.id);
        }
        //console.info('onBeforeRemoveItem', item);
    };
    uploader.onProgressItem = function(fileItem, progress) {
        //console.info('onProgressItem', fileItem, progress);
    };
    uploader.onProgressAll = function(progress) {
        //console.info('onProgressAll', progress);
    };
    uploader.onSuccessItem = function(fileItem, response, status, headers) {
        fileItem.file.id = response.data.id;
        if(response.data.name){
            fileItem.file.name = response.data.name;
        }
        //console.info('onSuccessItem', fileItem, response, status, headers);
    };
    uploader.onErrorItem = function(fileItem, response, status, headers) {
        //console.info('onErrorItem', fileItem, response, status, headers);
    };
    uploader.onCancelItem = function(fileItem, response, status, headers) {
        //console.info('onCancelItem', fileItem, response, status, headers);
    };
    uploader.onCompleteItem = function(fileItem, response, status, headers) {
        //console.info('onCompleteItem', fileItem, response, status, headers);
    };
    uploader.onCompleteAll = function() {
        //console.info('onCompleteAll');
    };

    //console.info('uploader', uploader);
    
}]);`

**Comment by gerome0123** [comment]
@xkidro thanks for the reply can i see your view?

**Comment by miraghe** [comment]
In my  case nothing works, I guess maybe there are recent changes in $http.get that makes all of the above code fail for me, anyway, after testing all code of the examples in this post, I was able to make it work:

var url = 'directory/imagen.jpg';

$http.get(url, { responseType: "blob" }).then(
function(data, status, headers, config) {

var iname	= data.config.url.substr(data.config.url.lastIndexOf('/') + 1);
var idata 	        = data.data;
var itype	        = idata.type;
						    
var file = new File([idata], iname, { type: itype});
						    
uploader.addToQueue(file);

}, 
function() {
});

That's all, addToQueue calls to onAfterAddingFile and render.

In case you need to change file attributes like isUploaded, I think addToQueue options allow do it, but I was unable to change it, so instead I just use the next lines of code after the addToQueue call
							
var dummy = uploader.queue[uploader.queue.length - 1];
							
dummy.progress = 100;
dummy.isUploaded = true;
dummy.isSuccess = true;

Hope that helps someone.

**Comment by th3v0ice** [comment]
If you want to have $_FILES populated inside the PHP once you submit the data, you need to add the `var file =...` lines from the code snippet below.


```
var dummy = new FileUploader.FileItem(uploader, {
    lastModifiedDate: new Date(),
    size: item.size,
    type: 'video/mp4',
    name: item.name
});

//Following two lines
var file = new File(["hello"], item.name, {size: item.size, type:"video/mp4", lastModifiedDate: new Date()});
dummy._file = file;

dummy.progress = 20;
dummy.isUploaded = false;
dummy.isSuccess = false;

uploader.onAfterAddingFile(dummy);
uploader.queue.push(dummy);
```
