### ISSUE TITLE
IE9 - Response is a string wrapped in <pre>-tags

### ISSUE THREAD

**Issue by robinwassen** [nervgh/angular-file-upload#216]
Steps to reproduce in IE9:
1. Setup an upload endpoint that return an `application/json` response
2. Setup an uploader with `onCompleteItem` callback
3. Console.log the `response` parameter

Expected outcome: The response JSON as a JSON-object

Actual outcome: The response JSON as a string wrapped in pre-tags.

![screen shot 2014-08-19 at 13 37 50](https://cloud.githubusercontent.com/assets/302151/3965318/55e24404-2795-11e4-89ea-a09f33ad0e48.png)

I will investigate what causes this in IE9, the response is working as intended in Chrome.

**Comment by wmfairuz** [comment]
@gohilumesh Your solution helps a lot. Thanks.

**Comment by bawigga** [comment]
+1 to @gohilumesh solution.

**Comment by hnq90** [comment]
I'm using this regex to match JSON string from response.
```
regex = new RegExp('{.*?}', 'gm'),
data = response.match(regex);
```

**Comment by irbian** [comment]
@gohilumesh Just in case, maybe you prefer (/^<pre>/i).test(response) instead of (/^<pre>/).test(response), I received <PRE> on my IE response
