### ISSUE TITLE
File Content Empty

### ISSUE THREAD

**Issue by patrickhousley** [nervgh/angular-file-upload#218]
I am currently experiencing an issue where when I attempt to upload a file, the file content is missing from the request payload. I am using Chrome 36. This issue is actually happening when using the examples from this Github site.

Below is the payload upon calling the uploadAll function:

```
------WebKitFormBoundaryKeav0AJ3auCA4p7B
Content-Disposition: form-data; name="json"

{"fileName":"profile.xml","description":"Test"}
------WebKitFormBoundaryKeav0AJ3auCA4p7B
Content-Disposition: form-data; name="file"; filename="angular-file-upload-master.zip"
Content-Type: application/x-zip-compressed


------WebKitFormBoundaryKeav0AJ3auCA4p7B--
```

**Comment by joshikiran** [comment]
Use this directive,

myApp.directive("fileread", [function () {
    return {
        scope: {
            fileread: "="
        },
        link: function (scope, element, attributes) {
            element.bind("change", function (changeEvent) {
                var reader = new FileReader();
                reader.onload = function (loadEvent) {
                    scope.$apply(function () {
                        scope.fileread = loadEvent.target.result;
                    });
                }
                reader.readAsDataURL(changeEvent.target.files[0]);
            });
        }
    }
}]);
