### ISSUE TITLE
uploading large Files Fails

### ISSUE THREAD

**Issue by sraparla** [nervgh/angular-file-upload#222]
Whenever I upload a large file (in my case a zip file size aroung 177.1MB) it is showing an empty array on the server. I checked my php.ini files and i followed the recommendation said by the below author
http://www.sitepoint.com/upload-large-files-in-php/
But i still don;t see the item on the server but i still get the onCompleteAll called

**Comment by yoyoprs** [comment]
Hello, same problem with 1.1.5, the post is empty :(
