### ISSUE TITLE
uploadAll sending stale formData

### ISSUE THREAD

**Issue by PawelDecowski** [nervgh/angular-file-upload#225]
I have a form which, in addition to uploading a file, sends some other fields. For clarity, I send only one field in this example:

``` JavaScript
$scope.save_with_upload = function(user) {
    $scope.uploader.formData = [{
        name: user.name,
    }];

    $scope.uploader.uploadAll();
}
```

Let’s say the value of the `name` input is _Test 1_.
1. When I first load the page and click _Save_, it sends the file but doesn’t send `formData` at all.
2. Then I change `name` field to _Test 2_ and hit _Save_. It sends the file and `formData`, **but** the value of `name` it sends is _Test 1_.
3. Then I change `name` field to _Test 3_ and hit _Save_. It sends the file and `formData`, **but** the value of `name` it sends is _Test 2_.
4. … and so on …

So it seems to always send the data that was assigned to `formData` _before_ the last call to `uploadAll`.

To clarify: If I do `dir(user, $scope.uploader.formData)` just before calling `uploadAll`, it shows correct up-to-date values in both.

I’ve been struggling with it for a few hours and just can’t seem to see what’s wrong. Any ideas?

**Comment by michaelmccarver** [comment]
$scope.uploader = new FileUploader({
        url: $scope.uploadUrl,
        removeAfterUpload: true,
        onBeforeUploadItem: function (item) {
            var stuff = {
                profiles: [1426, 1427, 1428],
                profiles_groups: '',
                upload_type: 'BROWSER',
                username: $scope.username,
                file_name: $scope.uploader.queue[0].file.name,
                file_size: $scope.uploader.queue[0].file.size,
                file_type: $scope.uploader.queue[0].file.type,
                file_created_date: 135479928,
            }
            item.formData.push(stuff);
        },
        onSuccessItem: function (item, response, status, headers) {

        },
        queueLimit: 1,
    });

**Comment by yasharma** [comment]
one can also do like that, if someone wants to send data on click of button with attached function ``save()``

```
$scope.uploader.onBeforeUploadItem = function(item) {
	item.formData.push($scope.post);
};

$scope.save = function(user) {
	$scope.uploader.uploadAll();
};
```
``$scope.post`` will contains your data eg. ``title, body``.

**Comment by sebastianfelipe** [comment]
On the server side, how can you get the data in that formData? I can't find it, I tried in req.body, req.query, req.params, ctx.args (loopback nodejs). Thanks.

**Comment by yasharma** [comment]
@sebastianfelipe you can get your uploaded file on server side within `req.file` and data would be in `req.body`.

**Comment by sebastianfelipe** [comment]
mmm... I can't receive anything in those variables, I'm using loopback, and in the beforeRemote method it still without appear. In the afterRemote method I can get access at the file variable, but not before. I would like to use the req.body, that is the only but it appears after the whole file has been uploaded, and is late to do some staff, like reject the file :c
