### ISSUE TITLE
e2e testing using protractor... error

### ISSUE THREAD

**Issue by Davei234** [nervgh/angular-file-upload#228]
Hi, I'm using test code similar to this, in Protractor:

``` js
it('should upload file', function() {
  var fileToUpload = '../some/path/foo.txt',
  var absolutePath = path.resolve(__dirname, fileToUpload);
  $('input[type="file"]').sendKeys(absolutePath);
  $('#uploadButton').click();
});
```

But getting this error when running Protractor (using Chrome):

```
Failed to load resource: net::ERR_FILE_NOT_FOUND http://localhost:3000/api/uploadFile
```

This is happening at line 499 of angular-file-upload.js:

``` js
xhr.send(form);
```

If I then refresh the page and try the upload again, it works fine. It's just the automated Protractor test is missing something it seems. Thoughts? Thanks.

**Comment by aosi87** [comment]
How you did that?, i cant select the file inside the filePicker
