### ISSUE TITLE
nvFileOver's class doesn't get removed when file is moved out from the element

### ISSUE THREAD

**Issue by mr-moon** [nervgh/angular-file-upload#231]
Just as subj. I'm on `OS X 10.9 Chrome 37.0.2062.94`,

**Comment by shinrox** [comment]
This issue is still happening, go to example pages then drag a file over/out the window.

Tested on Mac OSX **10.10.5**  
Chrome **44.0.2403.157**  
Firefox **40.0.3**

**Comment by chaim-kedem** [comment]
I have the same issue, and this is my workaround.
```javascript
element.on('dragleave', function () {
	$(this).removeClass('file-over-now-class');
});
```

**Comment by kuafucode** [comment]
+1 even exists in example link

**Comment by celsomtrindade** [comment]
+1 same here. On my page and on example link. tested on chrome and firefox. Both with same issue.

The class only get removed if the file is added to queue. But if i hover the file on the drop zone and leave without adding the file, the class will stay applied.

**Comment by pyrostrex** [comment]
Just to add to @chaim-kedem's workaround, if you have child inside the element, you should add `pointer-events: none;` to the css of your child element to prevent flickers. Credits to http://stackoverflow.com/a/14027995

**Comment by v-zabavsky** [comment]
A simple decorator to the `nvFileOver` directive:
```
(function () {
    'use strict';
    appModule.config(function ($provide) {
        $provide.decorator('nvFileOverDirective', function ($delegate) {
            var directive = $delegate[0],
                link = directive.link;

            directive.compile = function () {
                return function (scope, element, attrs) {
                    var overClass = attrs.overClass || 'nv-file-over';
                    link.apply(this, arguments);
                    element.on('dragleave', function () {
                        $(this).removeClass(overClass);
                    });
                };
            };

            return $delegate;
        });
    });
})();
```
Thanks @chaim-kedem for the workaround.
I hope that helps.

**Comment by thijsw** [comment]
In addition to the fix proposed by @chaim-kedem: the fix shouldn't depend on jQuery because you could just use `element` its `removeClass()` method
```js
element.on('dragleave', function () {
    element.removeClass('file-over-now-class');
});
```

**Comment by luncht1me** [comment]
Nothing here has really worked flawlessly for me yet..... Can we get a patch that handles drag leave ??

**Comment by liadlivnat** [comment]
Hello ?? can anyone commit a fix for that ?

**Comment by gimoteco** [comment]
The problem still happening in version 2.2.0, you can check in the sample pages. When you get out from drop zone the over-class remains.

**Comment by nestdimon** [comment]
+1

**Comment by napalm684** [comment]
+1

**Comment by RemyMilia** [comment]
+1

**Comment by rknell** [comment]
+1

**Comment by blackmiaool** [comment]
```
$(document.body).mouseenter(function(){
    $(this).removeClass("[the class]");
})
```
This makes the target page not that bad.

**Comment by PeterClough** [comment]
Seems to be this line on line no. 1706 of angular-file-upload.js I wonder why it's there...

if (event.currentTarget === this.element[0]) return;

**Comment by hacknplan** [comment]
If you replace this:
```
FileDrop.prototype.onDragLeave = function onDragLeave(event) {
                    if (event.currentTarget === this.element[0]) return;
                    this._preventAndStop(event);
                    forEach(this.uploader._directives.over, this._removeOverClass, this);
                };
```
with this:
```
FileDrop.prototype.onDragLeave = function onDragLeave(event) {
                    forEach(this.uploader._directives.over, this._removeOverClass, this);
                };
```
seems to work as I expected.

**Comment by jameseddyedwards** [comment]
This line appears to be added for a flickering issue for Chrome which I'd imagine could have been solved with CSS alone. I think it needs to take into account whether the nv-file-over directive is applied to the same element as the nv-file-drop so actually changing this to a !== seems to make more sense and is the fix I've applied.

**Comment by karq20** [comment]
Does this issue still exist?

**Comment by MGZero** [comment]
Still not working in 2.5.0
