### ISSUE TITLE
Limit the drop zone to accept only one file

### ISSUE THREAD

**Issue by pipja** [nervgh/angular-file-upload#232]
For the <input> button you can limit the number of files selected by excluding "multiple". I wonder what is the equivalent option for drop zone, if any? There are cases where I want to support both file browser and drop zone methods, but I want to limit to single file selection.

If the user select multiple files, only the first alphabetically ordered file will be selected and put into the queue. Cheers.

**Comment by maeishoj** [comment]
this is not enterily correct, because if I limit to 2 files and select 4, it will still look like i can upload all the 4 files, but it will discard 2 of them, and the user would not probably understand...
