### ISSUE TITLE
How add form validation

### ISSUE THREAD

**Issue by jolle-c** [nervgh/angular-file-upload#243]
I have successfully added extra input fields to each file being uploaded and figured out how to send them along with the upload.
But, some of the fields are required. And I have not figured out how to disable the upload, or to check before upload that all required fields have data.
Preferably I'd like to disable only files that miss data and allow uploading all files where form data validate.

Any clues on how to do that?

**Comment by UltimateFighter** [comment]
but was was with the uploadAll Button?
