### ISSUE TITLE
Troubles with IE9

### ISSUE THREAD

**Issue by scottybrown** [nervgh/angular-file-upload#245]
I've had some trouble getting this working in IE9.
- I can get my application working just like the simple and image preview demos, but unfortunately this isn't quite 'working'. The file pretends to upload, but has a size of null and cannot be opened.
- The demos appear to work - the file uploads with a tick. But these hide the image preview and size columns when viewed on IE9, and there's no way to view the uploaded file. For these reasons I think they don't actually work, the file doesn't upload, they just pretend to work.
- I'm using a content type of text/plain as I've seen recommended
- I've seen recommendations to use the IE9 shim for ES5, but this shouldn't be necessary as IE9 supports ES5. Also, the demos should be working.
- I have seen the comment here (https://github.com/nervgh/angular-file-upload/issues/73#issuecomment-36672366), it seems the lines to be commented out no longer exist in the example

Given that my application does the same thing as the demos, I suspect it doesn't work for IE9 at all.

**Comment by stripathix** [comment]
Is there any way to show image preview in IE 9?  Because using this plugin i am not able to it.
