### ISSUE TITLE
TypeError: "Uploader" must be an instance of FileUploader

### ISSUE THREAD

**Issue by dlodeprojuicer** [nervgh/angular-file-upload#250]
Hi. I have been trying to use the library inside **[angularschemaform](http://github.com/Textalk/angular-schema-form/)** and i keep getting this error `TypeError: "Uploader" must be an instance of FileUploader`.

When used outside angularschemaform, it works fine. I thought it could be an angular version issue, but if that is so it should throw the same error when used outside of angularformschema.

If you go on [this demo](http://igtestvm1.cloudapp.net:898/offline/angularschemaform/views/upload-demo.html) open dev tools you will see that the uploader on left does not log anything when a file is selected (because of the error) but the uploader on the write, which is outside the form, logs get triggered.

Any suggestions on how I can make get around this problem?

Thanks.

**Comment by mattcrwi** [comment]
I had the same error but it was because I had not defined the uploader attribute on my input element. This thread was misleading and I hope to save other peoples time. Make sure uploader is defined before trying these other fixes.

**Comment by HowardTA** [comment]
TY mattcrwi ... that was it! ... Yes, this thread was misleading until you steped in. :+1:

**Comment by askucher** [comment]
Have same problem. but attribute is defined

**Comment by ajankowski** [comment]
Thanks @robotnic   Adding $scope.uploader fixed this issue for me.

**Comment by dnamna** [comment]
@dlodeprojuicer hi sorry but how you registered the fileuploader scope in the directive?
