### ISSUE TITLE
Upload not working on IE8/IE9

### ISSUE THREAD

**Issue by felixbillon** [nervgh/angular-file-upload#253]
Hi everybody,

I got a probleme with the uploader module. It works fine on firefox and chrome and IE 10. On IE8/9 the file is correctly send to the server by iframe but the xhr response is undefined... When i track network i could see that response is correctly send to the server, then response body contains json but that could not bind on the response in javascript...

I try the online demo and it got the same error.

Please help :)

**Comment by swanidhi** [comment]
I am facing the same issues mentioned by @mcgraphix . @nervgh I couldnt find any discussion to this problem in the IE Tagged issues. Can't get it to work on IE8 and 9 because of above mentioned reasons. Anything I'm missing on?

**Comment by siriquelle** [comment]
@swanidhi did you ever find a work around for this that didn't involve using a different library?

**Comment by meloseven** [comment]
So,how to solve this problem?I found same issue in newest version.
