### ISSUE TITLE
Are there examples of extension filters or max size filters?

### ISSUE THREAD

**Issue by ludar** [nervgh/angular-file-upload#26]
Would be nice to be able to restrict file extensions ie (png|jpeg|jpg|gif)

Or by max size (1MB) 

with error messages if possible.

**Comment by nottinhill** [comment]
Thanks for the example, but what is the name of the filter? I cannot find it.

**Comment by runderworld** [comment]
@nottinhill There's a newer API; see my updated example here: http://stackoverflow.com/a/28511240/1438576

**Comment by mabumeshref** [comment]
How to filter image with specific dimensions, foe example, the user is not able to upload image width less than 1024

**Comment by suhas2421** [comment]
If I dont want to add same file in uploader.queue how can I do
