### ISSUE TITLE
Planned support for Angular 1.3?

### ISSUE THREAD

**Issue by kureus** [nervgh/angular-file-upload#263]
Angular 1.3 has been in development for a long time now. We've 19 betas and 5 releases candidates to date. Is file upload tested against 1.3, if so can you update the bower deps to represent its supported?Or if not can you create a milestone to target 1.3 support where we can triage issues?

**Comment by papercuter** [comment]
+1

**Comment by nachtwandler** [comment]
+1

**Comment by rriemann** [comment]
:+1:

**Comment by amrfaisal** [comment]
Are you planing to support Angular 1.3 anytime soon?

**Comment by paulbhartzog** [comment]
Why is this closed? Was it fixed?

I am having the same problem as "elfrasco" above, i.e.:

ECONFLICT Unable to find suitable version for angular

thx
