### ISSUE TITLE
How to include upload.php 

### ISSUE THREAD

**Issue by madhav5589** [nervgh/angular-file-upload#264]
What if someone is using AngularJS webapp inside MVC. How to include upload.php in the project ?

**Comment by Marioum** [comment]
@madhav5589 How did you solve this issue please? I am stuck and working with phpslim framework wich made things confuser for me. anyone ould help please?

**Comment by madhav5589** [comment]
@Marioum I replaced the upload.php with the own file and specify the server path where you want to upload the file.
