### ISSUE TITLE
Can not cancel upload onBeforeUploadItem.

### ISSUE THREAD

**Issue by nateinindy** [nervgh/angular-file-upload#265]
I need to check an input field for a value that will be used as part of my rest upload url and cancel the upload if the user did not supply this value.  I execute the item.cancel() method, but it seems to just ignore it. Nonworking code here:

uploader.onBeforeUploadItem = function(item) {
        if($('#myValue').val() == '')
            item.cancel();
 };

**Comment by andreaslarssen** [comment]
Because he's using jQuery? That still don't solve the issue:

```
$scope.uploader.onBeforeUploadItem = function (item) {
                item.cancel();
}
```

...does not work. It still sends the request. Trying other FileItem methods produces same result:

```
$scope.uploader.onBeforeUploadItem = function (item) {
                item.remove();
}
```

...removes file from queue, but still sends the request.

**Comment by andreaslarssen** [comment]
Created new [issue](https://github.com/nervgh/angular-file-upload/issues/425)

**Comment by nervgh** [comment]
https://github.com/nervgh/angular-file-upload/issues/425#
