### ISSUE TITLE
How to have non ascii characters (foreign languages like russian or french) cared for ?

### ISSUE THREAD

**Issue by stephaneeybert** [nervgh/angular-file-upload#267]
Hi,

The upload works fine for english characters, but the non english ones are messed up.

Any one has some experience on this ?

On vim on Linux I can see my uploaded file (the file created on the server) has the exact same content as the picked up one (the file browsed to on the client).

But they appear funky in the GUI after database insertion.

My MySQL table has been created in utf8 as:

drop table if exists address;
create table address (
  id bigint(20) unsigned not null auto_increment,
  version int(10) unsigned not null,
  address1 varchar(255),
  address2 varchar(255),
  zip_code varchar(10),
  city varchar(255),
  state varchar(255),
  country varchar(255),
  postal_box varchar(50),
  primary key (id),
  unique key id (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;

Any clue ?

Cheers,

**Comment by jmjdesenvolvimento** [comment]
how do this:
" I added a file encoding resolver to detect the encoding."
?

**Comment by stephaneeybert** [comment]
Hi, I'm sorry not to be able to answer you. I feel stupid not being able to even see what issue I was having. I looked into my old project and could not see anything like a resolver or encoding code. If I see it in the future I'll come back to you.

**Comment by stephaneeybert** [comment]
I keep looking.. but cannot find it. I also then googled and saw this question http://stackoverflow.com/questions/37585556/how-to-set-the-encoding-of-multipart-resolver-in-a-spring-boot-application Maybe it could solve your issue. I wish I could remember what my issue was...
