### ISSUE TITLE
Upload mpeg files through phone and tablets, no problem on demo site or on desktop.

### ISSUE THREAD

**Issue by numerized** [nervgh/angular-file-upload#280]
Hi Guys.

Thanks for the amazing file-upload-library.

I've got all setup, everything runs smoothly so far. Only when I'm adding a video straight from any phone I've got a FileSize zero and no error reported.

When I upload those files with a desktop browser I've got no problem at all.
The other info I have to give is that I don't have the compression screen before the image is actually submitted like in your demo site when I try it with my phone and the same video.

What do I miss, if you have any clue ?
Thanks so much.

**Comment by nervgh** [comment]
I'm closing this now because of too much time has passed and I think this issue is not relevant more.
Anyway, thank you for your question and good luck =)
