### ISSUE TITLE
Not an issue, but a question of compatibility with curl's --form option

### ISSUE THREAD

**Issue by melnikovkolya** [nervgh/angular-file-upload#284]
I am trying to use `formData` property to replicate the functionality of `--form` option in `curl`, however I cannot get it to work. Namely, I have the following `curl` `jobSettings`option that I want to pass in `angular-file-upload`'s formData (is it the right place to pass it)

```
curl  -H "Content-Type: multipart/form-data" --form "jobSettings=$body" --form "upload=@$file" ${URL}?key=$key
```

Could you please suggest me how I should do it?

**Comment by nervgh** [comment]
>  I want to pass in angular-file-upload's formData (is it the right place to pass it)

You cannot do that way because `angular-file-upload` cannot handle your server requests. It's just a script which works in a browser.
