### ISSUE TITLE
405 method not allowed

### ISSUE THREAD

**Issue by johnwesthoff** [nervgh/angular-file-upload#293]
I've tried to use the upload component but it fires a "method not allowed" after uploading to a /upload directory, created in the webapp dir. I'm using IISExpress, Asp.net MVC and angular. How can i fix this?
![knipsel](https://cloud.githubusercontent.com/assets/7084604/4921221/bcb1f21e-6508-11e4-86fb-4247214102cd.PNG)

**Comment by nervgh** [comment]
@johnwesthoff you need implement your server side :smiley_cat:
