### ISSUE TITLE
File can't be reselected after removing from the queue (Chrome, IE)

### ISSUE THREAD

**Issue by sbagriantsev** [nervgh/angular-file-upload#295]
Hello,

There seems to be an issue with reselecting same files in Chrome and IE browsers.

Steps to reproduce:
1. Go to http://nervgh.github.io/pages/angular-file-upload/examples/simple/
2. Select file with Single select.
3. Remove it from the queue using remove button
4. Try to select the same file once again.

Result: File is not added to the queue.
Expected result: File is added to the queue.
Browsers: Chrome Version 38, IE 11

If to add another file and then try initial file one more time it works, but this is not correct user experience.

Issue is not reproducible in Firefox.

Sorry if this is a duplicate.

Thanks,
Stanislav

**Comment by raoulus** [comment]
I created a pull request for this, https://github.com/nervgh/angular-file-upload/pull/357

**Comment by woaichiji** [comment]
use fileuploader.clearQueue();

**Comment by nervgh** [comment]
https://github.com/nervgh/angular-file-upload/wiki/FAQ#4-no-file-chosen-or-re-add-same-file
