### ISSUE TITLE
Unable to upload multiple images after removing images, IE10

### ISSUE THREAD

**Issue by jonespen** [nervgh/angular-file-upload#298]
Ok, this is a weird one. I could only reproduce this in IE10.

Steps to reproduce:
1. Open [Uploads only images (with canvas preview)](http://nervgh.github.io/pages/angular-file-upload/examples/image-preview/) example using IE10
2. Select multiple images
3. Multiple images added, remove all
4. Select multiple images again
5. Nothing happens.
6. Select one image
7. Image is added
8. Select multiple images
9. Multiple images added. 

Anyone else experienced this before?

**Comment by nervgh** [comment]
This is probably solved --> https://github.com/nervgh/angular-file-upload/issues/298#issuecomment-64046109
