### ISSUE TITLE
Get data from url request

### ISSUE THREAD

**Issue by redreeva** [nervgh/angular-file-upload#301]
Hi! Is it possible to get data that server sends after upload file?

.....
var uploader = $scope.uploader = new FileUploader({
        url: '/ajax/upload.php',
        data: // e.g. here output data
        ......
    });
..... 

Thanks and sorry for my bad English:)

**Comment by nervgh** [comment]
This is solved --> https://github.com/nervgh/angular-file-upload/issues/301#issuecomment-67456838
