### ISSUE TITLE
phantomjs error

### ISSUE THREAD

**Issue by yangweijie** [nervgh/angular-file-upload#304]
when i write an e2e test, first for chrome no problem。 But when i change to phantomjs 。And the same suite 

```
//使上传可见
        var path = require("path");
        var file = path.resolve('./upload/luofei_upload_monit.pdf');
        browser.wait(function(){
            return $('#upload_rd').isPresent();
        },10000);
        browser.executeScript(function(){
            $('#upload_rd').show();
        });

        $('#upload_rd').sendKeys(file);
```

didn't work.how do to debug when i use a headless browser with less information?

**Comment by nervgh** [comment]
I'm sorry, I have no idea how you could debug that.
I'm closing this issue due to relevance.
Good luck =)
