### ISSUE TITLE
Question: Upon upload, I want to do some validation on all files and then return status individually

### ISSUE THREAD

**Issue by bhashamitra** [nervgh/angular-file-upload#309]
Hi,

I want to upload multiple files.
On the server side, I want to do some kind of validation on each file.
Some file will pass the validation and others may fail.
I want to send this back to browser - status of individual file. Notice that upload is successful for all files but the custom validation has failed for some and passed for others.
On browser, under status column (in the simple example), I want to display this pass or fail as success or error.

How can I accomplish this?

Thanks!

**Comment by nervgh** [comment]
I hope that works now. Good luck everyone :smile_cat:
