### ISSUE TITLE
possible to set header option on existing FileUploader()?

### ISSUE THREAD

**Issue by chrxs** [nervgh/angular-file-upload#310]
I've set got a FileUploader like:

``` js
$scope.avatarUploader = new FileUploader({
  url: API_END_POINT + '/user',
  autoUpload: false,
  headers: {}
});
```

I'd like to set the header option just before I tell it to upload:

```
$scope.avatarUploader.uploadItem(0);
```

Is this possible?

Thanks! :smile:

**Comment by nervgh** [comment]
This is solved --> https://github.com/nervgh/angular-file-upload/issues/310#issuecomment-65222583
