### ISSUE TITLE
Custom Headers IE9

### ISSUE THREAD

**Issue by gregbenner** [nervgh/angular-file-upload#311]
I know the documentation says HTML5 browsers but there must be a way to add custom headers to the ajax request. 

I have set Angular's $http to have default headers with "access_token" but either this library is using something different for ajax or it's getting cleared.

IE9 doesn't seem to pick up any custom headers added to FileUploader instance either.

var uploader = $scope.uploader = new FileUploader({
 headers: {
          "access_token" : "notworking"
        }
 });

**Comment by mcarabolante-gradus** [comment]
I am having the same issue, any news ?

**Comment by gregbenner** [comment]
I figured the issue is no support for AJAX file attachments, the plugin uses a hidden iframe to upload.
Might need to pass your access token as a query param in a POST for this.

**Comment by mcarabolante-gradus** [comment]
uhmm, that should work

thanks !

**Comment by gregbenner** [comment]
No worries, death to IE9... took me awhile to figure it out before hope it helps.
