### ISSUE TITLE
ERROR: 413 (Request Entity Too Large)

### ISSUE THREAD

**Issue by funky86** [nervgh/angular-file-upload#313]
Hello guys!

I'm getting error 413 (Request Entity Too Large) when uploading a file larger than 2MB. The same error occurs (see browser's console) when trying to do that with the official demo.

On our production server (Ubuntu Server 14.04.1 LTS) I set in php.ini the following:
upload_max_filesize 10M
post_max_size   10M

The example on w3schools (www.w3schools.com/php/php_file_upload.asp) for file upload works on our server but uploading a file of size > 2MB with nervgh/angular-file-upload unfortunately still doesn't.

What can cause this behaviour?

Thank you in advance,

Tilen

**Comment by Kendysond** [comment]
Hello @funky86 please I use a shared hosting on godaddy, can you kindly help with a clearer solution for this ERROR: 413 (Request Entity Too Large) Thank you!

**Comment by hoangduy1508** [comment]
@nervgh I want to detect it and show message error in client not fix in server
