### ISSUE TITLE
URL Encoding File Name

### ISSUE THREAD

**Issue by desertlion** [nervgh/angular-file-upload#315]
Hi, I'm sorry if I missed something in the doc, but I can't find a way to url_encode my file name which is being uploaded, this caused the image I'm uploading not showing in my app. 

Instead of uploading "some file.png" I want to set the filename to "some%20file.png"

Actually it can be solved by renaming the file from the backend, but I dont have access to the backend, is there a way I can url encode the name of the file which is being uploaded.

**Comment by nervgh** [comment]
I'm not sure but you can overwrte filename using [that](https://github.com/nervgh/angular-file-upload/blob/2.5.0/src/services/FileUploader.js#L472) way. It will work only for FormData uploads.
