### ISSUE TITLE
After a file has been added to the queue and then removed, the same file cannot be added again.

### ISSUE THREAD

**Issue by ventres** [nervgh/angular-file-upload#322]
This has been tested in Chrome and Safari and can be seen in the simple example provided on your site:
http://nervgh.github.io/pages/angular-file-upload/examples/simple/
Simply add an item, remove it, and add it again.

I believe it is necessary to reach back into the input file element that the directive is attached to and remove the item from the selection. That is what is preventing the file from being added again.

**Comment by raoulus** [comment]
I am having the same problem. Please take a look at my pull request (https://github.com/nervgh/angular-file-upload/pull/357), which fixes this issue.

It uses an extra option as @fabiokiatkowski proposed.

**Comment by kunal999** [comment]
+1

**Comment by bmustata** [comment]
+1

**Comment by nervgh** [comment]
https://github.com/nervgh/angular-file-upload/wiki/FAQ#4-no-file-chosen-or-re-add-same-file
