### ISSUE TITLE
ProgressBar is running to the end imeddiatly.

### ISSUE THREAD

**Issue by DvirH** [nervgh/angular-file-upload#325]
For now, When i click on upload it's look like it Finished with a second, But actually it's still upload.
When i debug the code it's look like the event.total on the xhr.upload.progress is at the end.
and there is no content-length header.

any ideas?

**Comment by jeremiahblanch-PropertyMe** [comment]
I too have this problem.  It is not affected by the template markup - I'm reading the values in the console.

I'm not sure how the angular $scope could affect it, but I am interested to see why. 

I have a controller that looks after my upload page , I declare it like this.
       var uploader =  new fileUploader({
            url: '/api/storage/documents?format=json'
        });

then I put console.logs inside the onProgressItem and onProgressAll callbacks: 

                 uploader.onProgressAll = function (val) {
			console.log('progress is', val);
		};

		uploader.onProgressItem = function (item, val) {
			console.log('progress for',item,  val);
		};

Then I upload a 4.5 mB file. The moment I being the upload, it logs this in the console: 


        progress for i {url: "/api/storage/documents?format=json", alias: "file", headers: Object, formData: Array[0], removeAfterUpload: false…} 100

         progress is 100

So, progress = 100 from the beginning. I have tried this a few times, sometimes progress begins at 97.

**Comment by DvirH** [comment]
It solved when I ran it on the server.
The problem was it localhost and it was finish very quick.
