### ISSUE TITLE
select specific image on the upload queue.

### ISSUE THREAD

**Issue by iceblue85** [nervgh/angular-file-upload#334]
i have modified the option of the script 

```
alias: 'file[]',
```

it works but i dont understand for what reason on the php file:

```
 $photo = 'uploads' . DIRECTORY_SEPARATOR . $_FILES[ 'file' ][ 'name' ][0];
 $photo2 = 'uploads' . DIRECTORY_SEPARATOR . $_FILES[ 'file' ][ 'name' ][1];
 $photo3 = 'uploads' . DIRECTORY_SEPARATOR . $_FILES[ 'file' ][ 'name' ][2];
```

only $photo seems to be working (and it return the correct file name of first item), but i don't understand for what reason the others are empty.

**Comment by nervgh** [comment]
FileUploader sends files one by one so your server will be receiving only one item per request.
Good luck =)
