### ISSUE TITLE
Bower angular depencies

### ISSUE THREAD

**Issue by piernik** [nervgh/angular-file-upload#335]
Can't install Your script throungh bower. It has 1.2 ver of angular - I'm using 1.3

**Comment by labs-scnm** [comment]
I tested it with AngularJS 1.3.8 and it seems everything work well.
So, pleaser can you update the Bower dependencies to maybe `"angular": "=>1.2.11 <1.4.0"`?

@piernik you can solve your problem to add the property below to your bower.json file.
```json
"resolutions": {
  "angular": "~1.3.8"
}
```

**Comment by mateatslc** [comment]
Works fine on 1.3.11 for me.
+1 for updating angular version to "~1.3" in bower.json

**Comment by genuinefafa** [comment]
For me too! No problems here!

**Comment by piet-byteorbit** [comment]
Note that there are some open issues about problems on Angular 1.3: #305, #307

**Comment by genuinefafa** [comment]
@piet-byteorbit 
 * #307 is not really a problem, nobody answer the workaround.
 * #305 well... you are right there... :(

**Comment by mateatslc** [comment]
not too helpful for those having issues, but it works fine on Angular v1.4.1 for me. ¯\_(ツ)_/¯

**Comment by nervgh** [comment]
fixed https://github.com/nervgh/angular-file-upload/issues/469
