### ISSUE TITLE
IE9 Image preview not available

### ISSUE THREAD

**Issue by stripathix** [nervgh/angular-file-upload#339]
Hey can you help me with image preview on IE9. I cant get it working using this module. Am i doing something wrong or it is just because it is GREAT IE 9 who f**k developers :-( .

**Comment by nervgh** [comment]
IE 9 not support canvas preview

**Comment by vinogradov** [comment]
Actually IE9 supports canvas. The problem with IE9 preview is that you aren't able to get image URL for the preview.
