### ISSUE TITLE
cannot upload files with size >2MB

### ISSUE THREAD

**Issue by nevoeiro** [nervgh/angular-file-upload#340]
Hi there,

I implemented angular-file-upload on my app and it's working very well with files <2MB of size.
When I try upload  >2MB files the logs said that file transfer was completed but the file doesn't exist in my uploads folder.
Theres any paramenter to control the size limit of each file?

Thanks for help.
C.

**Comment by djmccormick** [comment]
What server is accepting the files? Are you certain you don't have an upload file size limit set through the server?

**Comment by nervgh** [comment]
See your server' settings https://github.com/nervgh/angular-file-upload/issues/118#issuecomment-41774321
