### ISSUE TITLE
Missing status text at headers/status

### ISSUE THREAD

**Issue by San4oPanso** [nervgh/angular-file-upload#344]
Hi. 
Can you add support for statusText, not only statusCode (200, 500 etc..)? xhr.statusText (now you are getting only xhr.status). If you never heard about it-check this out: 
https://developer.mozilla.org/ru/docs/Web/API/XMLHttpRequest 
I need to get error from server and it is received by status code (no response-body for POST request)
Thanks!

**Comment by nervgh** [comment]
You can do it using [that](https://github.com/nervgh/angular-file-upload/blob/2.5.0/src/services/FileUploader.js#L461) property. That is not a legal way but why not? :smile_cat: 
Good luck)
