### ISSUE TITLE
CORS Options Header Corruption

### ISSUE THREAD

**Issue by cpttripzz** [nervgh/angular-file-upload#349]
Using Symfony2 NelmioCORS bundle: https://github.com/nelmio/NelmioCorsBundle
Works perfectly with the angular http service using:  $httpProvider.interceptors.push
and this in the interceptor: config.headers.Authorization = 'Bearer ' + $sessionStorage.user.token

Every request to api requires the Authorization header except the OPTIONS request
Problem is that when the options request gets fired it has the header in a garbled state.

I read here https://github.com/nervgh/angular-file-upload/issues/163 you replied that you could use this:
uploader.bind('beforeupload', function (event, item) {
            console.info('Before upload', item);
        });

however I do not see how. Thanks for the help
![snapshot2](https://cloud.githubusercontent.com/assets/4466445/5887227/4c68b698-a3cc-11e4-8dfc-108685b27cf8.png)

Here is a working exampe with this module: https://github.com/danialfarid/angular-file-upload

![snapshot3](https://cloud.githubusercontent.com/assets/4466445/5887233/bf5f9f5e-a3cc-11e4-9762-320d816d82df.png)
![snapshot4](https://cloud.githubusercontent.com/assets/4466445/5887232/bf5e822c-a3cc-11e4-9d85-ec91afb32392.png)

**Comment by nervgh** [comment]
Hi

> Here is a working exampe with this module: https://github.com/danialfarid/angular-file-upload

You mentioned another module =) That is not related with this project.
