### ISSUE TITLE
upload doesn't put form in dirty state

### ISSUE THREAD

**Issue by awerlang** [nervgh/angular-file-upload#359]
If form is pristine and I upload a file, form's still pristine while one would expect it to become dirty.

I see this directive doesn't depend in any way of ng-model or ng-form, but I believe it would be nice if it could optionally require the parent form and call $setDirty() on uploading.

I have a service handling file uploading and as so I don't have a form reference there. I would need to change both service and controller wherever a use this component.

**Comment by demisx** [comment]
+1

**Comment by snehilmodani** [comment]
+1

**Comment by guyviner** [comment]
+1

**Comment by nervgh** [comment]
This module does not control with validation state of a form. It handles file uploads only.
