### ISSUE TITLE
URL of FileUploader

### ISSUE THREAD

**Issue by ava-oneilk** [nervgh/angular-file-upload#361]
I'm currently trying to use this module with a Yii application.  I am trying to upload a CSV and then eventually json encode and save the contents to an Amazon S3 Bucket.  I'm having trouble trying to figure out how to upload the file.

CONTROLLER:
=========================
    app.controller('UploadController', function (Uploads, $rootScope, $scope, FileUploader, DataSource)      { 
        var uploader = $scope.uploader = new FileUploader({
            url: '/account/upload.php'
        });

    });

VIEW:
=========================
```
<input type="file" nv-file-select uploader="uploader"/><br/>
<ul>
    <li ng-repeat="item in uploader.queue">
        Name: <span ng-bind="item.file.name"></span><br/>
        <button ng-click="item.upload();">upload</button>
    </li>
</ul>
```

===========================

I'm getting a 400 (bad request) error, was wondering if anyone could help me out.

**Comment by nervgh** [comment]
See #602
