### ISSUE TITLE
Upload for files larger than 2-3 MB fails on chrome

### ISSUE THREAD

**Issue by karan-kapoor90** [nervgh/angular-file-upload#362]
Uploading to chrome for files larger than a few MB crashes the window. This works ok on firefox though. Is this a known bug? Is there some workaround? Anybody with the same issue ?

**Comment by sentoro** [comment]
I have the same issue in Opera and Chrome

**Comment by khandah** [comment]
I have Chrome and I am having that problem.
Even if I push some conditions like this:
uploader.filters.push({ name: 'sizeFilter', fn: function(item) {
		   return item.size < 100000000;
		}});
The limit is the limit, which is 2 MB.

**Comment by karan-kapoor90** [comment]
Resolved? Where? Has the fix been propagated to bower or npm? Or is it available here only?

**Comment by khandah** [comment]
Where is the guy who said it is resolved!?? Disapeared ?

**Comment by karan-kapoor90** [comment]
Yup.

**Comment by khandah** [comment]
I am looking for the variable that can fix this but can't find it.

**Comment by karan-kapoor90** [comment]
The uploads weren't working anyways with this. I had to change a statement
in a particular file in his js. But ever since then items are uploading
synchronously. Will share the code here in a bit. Maybe we'll be able to
figure out out together

**Comment by khandah** [comment]
Ok thanks.

**Comment by karan-kapoor90** [comment]
@khandah How do you handle the file uploads on the server?

**Comment by khandah** [comment]
You mean how to copy them and so on ?
I am using both php and java.

**Comment by in8d3v** [comment]
Has this been resolved

**Comment by karan-kapoor90** [comment]
Ya its always works fine for me now. Don't know how you could solve it for
java or php, but while using nodejs, using multer to write the files on the
server worked for me, as opposed to using multer to capture the file
contents in memory, and then streaming it to a fs.createWriteStream
