### ISSUE TITLE
Adding additional parameter to formData

### ISSUE THREAD

**Issue by philecom** [nervgh/angular-file-upload#369]
I have set the plugin and it is working perfectly, however when i try to add additional data to the upload i get error. I came across this code in one of the issue comments, but my problem is where to place the code.
uploader.bind('beforeupload', function (event, item) {
item.formData.push({some: 'data'});
});

I get undefined is not a function when i place it directly in my controller.

I hope you can help me.

**Comment by karan-kapoor90** [comment]
You may bind it as such 

    uploader = new FileUploader({
                url: /api/fileUpload, //upload server route
                method: 'POST', //method
                formData: metadata 
            });

here metadata is of type :

    var metadata = [{'type':'content','attr1':value,'attr2':'dummyValue'}];

This is what worked for me.

**Comment by pcnate** [comment]
I had to bind to the beforeupload event as well. I think the reason you are having issues is that formData does not exist when you try to create it. In @karan-kapoor90's example, he is creating a differently name array called metadata. This works but it doesn't change after the creation of the FileUploader instance. Combining his example with the item.metadata.push() or item.metadata[index] = value will update the information prior to uploading correctly.

**Comment by enghelewa** [comment]
@philecom 

This worked for me :+1: 

```
var uploader = $scope.uploader = new FileUploader({
    url: 'YOUR URL',
    method: 'POST'
});

uploader.onBeforeUploadItem = function (item) {
    var index = $scope.uploader.getIndexOfItem(item);
    item.formData = [{ firstParam: 'Value', secondParam: 'value' }];
};
```

**Comment by bborad** [comment]
Hi

how do you retrieve this formData on server side with files. I am using .net. I am getting all the files from Request.Files but not sure about how to get data sent in uploader.formData. 

Thanks

**Comment by nervgh** [comment]
@bborad , https://github.com/nervgh/angular-file-upload/issues/257#issuecomment-59891082

**Comment by bborad** [comment]
Sorry for the late response, 

I didn't quite find the solution I was looking for from those issues but end up using "uploader.onBeforeUploadItem" to send form data. The only problem with this if I have large amount of data that I want to send with upload, this will send it with every single file I have in my upload list. I wanted to use it somewhere like OnBeforeUploadStart. 

But thanks for your help, at least got it working for now.
