### ISSUE TITLE
change image name dynamically

### ISSUE THREAD

**Issue by pdl761** [nervgh/angular-file-upload#374]
Hi nervgh
Good day to you
I want to change the name of file , but I am trying to do it in angular-js-upload.js and in controllers.js but no where file name if getting changed

using codes like             IN controller.js
console.log(uploader.queue[0].file.name);     should print the original name
uploader.queue[0].file.name = "some_name.jpg/png";
console.log(uploader.queue[0].file.name);      should print the changed name 

but both are printing the same name i.e original name. 

in angular-file-upload.js                       in function  -------------- addToQueue

console.log(item.file.name);     should print the original name
item.file.name = "some_name.jpg/png";
console.log(item.file.name);      should print the changed name 

both again printing same name.

Please help me regarding this.

**Comment by nervgh** [comment]
See an `alias` option https://github.com/nervgh/angular-file-upload/wiki/Module-API
