### ISSUE TITLE
AngularJS is limiting the size of files with no possibility to change it.

### ISSUE THREAD

**Issue by khandah** [nervgh/angular-file-upload#379]
I can`t change the size limit of files to be uploaded.
It is fixed to something lesser that 2 MB and no way to change that.
Filters are limited to images (jpg,npg,gif) as inthe demo. But I can upload anything I want with no restriction. The only restriction is size which is limited to 2 MB.

**Comment by anjum121** [comment]
you can do some modification to set image size like below 
             

         var checkImageSize = function (size) {
          //this can be from your rootScope or config file
         var imgSize = 3;
          var temp;
          if (((temp = imgSize ) === (void 0)||temp === '')||( size / 1024) / 1024 < imgSize) {
            return true
          } else {
            alert("File Size should be smaller than " + imgSize + "MB");
            return false
          }

        }

You can  then change line 402 to something like below 

        FileUploader.prototype._isValidFile = function (file, filters, options) {

          if(checkImageSize(file.size)){
            console.log(file)
            this._failFilterIndex = -1;
            return !filters.length ? true : filters.every(function (filter) {
              this._failFilterIndex++;
              return filter.fn.call(this, file, options);
            }, this);
          }

        return false

        };

**Comment by nervgh** [comment]
@khandah check size of item inside of your filter and return relevant response
