### ISSUE TITLE
Auto Upload After Adding File

### ISSUE THREAD

**Issue by Mr-Anonymous** [nervgh/angular-file-upload#380]
Is it possible to automatically start uploading the file after adding the file to queue instead of manually clicking on the upload or upload all button? I had a look at your sample controller and was wondering if I need to add a function or so for the onAfterAddingFile Callback for it to work like this?
``` 
       uploader.onAfterAddingFile = function(fileItem) {
            console.info('onAfterAddingFile', fileItem);
        };
```
Any suggestion on how I can achieve that please?

**Comment by pauloadaoag** [comment]
Yep you can. Here is how I do it in the controller. 

$scope.uploader = new FileUploader();
$scope.uploader.url = YOUR_URL;

$scope.uploader.onAfterAddingFile = function() {
    $scope.uploader.uploadAll();
};
$scope.uploader.onSuccessItem = function(item, response) {
    //Do whatever is needed here
};

**Comment by Mr-Anonymous** [comment]
Perfect! 
```
$scope.uploader.onAfterAddingFile = function() {
       $scope.uploader.uploadAll();
};
```
That did it for me. Thank you so much for helping @pauloadaoag
:)
