### ISSUE TITLE
Unknown provider: FileUploaderProvider <- FileUploader (Version: 1.1.5)

### ISSUE THREAD

**Issue by UltimateFighter** [nervgh/angular-file-upload#393]
Here is my simple snipplet:
- angular.module('myModule').factory('uploadhandler', function (FileUploader) {});

this ist the error message:
- "Error: [$injector:unpr] Unknown provider: FileUploaderProvider <- FileUploader <- uploadhandler"

this line i added to my bower:
- "angular-file-upload": "~1.1.5",

i use this angular version:
- "1.3.15",

**Comment by pgrodrigues** [comment]
You probably forgot to add `'angularFileUpload'` dependency to your angular module, like this:
`angular.module('myApp',['angularFileUpload'])...` and/or forgot to add the angular-file-upload script to index `<script src='bower_components/angular-file-upload/angular-file-upload.js'></script>`

**Comment by UltimateFighter** [comment]
thank you. I forgot to add 'angularFileUpload' to the app
