### ISSUE TITLE
Add 2 parameters for send to  MVC4 c# controller

### ISSUE THREAD

**Issue by edsquall** [nervgh/angular-file-upload#398]
Hi Alex, i try to use your library for upload image, i programed in mvc4 c#, i received the image in the controller with

    // MVC 4 Controller
    public void Picture(System.Web.HttpPostedFileWrapper file){

    }

but i cant receive other parameters in my controller called 'idReport' because i have to Add the image to History Report and i have to send the id at same time when saved the photo, can you help me, how i can send 2 parameters with you library, other somethings else i used you demo code for send de file to my controller in MVC4 c#.

    HTML Code
        <div ng-controller="AppUploaderController" nv-file-drop="" uploader="uploader" filters="queueLimit, customFilter" >
                                
                                        <label id="lblIdSummary" class="control-label col-sm-2" hidden="hidden" > </label>                                   
                                    
                                        <div>
                                        
                                            <div class="col-sm-6">
                                                <input id="txtLoadImage" class="form-control" type="file" uploader="uploader" nv-file-select="">
                                            </div>
                                        
                                            <div class="col-sm-6">
                                                <h3>Carga de imagen</h3>
                                            
                                                <p>Imágenes: {{ uploader.queue.length }}</p>
                                            
                                                <table class="table">
                                                
                                                    <thead>
                                                        <tr>
                                                            <th width="50%">Nombre:</th>
                                                            <th ng-show="uploader.isHTML5">Tamaño</th>
                                                            <th ng-show="uploader.isHTML5">Progreso</th>
                                                            <th>Estado</th>
                                                           @* <th>Acción</th>*@
                                                        </tr>
                                                    </thead>
                                                
                                                    <tbody>
                                                        <tr ng-repeat="item in uploader.queue">
                                                            <td> <strong>{{ item.file.name }}</strong> </td>
                                                            <td ng-show="uploader.isHTML5" nowrap>{{ item.file.size/1024/1024|number:2 }} MB </td>
                                                            <td ng-show="uploader.isHTML5">
                                                                <div class="progress" style="margin-bottom: 0;">
                                                                    <div class="progress-bar" role="progressbar" ng-style="{ 'width': item.progress + '%' }"></div>
                                                                </div>
                                                            </td>
                                                            <td class="text-center">
                                                                <span ng-show="item.isSuccess"><i class="glyphicon glyphicon-ok"></i></span>
                                                                <span ng-show="item.isCancel"><i class="glyphicon glyphicon-ban-circle"></i></span>
                                                                <span ng-show="item.isError"><i class="glyphicon glyphicon-remove"></i></span>
                                                            </td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                        

                                                <div>
                                        
                                                    <div>
                                                        Progreso:
                                            
                                                        <div class="progress" style="">
                                            
                                                            <div class="progress-bar" role="progressbar" ng-style="{ 'width': uploader.progress + '%' }"></div>
                                                        </div>
                                                    </div>
                                        
                                                    <button type="button" class="btn cssButton btn-s"  style="width:110px" ng-click="uploader.uploadAll()" ng-disabled="!uploader.getNotUploadedItems().length" id="btnModalInternoUpload" >
                                                        <span class="glyphicon glyphicon-upload"></span> Subir
                                                    </button>
                                        
                                                    <button type="button" class="btn cssButton btn-s"  style="width:110px" ng-click="uploader.cancelAll()" ng-disabled="!uploader.isUploading" id="btnModalInternoCancel" >
                                                        <span class="glyphicon glyphicon-ban-circle"></span> Cancelar
                                                    </button>
                                        
                                                    <button type="button" class="btn cssButton btn-s" style="width:110px" ng-click="uploader.clearQueue()" ng-disabled="!uploader.queue.length" id="btnModalInternoClear" >
                                                        <span class="glyphicon glyphicon-trash"></span> Eliminar
                                                    </button>
                                                </div>

                                            </div>

                                        </div>
                                    
                                    
                                        <div class="">
                                            <button type="button" ng-click = "defect.closeModal(); uploader.clearQueue()" class="btn cssButton" data-dismiss="modal">Cerrar</button>
                                            <button type="button" ng-click="defectInternal.saveData(); defect.closeModal(); uploader.clearQueue()" class="btn cssButton" id="btnGuardarDefectoInterno" > Guardar </button>
                                        </div>
                                    
                                    </div>

Javascript Code, I used the demo code 

    app.controller('AppUploaderController', ['$scope', 'FileUploader', function ($scope, FileUploader) {

        var uploader = $scope.uploader = new FileUploader({
            url: '/BitacoraMPM/Picture'
        });

        // FILTERS
        uploader.filters.push({
            name: 'customFilter',
            fn: function (item /*{File|FileLikeObject}*/, options) {
                return this.queue.length < 10;
            }
        });

        // CALLBACKS
        uploader.onWhenAddingFileFailed = function (item /*{File|FileLikeObject}*/, filter, options) {
            console.info('onWhenAddingFileFailed', item, filter, options);
        };

        uploader.onAfterAddingFile = function (fileItem) {
            console.info('onAfterAddingFile', fileItem);
            var i = 1;
        };

        uploader.onAfterAddingAll = function (addedFileItems) {
            console.info('onAfterAddingAll', addedFileItems);
            var i = 1;
        };

        uploader.onBeforeUploadItem = function (item) {
            console.info('onBeforeUploadItem', item);
        };

        uploader.onProgressItem = function (fileItem, progress) {
            console.info('onProgressItem', fileItem, progress);
        };

        uploader.onProgressAll = function (progress) {
            console.info('onProgressAll', progress);
        };

        uploader.onSuccessItem = function (fileItem, response, status, headers) {
            console.info('onSuccessItem', fileItem, response, status, headers);
            var i = 1;
        };

        uploader.onErrorItem = function (fileItem, response, status, headers) {
            console.info('onErrorItem', fileItem, response, status, headers);
        };

        uploader.onCancelItem = function (fileItem, response, status, headers) {
            console.info('onCancelItem', fileItem, response, status, headers);
        };

        uploader.onCompleteItem = function (fileItem, response, status, headers) {
            console.info('onCompleteItem', fileItem, response, status, headers);
            var i = 1;

        };

        uploader.onCompleteAll = function () {
            console.info('onCompleteAll');
            var i = 1;
        };

        console.info('uploader', uploader);

    } ]);

**Comment by siulung4073** [comment]
To send additional data with your file, you should use the formData property of the FileItem:
ej:
```javascript
fileItem.formData.push({ id: someId });
```
in ASP.Net MVC controller:
```
// MVC 4 Controller
public void Picture(System.Web.HttpPostedFileWrapper file, Guid id){

}
```
Choose the data type that you like, I used Guid. Remember that the name of the parameter should be the same as the one on the formdata

**Comment by jcsena** [comment]
how use this in nodejs... 
i am add new data in formaData but the ```req.body``` is empty 

```JavaScript
    uploader.onBeforeUploadItem = function(item) {  
                item.formData.push({test:'test'});    
  };
```
Backend

```JavaScript
console.log(req.body)
//{} empty object
```

**Comment by nervgh** [comment]
This issue is the server' issue
