### ISSUE TITLE
CORS: How to upload file to a different server using XMLHttpRequest object 

### ISSUE THREAD

**Issue by parv-gupta** [nervgh/angular-file-upload#411]
Hi !
I'm able to send properties of uploaded file to my server (NodeJS) using the given code

```
//sending uploaded file to myServer and then piping it to upload server
 uploader = new FileUploader({
                url: '/myserver/upload',
                method: 'POST',
                formData: metadata
            }); 
```
all content as required is received in req.files, req.headers, req.body on myserver
Now I piped it to a different server (upload server) using http request. But it requires a lot of time to upload video files (size > 200 MB).
I don't know how to send the file directly to the upload server. I tried to use this code to send properties of uploaded file to upload server directly:
````
//sending uploaded file directly to upload server
uploader = new FileUploader({
                url: 'http://www.myUploadServer.com/upload',
                method: 'POST',
                formData: metadata
            }); 
````
my upload server received an OPTIONS request but no content was found in request files and request body, although the request headers contained : 
````
{ host: 'www.myUploadServer.com',
  'access-control-request-method': 'POST',
  origin: 'http://vesmed-parvgupta.c9.io',
  'user-agent': 'Mozilla/x.x (Windows NT x.x; WOW64) AppleWebKit/xxx.xx (KHTML, like Gecko) Chrome/xx.x.xxxx.xxx Safari/xxx.xx',
  'access-control-request-headers': '0, content-type',
  accept: '*/*',
  referer: 'www.myServer.com',
  'accept-encoding': 'gzip, deflate, sdch',
  'accept-language': 'en-US,en;q=0.8',
  'x-forwarded-for': 'xxx.xx.xx.xx',
  connection: 'keep-alive',
  'transfer-encoding': 'chunked' }
```` 
So, if you have any idea to how can i send cross server request, help me ;) 
Thanks !!

**Comment by jeyathilak** [comment]
I have the same issue when I use a different server url. It is received as OPTIONS request. Have you solved it by sending a different header? Please let me know if you have any other solution for this problem?

**Comment by josencv** [comment]
The uploader works fine with CORS (they are handled by the browser directly). You have to check if your server can handle CORS: it should be able to respond to OPTIONS requests and should send an 'Access-Control-Allow-Origin' with your domain as a value.

An example of server CORS handling in nodejs / express server:

```javascript
function allowCrossDomain(req, res, next) {
  res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
  res.header('Access-Control-Allow-Headers', 'Content-Type, Authorization, Content-Length, X-Requested-With');

  // Allows only request from http://mydomain.com
  res.header('Access-Control-Allow-Origin', http://mydomain.com);

  // intercept OPTIONS method
  if ('OPTIONS' === req.method) {
    res.status(200).end();  // For OPTIONS requests, a 200 response is sent immediately
  } else {
    next();  // Continues normal workflow
  }
}
```

If you are the owner of the media server you should be able to do something like this. If you are using some external service, it will most likely support CORS.

You can read a complete explanation o CORS requests [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS).

Hope it helps

**Comment by jeyathilak** [comment]
Hi Jose,

Thank you for the server side solution. My Java developers made that change and it worked!!

Thank you so much!!
David

**Comment by josencv** [comment]
No problem!

I'm closing this as "not an issue".
