### ISSUE TITLE
Load a local json file into app $scope?

### ISSUE THREAD

**Issue by mikegoodstadt** [nervgh/angular-file-upload#412]
Hi!
I currently use FileReader to load user local JSON files into the app $scope.
However I would prefer to use a actively-maintained popular module with good functionality eg. angular-file-upload :)
It is possible to achieve the same local-to-local with angular-file-upload?
ie. not upload to a server but just pass the data to $scope or localStorage
Maybe I am just missing the obvious but I am having a fuzzy-brain day and so would appreciate some guidance...
Many thanks, Mike

**Comment by larvanitis** [comment]
I would say this is out of the scope (no pan intended) of this module.

You might want have a look at `FileUploader.onAfterAddingFile` `FileUploader.onWhenAddingFileFailed`.

[see docs](https://github.com/nervgh/angular-file-upload/wiki/Module-API)

_PS I am not affiliated with the project._

**Comment by mikegoodstadt** [comment]
Thanks! I will take a look...
