### ISSUE TITLE
FileUploader returns a response of a full HTML page

### ISSUE THREAD

**Issue by rougin** [nervgh/angular-file-upload#414]
While i'm trying to implement your library based on the given samples, ```uploader.onSuccessItem``` returns a ```status``` of ```200``` but instead of a JSON format in ```response```, it returns a full HTML page. The HTML page contains the current page that I'm working on. Where do you think is my mistake here? Thanks in advance! Here are the following snippets:

**ImportDocument.js** - the name of its controller for this file is ```importDocumentController```

```javascript
var uploader = $scope.uploader = new FileUploader({
    url: 'ImportGLAccount.aspx/Upload'
});

uploader.onSuccessItem = function(fileItem, response, status, headers) {
    console.info('onSuccessItem', fileItem, response, status, headers);
};
```

**ImportDocument.aspx**

```c#
[WebMethod]
public static string Upload()
{
    var responseData = new ResponseData();

    return JsonConvert.SerializeObject(responseData);
}
```

```ResponseData``` is a class that I'm using for passing links or returning data from the server-side to the client side.

**Response Headers**

```
HTTP/1.1 200 OK
Cache-Control: private
Content-Type: text/html; charset=utf-8
Content-Encoding: gzip
Vary: Accept-Encoding
Server: Microsoft-IIS/8.0
X-AspNet-Version: 4.0.30319
X-SourceFiles: =?UTF-8?B?QzpcVXNlcnNcRGV2ZWxvcGVyXERlc2t0b3BcRXhlcml1c1xtZm9cbWZvLXdlYlxWaWV3c1xNYXN0ZXJEYXRhXEltcG9ydEdMQWNjb3VudC5hc3B4XFVwbG9hZA==?=
X-Powered-By: ASP.NET
Date: Tue, 12 May 2015 05:54:05 GMT
Content-Length: 12676
```

**Comment by nervgh** [comment]
> FileUploader returns a response of a full HTML page

FileUploader can not return anything because it is uploader. Check out your server side =)

**Comment by rougin** [comment]
Thanks! I solved this using the following:

```
if (HttpContext.Current.Request.HttpMethod == "POST")
{
    var uploadedFile = new UploadedFile(Request.Files["file"]);

    Response.Clear();
    Response.ClearHeaders();
    Response.AddHeader("Content-Type", "application/json");
    Response.Write(SavePostedFile(uploadedFile));
    Response.Flush();
    Response.End();
}
```

It should be loaded in ```Page_Load``` method.
