### ISSUE TITLE
Add onBeforeFileAdded callback?

### ISSUE THREAD

**Issue by whafrog** [nervgh/angular-file-upload#416]
I would think this would be generally useful, but for my specific case:

I need to be able to put input controls into a grid, so that a user can upload single files tied to specific types (model data) behind the scenes.  If the user selects a file, changes their mind, and selects a second file, both files are added to the queue.  I need to be able to update the queue to remove any previous selections associated with that model data.

I can do this with a filter, but it doesn't seem the right role for a filter.
I can do this using onAfterAddingFile, but the logic is more convoluted since I need to count items associated with model data, and make assumptions about queue order.

**Comment by ernie58** [comment]
+1

**Comment by nervgh** [comment]
> I need to be able to update the queue to remove any previous selections associated with that model data.

See [API](https://github.com/nervgh/angular-file-upload/wiki/Module-API#methods)
- `uploader#removeFromQueue()`
- `uploader#clearQueue()`
- `item.remove()`

**Comment by ernie58** [comment]
The issue was not about the functionality for managing the queue, it was about when you could do this in the flow. Now it has to be done in the filter, which feels hacky

**Comment by nervgh** [comment]
> it was about when you could do this in the flow

Then you should explain what you mean. Also you can search `async filters` issue.

**Comment by ernie58** [comment]
It would be nice to have a callback executed when a user is attempting to add a file, e.g. onBeforeFileAdded. I only want one item in the queue, so now I have to do this in a filter function, which doesn't feel like the right place:

    while(uploader.queue.length > 1){
        uploader.removeFromQueue(0);
    }

The problem is not that it's much code, or it doesn't work, but it is not logic to put it in a filter function.
When there would be a callback onBeforeFileAdded, I could simply do `uploader.clearQueue()`

Does this make sense ?

**Comment by nervgh** [comment]
See [queueLimit](https://github.com/nervgh/angular-file-upload/wiki/Module-API#properties)

**Comment by ernie58** [comment]
In my case I want the last added file. With queueLimit, one cannot add
another file, without removing this one.
I want to make the steps the user has to take as minimal as possible.

I don't see it as a bug, just an extra feature that could be useful in some
cases

2015-06-24 10:21 GMT+02:00 Alex <notifications@github.com>:

> See queueLimit
> <https://github.com/nervgh/angular-file-upload/wiki/Module-API#properties>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nervgh/angular-file-upload/issues/416#issuecomment-114779927>
> .
>



-- 
Met vriendelijke groeten,

Bert Casier

*Ernie webdesign*
Sint-Jansstraat 30 - 8870 Izegem

G: 0473 284 777
E: bert@ernie.be
W: http://www.ernie.be

**Comment by nervgh** [comment]
> I don't see it as a bug, just an extra feature that could be useful in some

Thanks. I understood you :+1:

**Comment by whafrog** [comment]
I did end up implementing a solution using onAfterAddingFile, because technically, yes, all the API calls are available.  But having an onBeforeAddingFile method would be more elegant, and simpler.

The main issue is that by the time onAfterAddingFile is triggered, all the behind-the-scenes code has been run...the file is in the queue and unnecessary data associations are made, data associations that might not be unravelled correctly.  It would seem prudent to be able to run maintenance code before a file is actually added to the queue, without the danger of messing up data associations that might be critical.

**Comment by ernie58** [comment]
Hello,

Just look at that new stuff, I was surprised so much, you have to take a look here <http://trenafrosho.juicecleanserecipes.com/lnqbgldx>

Good wishes, Bert Casier

**Comment by ernie58** [comment]
Hi,

I know you're gonna be surprised by that news, just take a look <http://ltydeprylty.fixedannuities101.com/lngwsik>

My best to you, Bert Casier
