### ISSUE TITLE
Upload via REST and NG-Resource

### ISSUE THREAD

**Issue by krusk** [nervgh/angular-file-upload#421]
Is there an option to use ng-resource for the destination of files over REST? I need to include headers and the destination where the files are going. I saw a few of the other $http examples in the issues section, but I don't see where the URL and headers are set.

**Comment by aosi87** [comment]
There are some options you can use when declare the upload variable, you can read https://github.com/nervgh/angular-file-upload/wiki/Module-API and check for Properties, the url is where your Angular Service should be or if you prefer the REST resource, then you will find the headers option. Try to use google before create new issues. cheers.

**Comment by krusk** [comment]
Thank you. The insight on the URL is what I needed
