### ISSUE TITLE
does nv-file-select have to be on an input element?

### ISSUE THREAD

**Issue by firecentaur** [nervgh/angular-file-upload#423]
Hi there,

I want the file upload dialog to appear when a user presses a button rather than the input field.
Is there any way I can do this?

**Comment by Gulivertx** [comment]
No you cannot but I use a workaround by using a small jquery script. Idea is to put your input with the style hydden and a button that run this input.
it will something like:

The input:
```html
<input style="display:none;" id="fileDialog1" type="file" accept=".pdf" nv-file-select uploader="uploader1"/>
```

The button:
```html
<button type="button" class="btn btn-default btn-sm navbar-btn" id="dwg1">Open</button>
```

The jquery script
```javascript
    $('#dwg1').click(function(event) {
       $('#fileDialog1').click();
    });
```

**Comment by aosi87** [comment]
Or use the angular way:

```
angular.element('#myselector').trigger('click');
```

Not so hard =D. cheers.

**Comment by rolandocc** [comment]
By using material you can use a nice button like this:

```
 <md-button class="md-raised md-primary"
    ng-click="showFileSelection()">
    <span class="fa fa-picture-o"></span>
</md-button>
```

![image](https://cloud.githubusercontent.com/assets/1318512/8635667/8bb41d48-27ec-11e5-8ad4-18fd8c60ce26.png)

**Comment by lpsBetty** [comment]
I hid the input-file select and made an own simple directive for that!

````
/**
 * Dropzone directive to open file-select on click.
 * angular-file-upload cannot do that out of the box.
 */
angular.module('app').directive('lhDropzone', function ($timeout) {
  return {
    restrict: 'A',
    link: function(scope, element) {
      element.click(function() {
        $timeout(function () {
          element.find('input[type="file"]').click();
        });
      });
    }
  };
});

**Comment by mrpmorris** [comment]
Don't use javascript, you can just do this

            <label>
                <input type="file" multiple style="display: none;" />
                <span class="btn btn-default btn-primary">
                    Find files
                </span>
            </label>

**Comment by lpsBetty** [comment]
I should make a label around a whole div? seems not right..

**Comment by lpsBetty** [comment]
in my case I would like to have the whole dropzone clickable - label is quite a good idea if you have just a text link - but what do you do when you have a div with paragraphs, etc.?

**Comment by mrpmorris** [comment]
No, you style your button as I showed (the span using BootStrap classes in
my example) and wrap that + the hidden <input type="file"/> inside a <label>

**Comment by lpsBetty** [comment]
Ok so I changed my DIV into this

````
<label class="dropzone" for="file" nv-file-drop nv-file-over uploader="uploader" over-class="in">
  <i class="fa fa-file-text-o"></i>
  <a>Upload file</a>
  <p class="small text-muted">info text</p>
  <input nv-file-select uploader="uploader" id="file" type="file" multiple class="hidden-btn" />
</label>
