### ISSUE TITLE
What am I doing wrong ?$apply already in progress

### ISSUE THREAD

**Issue by vautrinr** [nervgh/angular-file-upload#431]
Hello;
I think it is a very useful plugin. However I have tried to hide this ugly file input, and I am not able to do so.

my directive image-upload, called inside a ng-repeat, call the following function : 
scope.clickUpload = function () {
  $("#" + scope.imgId).trigger("click");
};
The file input click is triggerred, but I got the message error below : 

Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.3.15/$rootScope/inprog?p0=%24apply
    at REGEX_STRING_REGEXP (angular.min.js:63)
    at beginPhase (angular.min.js:14820)
....

What am I doing wrong please ?

**Comment by luozhihua** [comment]
+1

**Comment by vautrinr** [comment]
I solved this by calling the click function in a $timeout(function(){},0); ;)
