### ISSUE TITLE
Base64 Encoding

### ISSUE THREAD

**Issue by krusk** [nervgh/angular-file-upload#433]
Hi all,

I am attempting to use this directive to upload images into SharePoint, but require it to be in base64 encoding. Does this directive support that, and if so, how is this achieved?

Thanks,

K.

**Comment by bradrich** [comment]
Hello @krusk, I am not the person who wrote this component, but here is how I handled the same exact thing when trying to use this for adding attachments and images to Mandrill emails:

```javascript
// Loop through uploads
angular.forEach($scope.form.fileUpload.uploader.queue, function(upload){

	// Set up attachment files
	var attachment = {};
	attachment.type = upload._file.type;
	attachment.name = upload._file.name.substring(0, upload._file.name.indexOf('.'));

	// Base64 encode attachment
	var reader = new FileReader();
	reader.readAsDataURL(upload._file);
	reader.onload = function(event){

		// Build content
		attachment.content = event.target.result.substring(event.target.result.indexOf(',') + 1, event.target.result.length);

		// Push attachment
		$scope.form.model.attachments.push(attachment);

	};

});
```
Its all in the FileReader() call.  You just handle adding your attachments within the onload function call and you are good to go.

**Comment by bradrich** [comment]
@krusk, forgive me! Make the attachment.name be this:

```javascript
attachment.name = upload._file.name;
```

**Comment by krusk** [comment]
Thanks Brad. I am not using attachments, but this is helpful!

**Comment by sarae4d** [comment]
@bradrich 
Hi,
i see your comment in up.
i have onAfterAddingFile function,
 uploader.onAfterAddingFile = function (fileItem) {
        };
how can i converting 'fileItem' to base64 string in onAfterAddingFile function???

Thank's!!!

**Comment by bradrich** [comment]
@sarae4d, I am guessing that your object from the uploader has the same properties as the object that I mentioned in the example above. If so, you need to bring in the FileReader() call. It has the capability to accomplish what you are attempting to do.

If your upload object has the _file property, then do the following:

```
var reader = new FileReader();
reader.readDataAsUrl(upload._file);
reader.onload = function (event) {
    var base64 = event.target.result.substring(event.target.result.indexOf(',') + 1, event.target.result.length);
    return base64;
};
```

Let me know if I was too late in responding, or if you have any further issues!

**Comment by dnamna** [comment]
@bradrich ,hey i added the following but still the uploaded images are corrupted

```
 uploader.onAfterAddingFile = function (fileItem) {
                console.info('onAfterAddingFile', fileItem);

            

                    var reader = new FileReader();
                    reader.readAsDataURL(fileItem._file);
                    reader.onload = function (event) {
                        var base64 = event.target.result.substring(event.target.result.indexOf(',') + 1, event.target.result.length);
                        return base64;
                    };


            }; 
```

**Comment by bradrich** [comment]
@dnamna I don't have a lot to go on in order to help you. The information that I have shared here is how I was able to make it work.
