### ISSUE TITLE
Please register with NPM & change package name

### ISSUE THREAD

**Issue by sscovil** [nervgh/angular-file-upload#435]
First, thank you for the great work. This thing is easy to implement and the docs & examples are spot on.

I'm not sure if you are aware, but as far as I can tell this repo is not registered with NPM and, in fact, another repo is registered with the same name: https://www.npmjs.com/package/angular-file-upload

The problem is, I (and many others, I'm sure) am using NPM and Browserify, without Bower, for dependency management and when I try to include this package, I instead get a different file upload module found here: https://github.com/danialfarid/angular-file-upload

The whole thing was very confusing at first, and seems a bit sketchy since the repo above is also registered with NPM (by the author) under a different name: https://www.npmjs.com/package/ng-file-upload

Anyway, if you could sort that out it would be amazing...and shouldn't take more than a few minutes, as your `package.json` file looks to be in order aside from the duplicate package name.

Thanks in advance, and let me know if I can be of any assistance!

**Comment by mateatslc** [comment]
Agreed, would be great to have this up on npm!

**Comment by jonespen** [comment]
With the recent es6 support added to this module, it should really be added to npm as well :+1:

**Comment by siulung4073** [comment]
+1

**Comment by nervgh** [comment]
Thanks, @sscovil.

I wrote email to @pitbeast (https://www.npmjs.com/package/angular-file-upload):

> Good day!
>
> Please, let me register my module in npm under the name "angular-file-upload".
> See https://github.com/nervgh/angular-file-upload/issues/435
> 
> Your module is available [here](https://www.npmjs.com/package/ng-file-upload).
> 
> Thanks.

**Comment by nervgh** [comment]
We say special thanks @pitbeast for _angular-file-upload_  npm name :+1:
