### ISSUE TITLE
Volume Externally Altered

### ISSUE THREAD

**Issue by darrylkuhn** [nervgh/angular-file-upload#440]
Hi,

So we implemented a "retry" function which calls `fileItem.upload();` under the hood. Our clever QA team tested the "retry" functionality by uploading from a USB stick and removing drive mid-way through upload, then re-inserting the USB drive and invoking the `fileItem.upload();` method once again. The problem is that this time around the value of fileItem._file.size is an exception (not a number) with the description:

* The volume for a file has been externally altered so that the opened file is no longer valid.

At which point the uploader instance seems to stop executing subsequent calls (at least in IE11). Anybody dealt with this kind of issue before? Is removing/reinserting the drive recoverable?

**Comment by nervgh** [comment]
Sorry, I don't dealt with this problem.

**Comment by darrylkuhn** [comment]
No worries - I can code a fix for it (to at least catch the error and I'll submit a pull request

**Comment by nervgh** [comment]
It will be good :+1:

**Comment by darrylkuhn** [comment]
Created pull request [443](https://github.com/nervgh/angular-file-upload/pull/443)
