### ISSUE TITLE
Append options={Object} to fromData

### ISSUE THREAD

**Issue by beniaminorossini** [nervgh/angular-file-upload#445]
As subject, i can't understand if i can put options in "options={Object}" inside formData.
I have to create multiple nv-file-over inside a ng-repeat ad i have to post some variables data desumed in ng-repeat (eg. item.id) alongside files.
Autoupload is active.
After 2h of work i cant' understand if it is possible and how can i accomplish that.

Thx

```html
 <div class="panel panel-default" nv-file-over="" uploader="uploader"
                     options="{id: user.id,bundle:paypacket_bundle.id}">
```

```javascript
 $scope.uploader = new FileUploader({
            autoUpload: true,
            url: '/paypackets',
            formData: [{user_id: xxxxx, paypacket_bundle_id: xxxx }],
            headers : {
                'X-CSRF-TOKEN': document.querySelector('meta[name="_token"]').getAttribute('content')
            },
        });
```

**Comment by aosi87** [comment]
The way to "push" attributes to formData is to use callbacks (onBeforeUploadItem, onSuccessItem etc) and then inside make some pushes( item.formData.push({id:myID}); ) and so on, btw this will be inside the body of the request, Cheers.

PS.- You can also declare diferent metadada (item.formData = metadada = {item:1, item:2};)

**Comment by jcsena** [comment]
I have the same problem, i using node in the backend aplications and not read  the aditional data in  formData, if read req.body is empty 

```JavaScript
    uploader.onBeforeUploadItem = function(item) {
                item.formData.push({test:'testdata'});
        };
```

and when read the body in nodejs .. is empty

```JavaScript
console.log(req.body)
//{}
```

**Comment by keithl8041** [comment]
Also it's not clear how 'options' is even supposed to work. I have some code like:

`<input type="file" nv-file-select uploader="uploader" options="{ id: 'test' }"  class="form-control" />`

and nowhere can I find an object like `{ id: 'test'}` attached to the file or uploader.  Any hints?

**Comment by bescione** [comment]
I'm trying to do the same thing, but in my case I have to push a variable instead of a fixed value:
`uploader.onBeforeUploadItem = function(item) {
                item.formData.push({test: myVar});
        };`
Where myVar is a variable, set in a ng-model space. The variable always has as result 'undefined'. Anyone can tell me how to proceed?

**Comment by nervgh** [comment]
See https://github.com/nervgh/angular-file-upload/wiki/FAQ#2-how-to-update-fileitem-options-before-uploading
