### ISSUE TITLE
Change content-type for file upload

### ISSUE THREAD

**Issue by vipul-jain** [nervgh/angular-file-upload#447]
![content-type](https://cloud.githubusercontent.com/assets/376500/8371621/afe4dcf8-1bf7-11e5-947f-d5c08879e536.png)

see selected path of image,
When I upload ".odt" file then default Content-type set "application/octet-stream".
I want to change it and set own Content-Type like "application/application/vnd.oasis.opendocument.text".

Is it possible?
if yes. How to set own Content-Type?

**Comment by jammingintexas** [comment]
+1

**Comment by theo4u** [comment]
#766
