### ISSUE TITLE
Retrieve file data as binary data

### ISSUE THREAD

**Issue by jamason** [nervgh/angular-file-upload#449]
uploader.onAfterAddingFile = function (fileItem) {
	console.info('bbbbbbbb ' + fileItem._file.name);
	var reader = new FileReader();
    reader.readAsText(fileItem._file.slice(0, 40 * 1024), "UTF-8");
	console.info('ccccc ' + reader.result);
};

can retrieve file name but reader.result is null.
Need binary data so that file can be saved to SharePoint library

**Comment by nervgh** [comment]
See the [ngThumb](https://github.com/nervgh/angular-file-upload/blob/v2.2.0/examples/image-preview/directives.js) directive
