### ISSUE TITLE
Module 'angularFileUpload' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify

### ISSUE THREAD

**Issue by laohuGitHub** [nervgh/angular-file-upload#451]
This line of code is not executed
var module = angular.module('angularFileUpload', []);

main.js

require.config({
    paths: {
        angular      : 'angular',
        angularRoute : 'angular-route',
        lodash       : 'lodash',
        restangular  : 'restangular',
        bootstrap    : 'ui-bootstrap-tpls',
        modal        : 'modal',
        datepicker   : 'datepicker',
        upload       : 'angular-file-upload'
    },
    shim: {
        'angular'     : {'exports' : 'angular'},
        'angularRoute': ['angular'],
        'restangular' : ['angular', 'lodash'],
        'bootstrap'   : ['angular'],
        'modal'       : ['angular'],
        'datepicker'  : ['angular'],
        'upload'      : ['angular']
    },
    priority: [
        "angular"
    ]
});
app.js

define([
    'angular',
    'angularRoute',
    'filters',
    'services',
    'directives',
    'restangular',
    'upload',
    'bootstrap',
    'datepicker',
    'modal',
    'controllers'
    ], function (angular, filters, services, directives, restangular, upload, bootstrap, datepicker ,modal , controllers) {
        return angular.module('admin', [
                'ngRoute',
                'restangular',
                'admin.filters',
                'admin.services',
                'admin.directives',
                'admin.controllers',
                'ui.bootstrap'
            ]);
});

**Comment by laohuGitHub** [comment]
"Error: "Uploader" must be an instance of FileUploader
.link@http://10.0.3.110:9086/admin-html/app/bower_components/angular-file-upload-master/angular-file-upload.js:1273:1
nodeLinkFn@http://10.0.3.110:9086/admin-html/app/bower_components/angular/angular.js:6752:13
compositeLinkFn@http://10.0.3.110:9086/admin-html/app/bower_components/angular/angular.js:6146:13
compositeLinkFn@http://10.0.3.110:9086/admin-html/app/bower_components/angular/angular.js:6149:13
compositeLinkFn@http://10.0.3.110:9086/admin-html/app/bower_components/angular/angular.js:6149:13
publicLinkFn@http://10.0.3.110:9086/admin-html/app/bower_components/angular/angular.js:6042:30
ngViewFillContentFactory/<.link@http://10.0.3.110:9086/admin-html/app/bower_components/angular-route/angular-route.js:915:7
nodeLinkFn@http://10.0.3.110:9086/admin-html/app/bower_components/angular/angular.js:6752:13
compositeLinkFn@http://10.0.3.110:9086/admin-html/app/bower_components/angular/angular.js:6146:13
publicLinkFn@http://10.0.3.110:9086/admin-html/app/bower_components/angular/angular.js:6042:30
createBoundTranscludeFn/boundTranscludeFn@http://10.0.3.110:9086/admin-html/app/bower_components/angular/angular.js:6166:21
controllersBoundTransclude@http://10.0.3.110:9086/admin-html/app/bower_components/angular/angular.js:6773:18
update@http://10.0.3.110:9086/admin-html/app/bower_components/angular-route/angular-route.js:865:25
$RootScopeProvider/this.$get</Scope.prototype.$broadcast@http://10.0.3.110:9086/admin-html/app/bower_components/angular/angular.js:13093:15
updateRoute/<@http://10.0.3.110:9086/admin-html/app/bower_components/angular-route/angular-route.js:547:15
qFactory/defer/deferred.promise.then/wrappedCallback@http://10.0.3.110:9086/admin-html/app/bower_components/angular/angular.js:11682:31
qFactory/defer/deferred.promise.then/wrappedCallback@http://10.0.3.110:9086/admin-html/app/bower_components/angular/angular.js:11682:31
qFactory/ref/<.then/<@http://10.0.3.110:9086/admin-html/app/bower_components/angular/angular.js:11768:26
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://10.0.3.110:9086/admin-html/app/bower_components/angular/angular.js:12811:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://10.0.3.110:9086/admin-html/app/bower_components/angular/angular.js:12623:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://10.0.3.110:9086/admin-html/app/bower_components/angular/angular.js:12915:13
done@http://10.0.3.110:9086/admin-html/app/bower_components/angular/angular.js:8450:34
completeRequest@http://10.0.3.110:9086/admin-html/app/bower_components/angular/angular.js:8664:7
createHttpBackend/</xhr.onreadystatechange@http://10.0.3.110:9086/admin-html/app/bower_components/angular/angular.js:8603:1
" "<input nv-file-select="" uploader="uploader" type="file">"

**Comment by spencerwi** [comment]
In our app, we ran into this problem today due to the `angular-file-upload.min.js` file not being present in the root of the directory bower creates for this package (`angular-file-upload/`).

Tossing `/dist/` in to reflect the new directory structure fixed the issue.

**Comment by PierrickP** [comment]
saaaaaame here :) i fix my package.json to the latest functional: **1.1.5**

**Comment by spencerwi** [comment]
@PierrickP the newest version also seems functional as well -- it's just directory structure that changed, so only your `<script src="...."></script>` tag should need to change.

**Comment by PierrickP** [comment]
@spencerwi Yes ! i confirme, latest version (1.2.0) working. I just changed path for ``angular-file-upload/dist/angular-file-upload.min.js``
Thanks

**Comment by runderworld** [comment]
@laohuGitHub @spencerwi @PierrickP:

see https://github.com/nervgh/angular-file-upload/commit/c7bd77f9d1dc5a39ccc98b4495649d0e5af04b0c for more info.

**Comment by pulkitsinghal** [comment]
Has v1.2.0 been pulled from NPM?
```
+ node_modules/bower/bin/bower install
bower angular-file-upload#1.2.0       not-cached git://github.com/nervgh/angular-file-upload.git#1.2.0
bower angular-file-upload#1.2.0          resolve git://github.com/nervgh/angular-file-upload.git#1.2.0
bower angular-file-upload#1.2.0     ENORESTARGET No tag found that was able to satisfy 1.2.0

Additional error details:
Available versions: 2.1.1, 2.1.0, 2.0.1, 2.0.0, 1.1.6, 1.1.5, 1.1.4, 1.1.1, 1.1.0, 1.0.3, 1.0.2, 1.0.1, 0.5.7, 0.5.6, 0.5.5, 0.5.4, 0.4.1, 0.4.0, 0.3.1, 0.2.7, 0.2.5, 0.2.4, 0.2.1
```

**Comment by nervgh** [comment]
@pulkitsinghal ,

>> Hello,
>>  
>> Until couple of days, I used angular-file-upload 1.1.8 with bower.
>> It seems that the version 1.1.8 is not yet  available.
>> 
>> What can I do to be sure to don't have regression ? 
>>
>> Thanks in advance for your answer.
>> 
>> Regards,
>> Guillaume

> Good day
> Yes. I changed "tags" in favor of semver.
>
> 1.1.7 -> 2.0.0
> 1.1.8 -> 2.0.1
> 1.2.0 -> 2.1.0
> 
> I apologize for the inconvenience.

---

About NPM https://github.com/nervgh/angular-file-upload/issues/435

**Comment by pulkitsinghal** [comment]
@nervgh - thank you very much

**Comment by jimeshgajera** [comment]
@nervgh , i have still same error! I am not able to resolve it. I have done bower install

**Comment by eliakorkmaz** [comment]
@jimeshgajera Did you look at the package dependencies to find if is it there on dev depencency or general  ?
