### ISSUE TITLE
onWhenAddingFileFailed is marked private but documented in API as public

### ISSUE THREAD

**Issue by lanoxx** [nervgh/angular-file-upload#454]
In: https://github.com/nervgh/angular-file-upload/blob/master/src/module.js#L248 the `onWhenAddingFileFailed` is marked as `@private`, but in https://github.com/nervgh/angular-file-upload/wiki/Module-API it is documented as a public callback, this is inconsistent and should be fixed by removing the `@private` or removing the callback from the documentation.

**Comment by nervgh** [comment]
Thanks. Fixed 80afa4b
