### ISSUE TITLE
How can I create a image height and width filter?

### ISSUE THREAD

**Issue by Rahuldiff** [nervgh/angular-file-upload#456]
In my app, its necessary to upload images with a minimum height and width like 100 and 200 respectively. How can I filter the height and width of image. Is there a way to get the image width onAfterAAddingfile?
Thanks in advance

**Comment by fabm22** [comment]
I'd like to know too ... any help ?

**Comment by MrSpark2591** [comment]
please help!!!

**Comment by Tinet-wangll** [comment]
+1

**Comment by nervgh** [comment]
Yes, you can. See https://github.com/nervgh/angular-file-upload/pull/289#issuecomment-263529504
