### ISSUE TITLE
Basic use question

### ISSUE THREAD

**Issue by CaliforniaCoder** [nervgh/angular-file-upload#464]
I am still learning the basics of Angularjs and I am just trying to get the basic functionality to work and for the life of me can not figure out how to use the library.

I have included the library in my Index.html file but when I try to use it in the controller it does not recognize the file.

It's defined in my injector code for the controller as -
    var injectParams = ['$location', '$filter', '$window',
                        '$timeout', 'authService', 'tasksService', 'modalService', 'FileUploader'];

And the controller function as -
    var fileUploadController = function ($location, $filter, $window,
        $timeout, authService, tasksService, modalService, FileUploader) {

But it fails here -
        var uploader = $scope.uploader = new FileUploader({
            url: window.location.protocol + '//' + window.location.host + window.location.pathname + '/api/Upload/UploadFile'
        });

What am I doing wrong?

**Comment by aosi87** [comment]
First, what error do you get?, its server error, angular error, syntax error etc
2.- I recommend to use onBeforeUpload to set a dynamic URL
