### ISSUE TITLE
Bug - uploadAll

### ISSUE THREAD

**Issue by CaliforniaCoder** [nervgh/angular-file-upload#465]
This prototype only uploads the first file listed -
            FileUploader.prototype.uploadAll = function() {
                var items = this.getNotUploadedItems().filter(function(item) {
                    return !item.isUploading;
                });
                if (!items.length) return;

```
            angular.forEach(items, function(item) {
                item._prepareToUploading();
            });
            items[0].upload(); <-- ERROR HERE
        };
```

**Comment by nervgh** [comment]
No, it works like an iterator:

```js
let iterator = new Iterator();
iterator.next();
iterator.next();
// ... and so on
```
