### ISSUE TITLE
angular-file-upload with property data object json

### ISSUE THREAD

**Issue by francinecmelo** [nervgh/angular-file-upload#466]
How do I add the data property of $http request on request below:

var app = angular.module('app', ['angularFileUpload']);

app.controller('Aula21Controller', function($scope, FileUploader){

```
var uploader = $scope.uploader = new FileUploader({
    url : 'http://localhost:8080/work/v1/chats',
    alias: 'message-body',
    headers: {'X-Client-Instance': '1.221@0000010000083359', 'Content-Type': 'multipart/formdata'},    
});
```

In my request needs to send a json object (date field) with the items below:

json object - data 

{
    "receiver":"", 
    "localAddress":"", // ip 
    "attachment":"", // name file
    "content":"" // content message
}

Thanks.

**Comment by gscoppino** [comment]
I accomplished this by using the ```onBeforeUploadItem``` callback to push the data into the ```FileItem```'s ```formData``` property.

```
this.data = {
   ...
 }

this.uploader = new FileUploader({
    onBeforeUploadItem: function (item) {
        item.formData.push(this.data);
    }
});
```

**Comment by sebastianfelipe** [comment]
And after that, how can you get access to that formData on server side? Thanks

**Comment by kamilkmita** [comment]
up

**Comment by v29neil** [comment]
@sebastianfelipe On server side, 
If you are using node as backend with body-parser middleware. 
You can access the data in `req.body`

**Comment by nervgh** [comment]
It looks solved
