### ISSUE TITLE
Chunked file upload

### ISSUE THREAD

**Issue by Cervenka** [nervgh/angular-file-upload#468]
It would be great if chunked file upload could be included. It is not possible to upload  2MB+ videos in Chrome on iOS without chunked file upload for instance.

EDIT: the html attribute "multiple" was the issue: https://productforums.google.com/forum/#!topic/chrome/P2-bENFTWEA;context-place=forum/chrome

Cheers

**Comment by Cervenka** [comment]
For anyone willing to implement chunked file upload properly: I'm willing to pay a reward. Cheers

**Comment by nervgh** [comment]
see https://github.com/nervgh/angular-file-upload/issues/118
