### ISSUE TITLE
Its not compatible with Angular 1.3/1.4

### ISSUE THREAD

**Issue by codeomnitrix** [nervgh/angular-file-upload#469]
Hi,

I am using this plugin with angular js 1.4 but it seems that its not compatible with this version, can you please look into this issue since there has been a lot of changes since angular 1.1 version which you are using in your examples.

Error log - 
Zb @ angular.js:8496(anonymous function) 
@ angular-file-upload.js:408
r @ angular.js:323
module.value.factory.FileUploader._transformResponse @ angular-file-upload.js:407
module.value.factory.FileUploader._xhrTransport.xhr.onload @ angular-file-upload.js:470

**Comment by ionox0** [comment]
I believe I may be having issues with trying to use Angular 1.4.3 as well

Is this an acknowledged dependency issue?

**Comment by asakalou** [comment]
Are there any plans to support Angular 1.4 ?

**Comment by codeomnitrix** [comment]
I have created a fork of this current repository at https://github.com/codeomnitrix/angular-file-upload which is compatible with angular 1.4 please let me know if you face any issue. I have created a pull request as well so will upload here once its approved.

**Comment by bkingon** [comment]
@nervgh Could we possibly get this merged in?

**Comment by tizot** [comment]
Up :)

**Comment by jlien-calwater** [comment]
@nervgh bumping for 1.4 support.

**Comment by majestix508** [comment]
@nervgh please support for 1.4 or maybe a merge from the codeomnitrix repo

**Comment by cyberua** [comment]
I took this task.

**Comment by dud3** [comment]
@nervgh bumping for 1.3/1.4.

**Comment by cyberua** [comment]
I tested with angular 1.4, 1.3 and all works.
Tested on ubuntu, chrome 44 and firefox 39, nodejs server response: string, json.
I need more information, what does not work?

**Comment by bkingon** [comment]
@cyberua The bower.json files has `"angular": "~1.2.11"` in it, and so we are unable to use it with angular 1.3/1.4

**Comment by majestix508** [comment]
I use it with angular 1.4.4 and it works so far.
Just one warning:
Warning: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

**Comment by cyberua** [comment]
@bkingon I tested, everything works on 1.4.4, we will chabge soon version in bower.

**Comment by tregusti** [comment]
Looking forward to the dep bump! :+1:

**Comment by plainlystated** [comment]
+1

**Comment by nervgh** [comment]
8efa7ded6fdef10938e20f7ec5021ea80227adff
