### ISSUE TITLE
bower.json incorrect

### ISSUE THREAD

**Issue by tobibrandenberg** [nervgh/angular-file-upload#470]
Hi!

Could you please point the "main" key in bower.json to "dist/angular-file-upload.min.js"?! Otherwise grunt tasks won't work....

**Comment by awk** [comment]
:+1:

**Comment by kashyapmukkamala** [comment]
:+1:

**Comment by ailnlv** [comment]
yes please

**Comment by nervgh** [comment]
fixed #471
