### ISSUE TITLE
Broken backward compatibility

### ISSUE THREAD

**Issue by iddqdidkfa** [nervgh/angular-file-upload#479]
With [this commit](https://github.com/nervgh/angular-file-upload/commit/6c7ff41b5324adab3251bddd4a288956aa32764d) you have moved JS files to dist folder and didnt change major version. So on clear environment bower will install new version that will not work with old path.

**Comment by nervgh** [comment]
Sorry. Fixed 5100d9676ed3af410009b1a020d55f84a9a0a73e

**Comment by iddqdidkfa** [comment]
Thanx dude, now I have to update path one more time :)
