### ISSUE TITLE
uploader success binding been triggered twice

### ISSUE THREAD

**Issue by bettysteger** [nervgh/angular-file-upload#48]
i have the following code:

```
  if(uploader.queue.length) {
    var firstItem = uploader.queue[0];
    uploader.uploadItem(firstItem);

    // successful upload
    uploader.bind('success', function (event, xhr, item) {
      console.log("success")
      uploader.clearQueue();

      var response = angular.fromJson(xhr.response);
      successCallback(response);
    });

    // unsuccessful upload
    uploader.bind('error', function (event, xhr, item) {
      var response = angular.fromJson(xhr.response);
      errorCallback(response);
    });
}
```

it works just fine, but not in a special case:
1. I choose a file, but don't fill out a required input field
2. I get an 400 server response 
3. I fill in the required input field and submit the form again (the item is still in the uploader queue)
4. "success" is triggered twice and I really don't know why..

when there is not a failing error before than it's just triggered once!

i hope you know what I mean and can help me ;)

**Comment by awerlang** [comment]
It's better to bind to events just at initialization.

Startup:

    // successful upload
    uploader.bind('success', function (event, xhr, item) {
      console.log("success")
      uploader.clearQueue();

      var response = angular.fromJson(xhr.response);
      successCallback(response);
    });

    // unsuccessful upload
    uploader.bind('error', function (event, xhr, item) {
      var response = angular.fromJson(xhr.response);
      errorCallback(response);
    });

Submit:

    if(uploader.queue.length) {
      var firstItem = uploader.queue[0];
      uploader.uploadItem(firstItem);
    }

**Comment by zabaz** [comment]
try to check your $routeProvider, may be your routing execute your controller twice
