### ISSUE TITLE
how to compress the image using angular-file-upload?

### ISSUE THREAD

**Issue by TonyLuo** [nervgh/angular-file-upload#481]
Is there any API to compress the image using angular-file-upload? Sometimes the image size is too large, I would like to only upload the compressed image to server.

**Comment by alvinshi** [comment]
+1

**Comment by anil1712** [comment]
Hi @TonyLuo 
Did you get any solution for the same?

**Comment by zral** [comment]
Hi @TonyLuo - did you manage to do this?

**Comment by TonyLuo** [comment]
not yet. i compress the image in the server instead of compressing it before uploading.
