### ISSUE TITLE
mutating the [[Prototype]] of an object will cause your code to run very slowly

### ISSUE THREAD

**Issue by mroberty8** [nervgh/angular-file-upload#482]
This module cause this warning : mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

It looks like tha the module use ```e.__ proto__=smthing```

Can fix it please ?

**Comment by nervgh** [comment]
Since [v2.1.0](https://github.com/nervgh/angular-file-upload/tree/v2.1.0) this module uses [Babel](http://babeljs.io/) with `_inherits` function:
```js
var _inherits = function(subClass, superClass) {
  if (typeof superClass !== "function" && superClass !== null) {
    throw new TypeError("Super expression must either be null or a function, not " + typeof superClass);
  }
  subClass.prototype = Object.create(superClass && superClass.prototype, {
    constructor: {
      value: subClass,
      enumerable: false,
      writable: true,
      configurable: true
    }
  });
  if (superClass) subClass.__proto__ = superClass;
};
```
See https://babeljs.io/docs/advanced/caveats/#classes-10-and-below-

**Comment by kgeoir** [comment]
Hello,
Any news on this topic? I got the same and your link to babeljs is broken.

**Comment by nervgh** [comment]
@kgeoir , https://phabricator.babeljs.io/T6847
