### ISSUE TITLE
How to pass JWT Token with uploader()

### ISSUE THREAD

**Issue by Mr-Anonymous** [nervgh/angular-file-upload#486]
I am using Satellizer that adds the JWT Token to headers when sending requests to the backend api (laravel in my case). When token is not present, the api will not process the request. However, when I process the `uploader`, I am getting the `token_not_provided` error from api. 

This is the `uploader` settings in controller:
```
	var uploader = $scope.uploader = new FileUploader({
			url: 'api/upload',			
	});
```	
However, I am able to get this to work if I manually add the token set in `localStorage` to the api URL as a parameter like this:
```
	var uploader = $scope.uploader = new FileUploader({
				url: 'api/upload?token=' + localStorage.getItem('my_token'),				
		});
```		
But the above method seems too dirty and more of a hack for me. Can someone share how do you pass the JWT token with `uploader` please?

**Comment by Denfie** [comment]
I use for my token authorization the header informations like...

var pdf_uploader = $scope.pdf_uploader = new FileUploader({
            url: [URL],
            withCredentials: false,
            autoUpload: true,
            method: 'PUT',
            removeAfterUpload: true,
            headers: {
                Authorization: 'Bearer ' + $sessionStorage.token
            }
});

**Comment by Mr-Anonymous** [comment]
Thank you so much @Denfie

Using your sample, I now have this that adds the JWT token to header and the request go through fine now after adding the token to header like this:
```
uploader.onBeforeUploadItem = function (item) {
  item.headers = {
	'Authorization': 'Bearer ' + localStorage.getItem('token_name')
  };
};
```
Thank you so much for sharing your code. It helped me by pointing in the right direction. Much obliged!
