### ISSUE TITLE
File upload doesn't get the origin path of image.

### ISSUE THREAD

**Issue by celsomtrindade** [nervgh/angular-file-upload#497]
When I try to upload an image, i get a blank origin path, and because of this, i'm not able to send the file to my database/folder. I'm using php as backend with the code [provided in here](https://github.com/nervgh/angular-file-upload/blob/master/examples/image-preview/upload.php)

On the console log, I have this return:

    name: "_01_Color_home.jpg"
    size: 2717610
    type: "image/jpeg"
    webkitRelativePath: ""

And also, when i try to log the return from the php file, i'm using this:

	print_r($tempPath);
	print_r($uploadPath);

But the `print_r($tempPath);` is blank, without any return.

How can i fix this? Or what i did wrong?

**Comment by nervgh** [comment]
> Origin path of image

client does not know. The security politics.
You could set up own path to files on your server.
