### ISSUE TITLE
Prevent file upload on dropping outside drop zone

### ISSUE THREAD

**Issue by srivshreya** [nervgh/angular-file-upload#499]
I want to prevent the user from dropping the file outside the drop zone by showing some cross and preventing the file from opening in the browser. Is the functionality already existing?

**Comment by nervgh** [comment]
No. You could write your own directive for this.

**Comment by syl20lego** [comment]
there is no feedback but I was able to do something using option and the body 
nv-file-drop="" uploader="uploader" options="{ disabled: true }"
and a filter
        uploader.filters.push({
            name: 'disabledElement',
            fn: function(item, options) {
                return !options.disabled;
            }
        });

is there a better way, I think the library should prevent drop file outside the drop zone.

**Comment by nervgh** [comment]
@syl20lego :+1:
