### ISSUE TITLE
how to make a server call when pressing upload in asp mvc c#

### ISSUE THREAD

**Issue by angelmalca** [nervgh/angular-file-upload#500]
i'm new to angular but i pretty much understand the hang of if. 
i'm using the "Uploads only images (with canvas preview)" example and i combined it successfully in a new asp MVC project view,so , now when i start the project in the debugger the client side works good.

Now i need to implement the server side and connect it to to the view .
i went to the AppController in the controllers.js file and changed the url in the uploader method to :

var uploader = $scope.uploader = new FileUploader({
            url: '/HomeController/Upload/'
        });

HomeController is the ASP MVC Controller and Upload is the controllers method.
now in the Upload method in the server side i implemented the method as follows:

[HttpPost]
public void Upload(HttpPostedFileBase file)
{
            // do something  
}

obviously it doesn't do anything but first i'm just trying to catch the ajax call which i can't seam to do in various ways.

i looked all over the comment section to find a solution but i only found pieces of information regarding implementation of this great library with AP MVC project.  couldn't find a full solution to the problem.

could you please supply a full server side solution to this simple task including the pieces needed to be customized in the client side for this to work?

many thanks

**Comment by Gyyone** [comment]
var uploader = $scope.uploader = new FileUploader({
url: '/HomeController/Upload/'
});

HomeController is the ASP MVC Controller and Upload is the controllers method.
now in the Upload method in the server side i implemented the method as follows:

[HttpPost]
public void Upload(HttpPostedFileBase file)
{
// do something
}

It is working for me, Just need make sure that the Url Are correct.
