### ISSUE TITLE
Angular 1.4.x Support

### ISSUE THREAD

**Issue by jsmylnycky** [nervgh/angular-file-upload#509]
Hi,

It looks like this plugin does work fine on Angular 1.4.3, but would it be possible to verify by the devs that this is intended to work properly on 1.4.x?  If so, can the bower.json file be updated with >= syntax to avoid potential code incompatibility warnings?

Thanks

**Comment by nervgh** [comment]
Updated https://github.com/nervgh/angular-file-upload/commit/8efa7ded6fdef10938e20f7ec5021ea80227adff
