### ISSUE TITLE
Submit all files at once

### ISSUE THREAD

**Issue by albertomizrahi** [nervgh/angular-file-upload#51]
Hello, 

Angular-file-upload has worked great so far. My only question is: is there a way to upload all the files in the queue in one request rather than send a request per file?

Thanks for your help!

**Comment by fxck** [comment]
Having the same problem, need to send uploaded files with email.. much bigger pain in the ass for either user(having to archive the files first), or me having to store them on server, figuring out the last request had been sent, get the files, send them, delete them..
