### ISSUE TITLE
Single array to send all files

### ISSUE THREAD

**Issue by Sudheervelivala** [nervgh/angular-file-upload#510]
Hi Team,
I am trying to upload files along with form data. I can able to send form data as an array but I need to send all selected files into single array instead of individual file. 

Expecting somthing like this:
Files:[array of files],
formData:[array of form data],
url: 'api-path',

Thanks In Advance.

Best regards ,
Sudheer

**Comment by nazmulhossain** [comment]
Hi Team, 
have a any answer for that?
i have also same problem with your plugin.

Thanks in advance.

**Comment by nervgh** [comment]
https://github.com/nervgh/angular-file-upload/issues/389#issuecomment-145818827
