### ISSUE TITLE
drag and drop only for single image

### ISSUE THREAD

**Issue by divyashekhawat** [nervgh/angular-file-upload#511]
Hello,
Many thanks for this nice plugin. Please tell me how can restrict drop zone to accept only one file and show only one file in progress section also. 
Thanks

**Comment by celsomtrindade** [comment]
From the docs: https://github.com/nervgh/angular-file-upload/wiki/Module-API
There is an attr called 'queueLimit'.

**Comment by zendu** [comment]
@celsomtrindade, from documentation it is not clear where to put this attribute. Also there is not a single example that can be referred to.

**Comment by nervgh** [comment]
```js
uploader.queueLimit = {Number}
```
https://github.com/nervgh/angular-file-upload/wiki/Module-API#properties
