### ISSUE TITLE
"Uncaught ReferenceError: angular is not defined" when loading module using requirejs

### ISSUE THREAD

**Issue by bennorwood** [nervgh/angular-file-upload#513]
in path->'angularFileUpload': '../plugin/angular-file-upload/angular-file-upload.min'
in shim->'angular': {'exports': 'angular', deps: ['jquery']}, 'angularFileUpload': {deps: ['angular']}

**Comment by bennorwood** [comment]
Loads successfully the first time, on page refresh I receive this error.

**Comment by nervgh** [comment]
@bennorwood sorry for silent by this issue. I have not time enough :crying_cat_face:
