### ISSUE TITLE
$http and angularFileUpload

### ISSUE THREAD

**Issue by sreinoso** [nervgh/angular-file-upload#515]
Hello,
I'm doing my first angular APP, and I need to use angularFileUpload with $http, but I don't know how I have to use it.

With this code:
angular .module('WishList', ['angularFileUpload']).controller('MainControl', ['$scope', 'FileUploader','$http', function($scope, FileUploader,$http) {.......

I have this error: [$interpolate:interr]
Someone knows what I must to do?
Thanks

**Comment by nervgh** [comment]
Hi

Currently you could not use $http with angular File Upload out of the box.
See https://github.com/nervgh/angular-file-upload/milestones/3.0.0

Sorry.
