### ISSUE TITLE
"No file chosen" label on upload button

### ISSUE THREAD

**Issue by RobertVogt** [nervgh/angular-file-upload#516]
@nervgh In the code for my upload button...
                        <input id="fileSelector" type="file" nv-file-select="" uploader="ctrl.uploader" multiple accept=".pdf, image/tiff, .tif"/>

The label reads "No file chosen" even when a file is selected...I worked with my code for a couple hours before going to the "simple example" and realized it was happening in the example code too.  

Is this a bug?  How to I update the label or hide it? I've noticed another unresolved question about this as well.

**Comment by RobertVogt** [comment]
@nervgh I have a deadline for the code I'm using this upload in...will this question be answered anytime soon?

**Comment by nervgh** [comment]
> I have a deadline

You are not one :blush:

https://yadi.sk/i/lydRCoO9j8KEi
https://github.com/nervgh/angular-file-upload/wiki/FAQ#4-no-file-chosen-or-re-add-same-file

**Comment by RobertVogt** [comment]
I understand...but this is not a good solution, users get confused when they select files and the label says "No files chosen".  The label should be an input that you can write to so that either the file queue number can be displayed or empty string...or really whatever you want, it should not be locked down @nervgh

**Comment by gerome0123** [comment]
@RobertVogt can u give an example? :)
