### ISSUE TITLE
Files not being added to queue after firts file selection

### ISSUE THREAD

**Issue by diogodomanski** [nervgh/angular-file-upload#517]
I am using angular-file-upload module (version 2.1.4 with angular 1.4.5). I took the "Uploads only images (with canvas preview)" example as the starting point.

However, when I click the "Select files" button, only at the first time the selected files are added to the queue. If I click "Select files" button a second time (even if there is any file in the queue or not), the new selected files are not added to the queue.

As a way to find out where is the problem, I've attached an "onchange" event to the file input field:
```html
<input type="file" nv-file-select="" uploader="uploader" multiple onchange="alert('changed')"/>
```
Everytime I click "Select files" button (it doesn't matter if is the first time or fifth time) the alert is always shown - but the files are added to the queue only at the first time.

Debugging the source-code, I've confirmed that FileSelect::onChange() method is being called only at the first file selection - and the instruction at line 69 (this.element.prop('value', null);) is being executed.

Watching to the console panel (Firefox 40.0.3 or Chrome 45.0), no error message is shown.

The original "Uploads only images (with canvas preview)" example works fine in both browsers. I've tried to make my code as similiar as possible to the example.

What am I doing wrong?

**Comment by diogodomanski** [comment]
PS: if I remove the "multiple" attribute from ```<input>``` it works

**Comment by nervgh** [comment]
Please, see [faq 4. "No file chosen" or "Re-add same file"](https://github.com/nervgh/angular-file-upload/wiki/FAQ#4-no-file-chosen-or-re-add-same-file)

**Comment by diogodomanski** [comment]
Hi @nervgh,

I guess is not the same issue. I've done everything that is mentioned in FAQ 4. But the problem seems to be the opposite. It works with single selection and doesn't work with multiple attribute defined.

**Comment by nervgh** [comment]
> It works with single selection and doesn't work with multiple attribute defined.

Are you sure?
>
```js
FileUploader.FileSelect.prototype.isEmptyAfterSelection = function() {
    return {Boolean}; // true|false
};
```
https://github.com/nervgh/angular-file-upload/wiki/FAQ#4-no-file-chosen-or-re-add-same-file

https://github.com/nervgh/angular-file-upload/blob/v2.1.4/src/services/FileSelect.js#L68

**Comment by richardmqq** [comment]
I am having the same issue here. Once I have selected file(s) and they have been added into queue, the queue no longer gets updated any more.

**Comment by AMWN** [comment]
Still exactly the same problem over here...

**Comment by roman-srek** [comment]
The root cause is fix for IE in FileUploader onChange method:
`this.element.replaceWith($compile(this.element.clone())(this.scope)); // IE fix`

Picking multiple filles works fine in Firefox when you modify it to execute in IE only:
`var userAgent = window.navigator.userAgent;
var.isIE = userAgent.indexOf('Edge/') > 0 || userAgent.indexOf('Trident/') > 0 || userAgent.indexOf('MSIE ') > 0;
if (isIE) {
     this.element.replaceWith($compile(this.element.clone())(this.scope)); // IE fix
}`
