### ISSUE TITLE
Uplaoder doesn't work on safari 5.1.7

### ISSUE THREAD

**Issue by Nizzypal** [nervgh/angular-file-upload#518]
We used the uploader on our project and it works on all browsers, except Safari for Windows 5.1.7... When I click the drag area, nothing happens.  Nothing shows up in the console. I added code to show an alert if a click event is done in the div containing the directive.  An alert fred but that was it.

Any ideas?

**Comment by nervgh** [comment]
[Safari for Windows was deprecated](http://apple.stackexchange.com/a/94010).
