### ISSUE TITLE
Create Multiple FileUploader

### ISSUE THREAD

**Issue by flaviotomazio** [nervgh/angular-file-upload#520]
I have a unlimited number of requests in a list, i need upload file to each request, actually i use this:

[
 {id: 123,
  uploader: new FileUploader({url: url...+ 123})
},
 {id: 456,
  uploader: new FileUploader({url: url...+ 456})
}
]

But when the upload start, they always send the file to same URL (.. 123), is possible change this?

**Comment by nervgh** [comment]
You could create single instance of `FileUploader` and pass options via attributes:
```html
<element nv-file-drop uploader="{FileUploader}" options="{url: 'string'}"></element>
<input type="file" nv-file-select uploader="{FileUploader}" options="{url: 'string'}"/>
```
