### ISSUE TITLE
Dist folder contians only minified version

### ISSUE THREAD

**Issue by thomasfl** [nervgh/angular-file-upload#526]
This can cause problems in some projects. In my case I am not able to include angula-file-upload in my vendor.js and run uglify on it.

**Comment by albv** [comment]
+1

**Comment by nervgh** [comment]
Related https://github.com/shama/webpack-stream/issues/78

**Comment by michelem09** [comment]
+1

**Comment by nervgh** [comment]
We say thanks @andrei-cacio =)
