### ISSUE TITLE
Unable to run gulp tasks

### ISSUE THREAD

**Issue by thomasfl** [nervgh/angular-file-upload#527]
Maybe add a few lines to the README.md telling how to run the gulp tasks?

**Comment by nervgh** [comment]
Standard way:

```
npm install
gulp <task_name>
```

List of tasks
```
gulp --tasks
```

I use GUI of IDE for running tasks.

**Comment by thomasfl** [comment]
Thanks. I am not used to using gulp. If gulp is installed using "npm install -g gulp" instead of "npm install" then "gulp --tasks" doesn't work, but "gulp angular-file-upload/build" does.

I propose adding a few lines to the bottom of the readme file.

## Building angular-file-upload

```
   npm install
   gulp  angular-file-upload/build
```

To run tests.

```
    angular-file-upload/watch
```
