### ISSUE TITLE
Retrieve back all the images

### ISSUE THREAD

**Issue by sivaio** [nervgh/angular-file-upload#529]
Hi, how can I retrieve back all the images from db and load into the canvas? Lets say I can retrieve a json info from server about file name, file url and etc.

**Comment by cho-is** [comment]
+1

**Comment by vinimtex** [comment]
+1

**Comment by felipemendesbraga** [comment]
+1

**Comment by rainstormza** [comment]
+1

**Comment by nervgh** [comment]
See #211

**Comment by rainstormza** [comment]
is that work with angular 2  ?

https://github.com/valor-software/ng2-file-upload

**Comment by nervgh** [comment]
@rainstormza not today =)

It looks like a port of my module.

**Comment by rainstormza** [comment]
ok , please tell me a way when you 're ready :)

I try your way with anuglar 2 , it not work :(
