### ISSUE TITLE
Get an empty file after upload file (Chrome)

### ISSUE THREAD

**Issue by 1043099804** [nervgh/angular-file-upload#533]
I used code as below but after trigger the url, req.body is empty. Could someone help me check where is the issue?  
var IndexAPP = angular.module('IndexAPP', ['ngResource', 'ngRoute','angularFileUpload']);

IndexAPP.controller('IndexController',function($scope, $resource, $routeParams, $location,FileUploader) {
	var uploader = $scope.uploader = new FileUploader({
        url:'/picture'
    });
    $scope.upload_form_show = false;
	$scope.upload = function(){
        $scope.upload_form_show = true;
    };

});
</code>

**Comment by nervgh** [comment]
You can look closed [issues](https://github.com/nervgh/angular-file-upload/issues?q=is%3Aissue+label%3ANode.js+is%3Aclosed) with the `Node.js` tag.

**Comment by 1043099804** [comment]
Yes, it is because I didn't use the busboy. Thanks!
