### ISSUE TITLE
Response for preflight has invalid HTTP status code 406

### ISSUE THREAD

**Issue by ketannaik** [nervgh/angular-file-upload#534]
How to avoid preflight OPTIONS request?

**Comment by nervgh** [comment]
What? =)

**Comment by ketannaik** [comment]
I am using your library i.e. angular-file-upload. while uploading the file i am getting error as "Response for preflight has invalid HTTP status code 406". So how to avoid this issue?

**Comment by josencv** [comment]
The preflight OPTIONS request is a part of the [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) convention to prevent unwanted requests to external domains. I think your problem has nothing to do with the uploader itself but with where you are uploading the file to. You probably have to configure your request headers in your client and/or in your server to allow CORS requests.

PS: You can access the uploader request headers using:

```javascript
uploader.headers = { some-header: some-value }
// Or if you have access to the FileItem
item.header = { some-header: some-value }
```
