### ISSUE TITLE
Sending parameters from UI

### ISSUE THREAD

**Issue by clubbavi** [nervgh/angular-file-upload#539]
Hello,

I am uploading multiple files. How can I send extra parameters from the UI dynamically as I would not be knowing which values are there?
Example:
```
<label class="btn btn-default" ng-repeat="docType in types">
    <input type="radio" ng-model="$parent.selectedType" name="name" value="{{docType.type}}" 
          required />{{docType.type}}
</label>
<button type="button" class="btn btn-success btn-s" ng-click="uploader.uploadAll()" 
      ng-disabled="!uploader.getNotUploadedItems().length">
```

Can we send selectedType parameter in ng-click along with uploader.uploadAll ?
& can we get all the uploaded items in a single array?

Thanks

**Comment by Webbrother** [comment]
+1

**Comment by ganeshghalame** [comment]
+1

**Comment by nervgh** [comment]
See 

https://github.com/nervgh/angular-file-upload/wiki/FAQ#2-how-to-update-fileitem-options-before-uploading
https://github.com/nervgh/angular-file-upload/wiki/FAQ#3-i-need-custom-options-are-there-any
https://github.com/nervgh/angular-file-upload/pull/377
