### ISSUE TITLE
How to upload same file twice?

### ISSUE THREAD

**Issue by ubaid-rehman** [nervgh/angular-file-upload#542]
I am taking file input in a dialog, my flow is as follows:

User open dialog, Upload File, User Closes the dialog

The issue is, when the user opens the dialog next time, without refreshing the page (obviously), the previous file name is still there next to "browse" button. But when user click on upload, it doesn't upload the same file, even if the user re select the same file. I know it has something to do with the onchange event but how to solve this?

**Comment by geemang2000** [comment]
:+1:  Having the same issue. Same issue when you "cancel" the item in your queue. Can't re-add the file if its already there next to the "browse" button.

**Comment by verlinden** [comment]
Had the same issue and fixed it thanks to this https://github.com/nervgh/angular-file-upload/wiki/FAQ#4-no-file-chosen-or-re-add-same-file

**Comment by ubaid-rehman** [comment]
Thanks verlinden, I will definitely try this.

**Comment by nervgh** [comment]
Please, see [this comment](https://github.com/nervgh/angular-file-upload/issues/542#issuecomment-155801037) =)

**Comment by loveXiaoiao** [comment]
By default the value property of input element cleared after selection of files if the input have multiple attribute. If you do not clean this property then "change" event will not be fired if you select same file. You can manage this behavior:

Using multiple attribute

<input type="file" nv-file-select uploader="{FileUploader}" multiple/>

<input type="file" nv-file-select uploader="{FileUploader}"/>

**Comment by arthurChennetier** [comment]
You can also resolve this by setting your input value to null when you click it !: 
`onclick="this.value=null"`

**Comment by hashishshetty** [comment]
Thanks, @arthurChennetier! That was amazing!
