### ISSUE TITLE
Cancle ohne of many items by using form validation and UploadAll

### ISSUE THREAD

**Issue by UltimateFighter** [nervgh/angular-file-upload#544]
In exampel i have 3 items to upload with uploader.uploadAll.
One of the 3 items is not valid to upload (additinal description textarea for this item is to long).
How can i skip/cancle/disable this one item during the exekution of the method uploadAll?

**Comment by nervgh** [comment]
You can redefine the `Uploader#getNotUploadedItems()` method

https://github.com/nervgh/angular-file-upload/blob/v2.2.0/src/services/FileUploader.js#L134
https://github.com/nervgh/angular-file-upload/blob/v2.2.0/src/services/FileUploader.js#L186

**Comment by UltimateFighter** [comment]
But imo the getNotUploadedItems() get the not uploaded items _after_ the post request. I will to inhibit the request.

I have to try a Return false in the onBeforeUpload method or a item.cancel, but nothing helps. The request of all items are sending to my server

**Comment by UltimateFighter** [comment]
Thats the right way :) Thank you.
