### ISSUE TITLE
Initialize FileUploader Dynamically

### ISSUE THREAD

**Issue by archbrys** [nervgh/angular-file-upload#547]
Is it possible to initialise FileUploader dynamically with scope? Let's say when ever i click a button it will create a new uploader. I'm doing this for my chat box where when I open a popup it will initialise a new FileUploader.
```HTML
<button ng-click="openPopup()">New Chat box</button>
```

```javascript
$scope.openPopup = function() {
     var genereteID = Math.floor(Math.random() * (100000000 - 1000 + 1)) + 1000;
     $scope.conversation[genereteID].uploader = new FileUploader();

     var $tpl = $('\
                <div> \
                    <input type="file" ng-file-select uploader="conversation['+genereteID+'].uploader"> \
                </div> \
            ');  
    var element = $compile($tpl)($scope);
    $( "body" ).append( element );
}
```

When I open a popup, I got this Error
```javascript
TypeError: "Uploader" must be an instance of FileUploader
```

**Comment by nervgh** [comment]
Yes. There are many ways do this:
1. You can create `FileUploader` in directive link function
2. You can use the `ng-if` directive
3. ...

**Comment by archbrys** [comment]
how can i use the ng-if and what for?

**Comment by nervgh** [comment]
```html
<element ng-if="expression">
    // html with uploader logic here
</element ng-if="expression">
```

Also, [this](https://github.com/nervgh/angular-file-upload/issues/111) may be useful

**Comment by archbrys** [comment]
Sorry for the very late reply.

Already using ng-if thanks for the answer.
