### ISSUE TITLE
Change button name of "Choose File"

### ISSUE THREAD

**Issue by colbroth** [nervgh/angular-file-upload#549]
Does the FileUploader have an option to change the name of the button? I am using the simple model of FileUploader. It displays a button [Choose File] and the text "No file chosen". I need to change the name of [Choose File]. Is this allowed? I have to support multiple languages, could it be possible to have this as an option in the FileUploader constructor? i.e.
  var uploader = new FileUploader({
        'url': url,
        'headers': {
          'Authorization': $http.defaults.headers.common.Authorization,
        },
        'queueLimit' : 2
        'buttonName': 'replace Choose File with Datei auswählen'        <<<<<<<<<<<<<<<<<
        'textBesideButton': 'replace No file chosen with Keine Datei ausgewählt' <<<<<<<<<<<<<<<<
      });

**Comment by nervgh** [comment]
Please, see https://github.com/nervgh/angular-file-upload/issues/204
