### ISSUE TITLE
Drop doesn't work in IE if element has no dimensions set

### ISSUE THREAD

**Issue by paul-request** [nervgh/angular-file-upload#552]
This isn't really a bug with the nv-file-uploader, but it would be good to add it to some troubleshooting or something similar.

The element that has the nv-file-drop directive needs to have an explicit height or width set in the CSS otherwise Internet Explorer with try to open the file rather than upload it.

**Comment by tbprojects** [comment]
@pmbennett thank you for that suggestion :+1:

**Comment by DumboJet** [comment]
@paul-request 
Thanks for posting this.
It would take me ages to figure this one out... :|

**Comment by nervgh** [comment]
@paul-request :+1: 

It looks solved.
