### ISSUE TITLE
How to call file browser by click on the file drop area?

### ISSUE THREAD

**Issue by proteye** [nervgh/angular-file-upload#553]
Hello.
Thank you for this plugin.
How to call file browser by click on the file drop area?
I want to add files by click and drop on the file drop area.

**Comment by corehook** [comment]
+1

**Comment by BennyB116** [comment]
Just place an input of type file within the file drop area div.

**Comment by lpsBetty** [comment]
I hid the input-file select and made an own simple directive for that!

````
/**
 * Dropzone directive to open file-select on click.
 * angular-file-upload cannot do that out of the box.
 */
angular.module('app').directive('lhDropzone', function ($timeout) {
  return {
    restrict: 'A',
    link: function(scope, element) {
      element.click(function() {
        $timeout(function () {
          element.find('input[type="file"]').click();
        });
      });
    }
  };
});

**Comment by lpsBetty** [comment]
I delete my directive again and did it just via HTML (+CSS).
It is only necessary to surround the input[type=file] with a `label` element, like this

    <label class="dropzone" nv-file-over uploader="uploader" over-class="in">
      Select File

      <i class="fa fa-file-text-o"></i>

      <input class="hidden" nv-file-select uploader="uploader" type="file" multiple />
    </label>

or set the same name for `label[for]` and `input[id]`

      <label for="avatar" class="dropzone" nv-file-over uploader="uploader" over-class="in">
        Select File
      </label>
      <input nv-file-select uploader="uploader" type="file" id="avatar" class="hidden" />
