### ISSUE TITLE
How to get response from the api ?

### ISSUE THREAD

**Issue by leovetter** [nervgh/angular-file-upload#558]
Hi everyone,

I'm using angular-file-upload to upload image to my api like so :

`
var uploader = $scope.uploader = new FileUploader({
    url: 'http://localhost:8000/image',
    headers: {
      'X-CSRFToken': $('input[name="csrfmiddlewaretoken"]').attr('value')
    },
  });
`

Then what I have been unable to figure out is how to get the response from the api (Some data that I need to insert into my html). I first supposed I would be able to register some kind of listener but I didn't find anything that could allow me to do that.  

Does the angular-file-upload module provide a way to do this or do I need to rely on an other angularjs functionality ?

Thanks in advance for any help !

**Comment by gugahoi** [comment]
You need to use one of the callbacks, for example:

````js
	$scope.uploader = new FileUploader({
        ....
		onSuccessItem: function(item, response, status, headers) {
			console.log(item, response, status, headers);
		},
        ....
	});

**Comment by smohamali** [comment]
I ran into the same issue. 
It appears as though the call back function is called immediately and not after the server has returned its response.

**Comment by amacar** [comment]
There is no issue, callback is working ok.

For example:
`$scope.uploader.onSuccessItem = function(fileItem, response, status, headers) {
      $scope.success = 'Datoteka uspešno naložena';
      $scope.error = null;
      
      if (response && response.datotekaId) {
        $scope.imageUrl = "api/datoteke/" + response.eiksDatoteka.datotekaId;
      }
    };`
