### ISSUE TITLE
IE9: iframe transport opens a dialog to save the response of the uploadItem call and does not trigger callbacks.

### ISSUE THREAD

**Issue by calmvp** [nervgh/angular-file-upload#563]
Version: angular-file-upload v2.2.0
In IE9 using uploadItem causes a dialog to open requesting that I save or open a .json file containing the response from my uploadItem request. So while the upload occurs successfully, I don't want this dialog to occur and no callback functions are fired (like onSuccessItem, for example). From looking at the angular-file-upload script it appears that this use case should be handled and I feel like I'm missing something obvious. Or is this use case only covered as far as uploading goes and then we implement our own code to handle the response to the iframe? Please let me know if I can provide any additional information to help clarify.

**Comment by calmvp** [comment]
I ended up resolving this issue with help from #137 and subsequently #216. Basically, ensure that your server responds with '''content-type="text/plain"''' and then parse '''<pre></pre>''' tags from your response after parsing to JSON.

**Comment by nervgh** [comment]
:+1:
