### ISSUE TITLE
Unable to add callbacks to the uploader object, only onAfterAddingFile seems to work

### ISSUE THREAD

**Issue by chrillewoodz** [nervgh/angular-file-upload#564]
I'm going mad over this, I can add the onAfterAddingFile callback just fine, but when I want to check for successItem or anything else the uploader callbacks aren't being bound to the uploader.

I do this:

    uploader.onAfterAddingFile = function(item) {

	    item.formData = [{
		    file: item._file
	    }];
		
	    Array.prototype.push.apply(item.formData, uploader.formData);
    };
	
    uploader.onSuccessItem(function(item, response, status, headers) {
	    console.log(item);
    });

But onSuccessItem is not even being bound to the uploader object when I console.log the uploader. 

What could be the issue?

**Comment by nervgh** [comment]
See [examples](https://github.com/nervgh/angular-file-upload/blob/master/examples/simple/controllers.js#L44).

**Comment by chrillewoodz** [comment]
I've looked the every example... They're not working. The issue is that one is working but the rest isn't. It's not a closed issue.

**Comment by nervgh** [comment]
Is there difference
```js
// your code
uploader.onSuccessItem(function(item, response, status, headers) {
    console.log(item);
});
// --------------------------
// code of example
uploader.onSuccessItem = function(fileItem, response, status, headers) {
    console.info('onSuccessItem', fileItem, response, status, headers);
};
```
?

**Comment by chrillewoodz** [comment]
No there isn't. Because my code should still be bound to the uploader. Regardless of what the parameters are named or if I do a console.info in it.

**Comment by nervgh** [comment]
:smile:
