### ISSUE TITLE
Uploading same image again after delete

### ISSUE THREAD

**Issue by Jeevanandanj** [nervgh/angular-file-upload#565]
I've uploaded a image. I've saved the image in the server. Again If I upload the same image, the image is not loaded.

I've set the removeAfterUpload attribute to true. After upload the image in the server, I am getting the issue is like
"Uncaught TypeError: Cannot read property 'isUploading' of undefined"

Is there anything I've missed to write in the code?

**Comment by nervgh** [comment]
Did you see [faq](https://github.com/nervgh/angular-file-upload/wiki/FAQ#4-no-file-chosen-or-re-add-same-file)?
