### ISSUE TITLE
data-button-text as variable

### ISSUE THREAD

**Issue by baumannzone** [nervgh/angular-file-upload#569]
Hello, Im using angular file upload, and it's working very well. 
Now my app, is going to support multilanguage (using angular-translate), so I need to change `data-button-text` according to my languague variable. 
I've been testing and I can't use a variable in `data-button-text`.  
Do you know why? Any help? I think it's possible but I don't know how.

thanks.

**Comment by nervgh** [comment]
I think your issue is not related with `angular-file-upload`.
Documentation of the angular 1.x.x may be useful in this case.
