### ISSUE TITLE
Re-Adding the last removed file doesn't work

### ISSUE THREAD

**Issue by thunderbless** [nervgh/angular-file-upload#570]
I got this problem using the simple example: http://nervgh.github.io/pages/angular-file-upload/examples/simple/

Steps:
- Choose file, file is added to queue
- Remove file from queue
- Choose the same file, file is NOT added to queue

**Comment by KimCrab** [comment]
Same issue here...

**Comment by chiccomotta** [comment]
Same problem for me... is there a workauround for this?
Thanks

**Comment by exploratory666** [comment]
Same problem ,what should  I do ?  thanks

**Comment by MrSpark2591** [comment]
same problem here

**Comment by arshtepe** [comment]
It is bug bound with input type=file. If you select file, event change does not work if you choice file which the already select.
Solution:
after select file, reset input value.

I fix this.

**Comment by arshtepe** [comment]
About this , author already  wrote https://github.com/nervgh/angular-file-upload/wiki/FAQ#4-no-file-chosen-or-re-add-same-file . I need read documentation :)
