### ISSUE TITLE
onCompleteItem not working

### ISSUE THREAD

**Issue by chrillewoodz** [nervgh/angular-file-upload#571]
I need to access a response value when the file upload of a single file is done, but the callback isn't working. No callbacks that runs after the upload is finished seems to work.. Here is my code:

    var uploader = $scope.uploader = new FileUploader({
		url: '',
		filters: []
	});

    /* Callback straight from the simple example code */
    uploader.onCompleteItem = function(fileItem, response, status, headers) {
		console.info('onCompleteItem', fileItem, response, status, headers);
	};

     videoUploader.uploadSingle = function(video) {

        /* Get the url which we'll be posting the video to */
	    videoApi.new()
		  .then(function(res) {
			
			/* Bind this url to the video and then upload it */
			video.url = res.data.data.form_url;
			uploader.uploadItem(video);
		  })
		  .catch(function(err) {
			statusHandler.setStatus('The server did not respond', false);
	   });
    }

**Comment by wiredlain** [comment]
hi, you need set an endpoint like this

res.end(); in the upload controller.

**Comment by nervgh** [comment]
Looks like this was resolved
