### ISSUE TITLE
Uploading to Amazon S3, image gets there as a corrupted image

### ISSUE THREAD

**Issue by daminufe** [nervgh/angular-file-upload#572]
Hey! I am using pre-signed urls to upload the image.

If I use jquery to do an old school upload, works fine:
```
$.ajax({
    url: signedData.awsUrl,
    type: 'PUT',
    data: file._file,
    processData: false,
    contentType: file._file.type
});
```

If I use angular-file-upload:

`$scope.uploader.uploadAll()`

The image gets corrupted for some reason, and I get this:
![image](https://cloud.githubusercontent.com/assets/4832774/12258043/d4be5e6c-b90b-11e5-9ba0-366ca440e5be.png)

I am not replacing the content of the file in any place.
The only things I am changing, are:
 * `url` to upload
 * `method` to PUT
 * `headers` push `Content-Type` to the one selected by the image.

Any thoughts?

**Comment by nick-bogdanov** [comment]
The problem is that amazon doesn't accept Content-Type:multipart/form-data; Which this module is send.
http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html#d0e25179
You need to set one of this types
Type: String
Default: binary/octet-stream
Valid Values: MIME types
Constraints: None
Content-Encoding

In you case this is MIME types.

**Comment by daminufe** [comment]
Yes, I don't know how to make `angular-file-upload` to use the correct headers.

**Comment by maurycyg** [comment]
Do it in afteraddingitem

```
.bind('afteraddingfile', function (event, item) {
            item.headers['Content-type'] = 'binary/octet-stream';
}
```

**Comment by daminufe** [comment]
Yes @maurycyg I tried the `scope.uploader.onAfterAddingFile()` but didn't work...
Also I don't want to do it when I create the instance, because I never know what's the content type for each file.

**Comment by maurycyg** [comment]
Can you post your code, how did you tried to do it? Have you checked the request headers in developer tools to confirm it didn't work?

**Comment by geeves** [comment]
I have not had problems with S3, the main issue I had was updating the formData correctly to include the key (file name/ path), signature, policy, etc.  Like maurycyg, I updated the formData on the fly, however I used the the fileItem.file.type as the "Content-Type"

`uploader.onAfterAddingFile = function (fileItem) {

            var uuid = UUIDFactory.optimized();
            $scope.formData.key = AssetFactory.getAmazonWebService().key + "" + uuid + "/" + fileItem.file.name;

            var key = {"key" : $scope.formData.key};
            var policy = {"policy" : AssetFactory.getAmazonWebService().policy};
            var signature = {"signature" : AssetFactory.getAmazonWebService().signature};
            var AWSAccessKeyId = {"AWSAccessKeyId" : AssetFactory.getAmazonWebService().awsAccessKey};
            var acl = {"acl" : "private"};
            var content_type = {"Content-Type" : fileItem.file.type};

            fileItem.formData = [key, policy, signature, AWSAccessKeyId, acl, content_type];

            //console.log(fileItem.formData);
            fileItem.url = AssetFactory.getAmazonWebService().awsUploadUrl;

        }`

**Comment by josencv** [comment]
I don't think there is a builtin way to this yet. The XMLHttpRequest object sends a FormData object, which "enforces" the request to be multipart. Truth is, the XMLHttpRequest accepts File and Blobs objects as well.

What you can do is to fork the repository and change the code yourself. Look for:

```javascript
xhr.send(form);
```

that is in the _xhrTransport in the FileUploader service. You have to change (or do whatever you like) it for:

```javascript
xhr.send(item.file);
```

I tested it and it works perfect with Amazon S3.

Cheers

PD: careful with the browser compatibility. You can check it [here](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#Browser_compatibility)

**Comment by josencv** [comment]
I made a pull request (#602) that provides a built in way to do this. Check it out.

**Comment by nervgh** [comment]
done since `>=2.3.x`
