### ISSUE TITLE
IE9 XSRF token

### ISSUE THREAD

**Issue by bhuranideepak82** [nervgh/angular-file-upload#573]
I am able to pass token in IE10 and above and chrome as below 

  that.uploader = that.scope.uploader = new that.FileUploader({
            url: that.scope.uploadUrl,
            headers: {
                'TokenHash': that.xsrfToken
            }
        });

but this does not work in IE9.

I see we are not setting request headers in case of "_iframeTransport"

Any help?

**Comment by nervgh** [comment]
Is there a possible to set headers via IFrame?
http://stackoverflow.com/questions/13432821/is-it-possible-to-add-request-headers-to-an-iframe-src-request
I has updated the [Browser compatibility](https://github.com/nervgh/angular-file-upload/blob/master/README.md#) table.
