### ISSUE TITLE
Passing Array in form data not working

### ISSUE THREAD

**Issue by niharika88** [nervgh/angular-file-upload#578]
i,m trying to post form data with key containing a array it seems that it posts that array as string.

**Comment by mrpmorris** [comment]
Iterate through each value in the array and do this for each value

item.formData.push({
  yourKey: thatValue });

**Comment by nervgh** [comment]
@niharika88 ... or you could use [spread operator](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Spread_operator)
```
item.formData.push(...yourArray);
```

**Comment by niharika88** [comment]
Thanks for the quick response, but for me it still doesn't seems to work as I am sending an array in side my key in the form data for eg:
sampleFeedback : {
Samplecategory: "ABC"
description: "test"
email: "sample@gmail.com"
order_ids: Array[3]
sub_category: "I want to know my order delivery status"
subject: "I want to know my order delivery status"
}
After post the Order_ids get posted as comma separated string .
I want to resolve this issue.
