### ISSUE TITLE
is there any upper limit of the size of file that can be uploaded 

### ISSUE THREAD

**Issue by deepakrjit** [nervgh/angular-file-upload#579]
Hi ,

i have to upload file up to 2 gb i am using anguler file upload in the front end  i am getting   ERR_CONNECTION_RESET

**Comment by dhruvdutt** [comment]
You can use max-size filters.
```
uploader.filters.push(function (item) {
    return item.file.size <= 1048576; // 1024 * 1024 | Math.pow(2,20); | 0x100000
});
```

**Comment by nervgh** [comment]
@dhruvdutt :+1:

**Comment by Vishnupriya112** [comment]
How do I show error to the user  If my file is above the max size?
