### ISSUE TITLE
When adding a file and removing. Can't choose it again

### ISSUE THREAD

**Issue by arsu-leo** [nervgh/angular-file-upload#581]
If you use a single file input, choose a file and then remove the item from the queue, you can't choose the same file again since the input still have the removed file as value and queue add wont be triggered.

**Comment by arsu-leo** [comment]
Simply the file chooser never get's it's value removed, even after the file get uploaded. In consequence you cant ever add to the queue the same file twice if you dont change it in between by other file

**Comment by chiccomotta** [comment]
Hi, I have the same problem. How can I resolve this issue? 
Thanks in advice.

**Comment by nevech** [comment]
Hi! To resolve this problem, after remove the item from the queue need clear the value of input .

Example:
```html
<input id="my-file" type="file" />
```

```js
document.getElementById('my-file').value = ""
```

**Comment by dhruvdutt** [comment]
@nevech 
Thank you very much.

**Comment by apenman** [comment]
Ran into the same issue and clearing the input value after removing the item solved this for me.

For reference: Only ran into the issue in Chrome and not in Firefox. Value in Chrome was "C:\fakepath\my-file.docx" (path actually was set "fakepath" from somewhere) while for Firefox was just "my-file.docx". Not sure if this affects things but noting here if anything is added to have this built in

**Comment by vinogradov** [comment]
This question was already answered in FAQ: https://github.com/nervgh/angular-file-upload/wiki/FAQ#4-no-file-chosen-or-re-add-same-file

**Comment by nervgh** [comment]
See also #584

**Comment by gerome0123** [comment]
@vinogradov can you give an example for that FAQ T_T

**Comment by vinogradov** [comment]
@gerome0123 aren't you satisfied with the example given there?

**Comment by gerome0123** [comment]
@vinogradov thanks for the reply i dont get it why he use {FileUploader} im using uploader = "uploader" i'm try to achieve to select the uploaded file in the server then when i want the result of the save data in the input file. http://stackoverflow.com/questions/43115686/angular-file-upload-how-to-change-uploaded-file-in-the-sever

**Comment by bhaidar** [comment]
I am using this component in an Angular 4 application. Where shall I change the function as the FAQ says?

All the code in my app is TypeScript, so I am not sure where to fix this function to return true.

`/**
             * If returns "true" then HTMLInputElement will be cleared
             * @returns {Boolean}
             */
            FileSelect.prototype.isEmptyAfterSelection = function() {
                return !!this.element.attr('multiple');
            };`

**Comment by nervgh** [comment]
@bhaidar Are you sure that Angular4 is compatible with AngularJS(1) modules?

**Comment by bhaidar** [comment]
@nervgh I am so sorry for posting here. I was looking for the same issue but using ng2fileselect (Angular 4 module). I didn't notice the main project here.

But I was able to fix this issue manually in Angular 4 without the need to change any code.

Thanks
