### ISSUE TITLE
onAfterAddingFile  

### ISSUE THREAD

**Issue by sarae4d** [nervgh/angular-file-upload#586]
Hi,
how can i converting 'fileItem' to base64 string in onAfterAddingFile function.
thanks!

**Comment by nervgh** [comment]
Hi!

You could to add a method to `{FileItem}` class and call that method https://github.com/nervgh/angular-file-upload/wiki/FAQ#5-how-i-can-modify-native-methods-or-add-new-features-to-fileuploader

See also that link https://github.com/nervgh/angular-file-upload/blob/v2.2.0/examples/image-preview/directives.js#L46
