### ISSUE TITLE
Setting URL after creating FileUploader doesn't work

### ISSUE THREAD

**Issue by felipedrumond** [nervgh/angular-file-upload#589]
When creating a FileUploader with 

```
$scope.uploader = new FileUploader({
            headers: {
                SecurityToken: credentials.securityToken
            }
        });

```
and setting the url afterwards with

`$scope.uploader.url = url;`

does not work. I need to change the URL depending on a input <select>.

How to solve this issue?

**Comment by Nephidream** [comment]
Do you already have a file in your uploader queue when you do `$scope.uploader.url = url;`?
If so, for what I understand, setting the url of the uploader doesn't update the url of the pre-existing files in the queue, so you have to manually update them. For example I use a function like this:

```javascript
this.updateUrl = function(url, uploader) {
  uploader.url = url;
  uploader.queue.forEach(function(file) {
    file.url = url;
  });
};
```

**Comment by josencv** [comment]
You can also use a file handler like onAfterAddingFile to set the url:

```javascript
$scope.uploader.onAfterAddingFile = function(item) {
  item.url = url;
}
```

**Comment by nervgh** [comment]
You could use the [`onBeforeUploadItem`](https://github.com/nervgh/angular-file-upload/wiki/Module-API) callback.
Also you could implement the [`setOptions`](https://github.com/nervgh/angular-file-upload/pull/377) method.
