### ISSUE TITLE
Upload input data with files

### ISSUE THREAD

**Issue by grenard01** [nervgh/angular-file-upload#595]
Hello,
I want to do an upload page. I use this sample http://nervgh.github.io/pages/angular-file-upload/examples/simple/ with small customisations and a proper php script for receive the files.
However I am unable to join input field content (ex : "Name : ") in post to my php script.
I have found this code to put in the controller : 
```
 uploader.onBeforeUploadItem = function(item) {
            console.info('onBeforeUploadItem', item);    
			item.formData = [{data: "data"}];
        };
```
And this is my html input
`<input type="text" ng-model="fname"name="fname" id="fname"`

But in php i see "undifined index fname"....
I don't understand what I need to do in the .js

**Comment by JarleJac** [comment]
I solved this by adding my own object to the fileItem in onAfterAddingFile like this:
```javascript
    $scope.uploader.onAfterAddingFile = function(fileItem) {
    	fileItem.myData = {description: ""};
    };
```
And then picking it up again in onBeforeUploadItem 

```javascript
    $scope.uploader.onBeforeUploadItem = function(fileItem) {
    	fileItem.formData.push({description: fileItem.myData.description});
    };
```
In the html you just bind to your own object
`ng-model="item.myData.description"` 
within a `ng-repeat="item in uploader.queue"`

**Comment by yuriyarhipov** [comment]
you can push it in "onAfterAddingFile", it works perfectly 
`fileItem.formData.push({description: fileItem.myData.description});`
