### ISSUE TITLE
How can i change the queue limit dinamically

### ISSUE THREAD

**Issue by felipemendesbraga** [nervgh/angular-file-upload#598]
Hi guys, first of all, sorry for my poor english. 

I do not know how to upload the images from the server in a FileUploader instance to generate and display canvas, so I'm displaying in a `<img ng-src="{{url}}" />`. By definition of the scope, I can have a maximum of 3 images. In this case, I need to control the removal and addition of new images, but for that I would have to change the limit of the queue every time I remove an image already loaded. How do I change this value according to this demand? Do I need to instantiate a new FileUploader every time it happens?

**Comment by nervgh** [comment]
Hello!

@felipemendesbraga , do not worry about your English. You are not one :blush: 
We need post more smiles for understanding each other :laughing: 

The `queueLimit` option is [dynamic already](https://github.com/nervgh/angular-file-upload/blob/master/src/services/FileUploader.js#L341).
