### ISSUE TITLE
upload destination

### ISSUE THREAD

**Issue by bsfahmi** [nervgh/angular-file-upload#600]
where did i put the url of the directory in which i would like to upload my files in ?

**Comment by bsfahmi** [comment]
Hello,
How to upload files not on the server but in another folder in my Disk ?
Thanks

**Comment by nervgh** [comment]
Hello!

Yes, it is possible. Please, check out a guide how to handle the sending of files using your backend code.

Good luck =)

If you are using PHP as the server language, you could look at a [example](https://github.com/nervgh/angular-file-upload/blob/v2.2.0/examples/without-bootstrap/upload.php).

**Comment by bsfahmi** [comment]
Hello Alex,
please how can i add the type of the file that i can upload with
my-drop-zone? i want to upload only xml files so how can i do that ?
Thanks.

2016-02-26 19:08 GMT+01:00 Alex <notifications@github.com>:

**Comment by josencv** [comment]
You can add a filter to your uploader:

```javascript
var uploader = new FileUploader();

function xmlFilter(file) {
  var validMimeTypes = ['application/xml', 'text/xml'];
  if (validMimeTypes.indexOf(file.type) !== -1) {
    return true;
  }
}

uploader.filters.push({name: 'xmlFilter', fn: xmlFilter});
```

And you can add a handler to take action when this filter fails, like this:

```javascript
function onFilterFail(item, filter, options) {
  if (filter.name === 'xmlFilter') {
    // Do something... show a message or whatever
  }
}

// register callback in the uploader
uploader.onWhenAddingFileFailed = onFilterFail;
```

**Comment by bsfahmi** [comment]
Hello Alex,
Thank you very much for your answer but i'm a beginner in javascript and i
didn't understand where can i add this fillter exactly ! in which file and
after what ?
Thanks Alex.

2016-03-01 18:56 GMT+01:00 josencv <notifications@github.com>:

**Comment by nervgh** [comment]
@josencv , thanks! Also I saw your PR on last week. One more thanks =) I'll review your PR more attentively when I will have time for that. Currently, I very busy. Sorry.
