### ISSUE TITLE
angular progress bar using ng-style goes back

### ISSUE THREAD

**Issue by liadlivnat** [nervgh/angular-file-upload#603]
I have issue with ng-style and progress bar

The issue is the progress bar goes back with the animation instead of starting from 0.

I checked the values and it does start from 0, than progress until 100, but the progress looks like it goes back.

Not sure what am i doing wrong,

If you have any idea, please share it with me.

I attached animated gif to show the scenario

and my html code:

```
<div ng-if="item.progress <= 100" class="upload-progress-bar">
<div class="progress-bar" ng-style="{ 'width': item.progress + '%' }"></div>
</div>
```

I attached an image that show what happens:

![animation](https://cloud.githubusercontent.com/assets/2083527/13459308/549348dc-e07b-11e5-970f-07ab216cb681.gif)

if you have any idea how to fix that please help,

i tried everything include printing the values of the progress to the screen, the progress value is correct and set to 0 but the animation goes back.

**Comment by lpsBetty** [comment]
Can you please also show the `ng-repeat`?

**Comment by liadlivnat** [comment]
@lpsBetty i resolved the issue, the problem was that i used "track by $index"
not sure why it caused the issue, but removing it solve that.

Thank you for your reply

**Comment by liangguohun** [comment]
can you tell me how to fix it and make the progress bar show correctly? this don't have the demo of progress bar .
