### ISSUE TITLE
upload only xml files

### ISSUE THREAD

**Issue by bsfahmi** [nervgh/angular-file-upload#604]
Hello,
i want to upload only xml files so for the <input type="file"> i added accept=".xml" but for the drop zone i didn't know how do that !

**Comment by arshtepe** [comment]
https://github.com/nervgh/angular-file-upload/blob/master/examples/image-preview/controllers.js#L19

**Comment by bsfahmi** [comment]
Hello,
I have added this but it doesn't work !
uploader.filters.push({
            name: 'xmlFilter',
            fn: function(item /*{File|FileLikeObject}*/, options) {
                var type = '|' + item.type.slice(item.type.lastIndexOf('/') + 1) + '|';
                return '|xml|'.indexOf(type) !== -1;
            }
        });

**Comment by arshtepe** [comment]
@bsfahmi Please create example, on jsfiddle.net or similar service
