### ISSUE TITLE
Error when removing last item and adding again

### ISSUE THREAD

**Issue by lpsBetty** [nervgh/angular-file-upload#605]
I got the following error when removing all items from a queue, and than adding an item again.
It is not possible to add any item :( 
````
Uncaught TypeError: Cannot read property 'length' of undefined
i.addToQueue.value	@	FileUploader.js:60
i.onChange.value	@	FileSelect.js:67
````

I am using the latest version 2.2.0..

**Comment by arshtepe** [comment]
@lpsBetty  Are you can create demo, on jsfiddle.net or similar service?

**Comment by lpsBetty** [comment]
I am so sorry, I added a custom validator directive that caused this problem ..

`<input class="hidden" ng-model="uploader.queue" validate-length />`

I am closing this issue again ;)
