### ISSUE TITLE
<input multiple  /> only fires once in 2.2.0, works fine in 2.1.3

### ISSUE THREAD

**Issue by MarcusRiemer** [nervgh/angular-file-upload#606]
I basicly copied over the simple example to my machine and was puzzled, that I could only select files from the "multiple" input element once. The first time I selected the files they were put into the transfer queue, all subsequent times they were "left" in the element.

![screenshot_20160304_135954](https://cloud.githubusercontent.com/assets/2138773/13527725/7b5b4612-e211-11e5-818c-55d010a9eed8.png)

After the initial selection no further example events were fired:

    uploader Object { url: "api/photoUpload.php", alias: "file", headers: Object, queue: Array[0], progress: 0, autoUpload: false, removeAfterUpload: false, method: "POST", filters: Array[2], formData: Array[0], 17 more… } page-angular.js:358:3
    onAfterAddingFile Object { url: "api/photoUpload.php", alias: "file", headers: Object, formData: Array[0], removeAfterUpload: false, withCredentials: false, method: "POST", uploader: Object, file: Object, isReady: false, 9 more… } page-angular.js:328:5
    onAfterAddingAll Array [ Object ]

I then checked which version ran the samples, downgraded to 2.1.3 locally, and it immediatly worked. I observed this behaviour using `Mozilla Firefox 44.0.2` and `Chromium 48.0.2564.116` on Arch Linux.

**Comment by GodzillaHe** [comment]
I have the same problem. The demo on the website is based on v2.1.3.

**Comment by henritoivar** [comment]
+1

**Comment by erictvalverde** [comment]
+1

**Comment by hansih91** [comment]
+1

**Comment by GodzillaHe** [comment]
Maybe we should find a another upload widget

**Comment by itamair** [comment]
+1

**Comment by sWW26** [comment]
Appears to be a side effect of commit #512

**Comment by tbasallo** [comment]
Confirming #512 is causing the issue. Commenting out the "IE fix" allows additional files to be added again.

**Comment by riteshjagga** [comment]
+1

**Comment by ronlv10** [comment]
+1

**Comment by hossam9995** [comment]
+1

**Comment by nervgh** [comment]
Did you try the `v2.3.1` version?

**Comment by nervgh** [comment]
I have Ubuntu 15.10, Chromium Browser 49.0.2623.108, angular 1.1.5 and angular-file-upload v2.3.1. Looks like it works fine. See a [video](https://drive.google.com/open?id=0B2CP8LcWJSNSREM5S1RROFlfNVE).

**Comment by nervgh** [comment]
If the issue still exists, please try #584 PR and leave comment about it here.

**Comment by tommarien** [comment]
I can confirm that this is still broken in version 2.3.3, rolling back to 2.1.3 works. i do think that pr #584 could be a possible fix

**Comment by BramDecuypere** [comment]
+1

**Comment by nervgh** [comment]
Please, try `v2.3.4`
