### ISSUE TITLE
Source maps in releases

### ISSUE THREAD

**Issue by cfoehrdes** [nervgh/angular-file-upload#611]
I was wondering why you ship your dist version with source maps. Would it be possible to remove them at least from the minified releases. It doesn't really make sense to have source maps in production code, which is the case if you install your library via bower.

**Comment by nervgh** [comment]
1. People could install this library via Bower not only for the production.
2. For debugging in production :smile: Browsers will download and use source maps only when a developer will open devtools (as I know)
3. Many popular libraries use same approach
4. You could block source maps on your server using its settings.

Thank you for the question
