### ISSUE TITLE
怎么实现单图片上传？

### ISSUE THREAD

**Issue by ggg2537** [nervgh/angular-file-upload#623]
弄一晚上实在整不出来啊。

**Comment by nervgh** [comment]
медведь матрешка водка балалайка :laughing:

**Comment by poc7667** [comment]
@nervgh he said, how could he upload only one image instead of multiple images, @ggg2537  我幫你翻譯了

**Comment by ggg2537** [comment]
666 咋背的单词 这么顺 我就英语不行。 @poc7667

**Comment by poc7667** [comment]
@ggg2537  沒事～～就多看就會了。 希望你能趕快找到解答。

**Comment by poc7667** [comment]
@ggg2537  幫你找了一下，你去參數改成 queueLimit 1 應該就能了

**Comment by ggg2537** [comment]
你不会用英语找的吧。。  我这个弄完了 添加一个的时候把之前的给删了。。哈哈 @poc7667

**Comment by nervgh** [comment]
wow

@ggg2537 I think we have to use English for communication between each other :v: In another case I do not understand your native language and you don't understand mine.
