### ISSUE TITLE
Can upload be done without php? is there an example showing how to do this in .net?

### ISSUE THREAD

**Issue by ezmani** [nervgh/angular-file-upload#628]
Can upload be done without php?

**Comment by nervgh** [comment]
Yes. You could use any back-end language.

[ruby](https://github.com/nervgh/angular-file-upload/issues?utf8=%E2%9C%93&q=ruby)
[node.js](https://github.com/nervgh/angular-file-upload/issues?utf8=%E2%9C%93&q=node.js)
[java](https://github.com/nervgh/angular-file-upload/issues?utf8=%E2%9C%93&q=java)
[.net](https://github.com/nervgh/angular-file-upload/issues?utf8=✓&q=.net)
