### ISSUE TITLE
Image Preview doesn't work on safari 5.1.7 

### ISSUE THREAD

**Issue by krishanchopra** [nervgh/angular-file-upload#629]
![image](https://cloud.githubusercontent.com/assets/11444184/15099509/28022d90-1525-11e6-8ae9-6388dc7631ad.png)

Testing URL http://nervgh.github.io/pages/angular-file-upload/examples/image-preview/

We used the uploader on our project and it works on all browsers, except Safari for Windows 5.1.7... When I select image it added image in array but No Image Preview.

**Comment by nervgh** [comment]
@krishanchopra It looks like Safari for Win does not support an image preview via canvas https://github.com/nervgh/angular-file-upload/blob/v2.2.0/examples/image-preview/directives.js#L21

**Comment by krishanchopra** [comment]
@nervgh Thank you for your quick response. Yes Safari for Win does not support an image preview via canvas, SO is there any solution for this issue ?

**Comment by nervgh** [comment]
You could use something like [that](https://www.google.ru/search?q=no+preview+available&newwindow=1&tbm=isch).

**Comment by krishanchopra** [comment]
Ok, Thank You
