### ISSUE TITLE
Angular dependency injection broken in minified files

### ISSUE THREAD

**Issue by josencv** [nervgh/angular-file-upload#631]
The issue is very straighforward. The angular dependencies are broken in the minified version of the library (v2.2.3).

I investigated a little and it looks like **this is not a problem of the uglifier webpack plugin**.

The problems lies in convertion from ES6 to ES5, that is, babel iseltf. From version 6.0 and above the code:

```es6
export default (args) => {
 ...
}
```

transforms into:

```javascript
exports.default = function (args) {
  ...
}
```

instead of:

```javascript
module.exports = function (args) {
  ...
}
```

The angular modules injection are explicit, but they are using common js module syntax:

```javascript
module.exports.$inject = ['args'];
```

So the dependencies are being injected to a wrong target, causing the whole problem.

The solution involves a change in the design of the whole module, so I think @nervgh should decide how to solve this.

[This article](https://medium.com/@kentcdodds/misunderstanding-es6-modules-upgrading-babel-tears-and-a-solution-ad2d5ab93ce0#.omvb10jep) explains in depth the problem and the posible solutions.

**Comment by nervgh** [comment]
@josencv thanks! Fixed in [v2.3.1](https://github.com/nervgh/angular-file-upload/releases/tag/v2.3.1) :smile:

**Comment by josencv** [comment]
Thanks for the quick fix. Now works without problems.

**Comment by nervgh** [comment]
You are welcome! Thank you for the informative issue!
