### ISSUE TITLE
File Upload Broken in IE9,  v2.3.1

### ISSUE THREAD

**Issue by Hypopheralcus** [nervgh/angular-file-upload#633]
Hi,

I use your awesome angular file upload. In Version 2.3.1 the support for Internet Explorer Version 9 is broken. I hope you will not drop the Support for old browsers.

I made as little exemple: [https://plnkr.co/edit/ZZz10IZg1dRcZMZctp9V?p=preview](https://plnkr.co/edit/ZZz10IZg1dRcZMZctp9V?p=preview)

Version 2.1.3 is working.

**Comment by nervgh** [comment]
Please, try #584 PR. Does #584 resolve this issue?

**Comment by Hypopheralcus** [comment]
Unfortunately the fix #584 is not working for this issues. It looks like that the method `_possibleConstructorReturn` in the FileSelect returns a wrong result. `this.uploader` is null after this call.

**Comment by josencv** [comment]
I think this issue may be related to the version of Babel used in the latest version of the package. @nervgh read [this](https://github.com/babel/babelify/issues/133).

**Comment by nervgh** [comment]
@josencv , thank you for the helpful comment :+1: 

@Hypopheralcus , try `v2.3.2`

**Comment by Hypopheralcus** [comment]
@nervgh Thank you. it's working.
