### ISSUE TITLE
Uploading multiple images and form data with one http request

### ISSUE THREAD

**Issue by nargeszmn** [nervgh/angular-file-upload#634]
Is there any way to submit the whole form data and multiple dropped images with one xhr request?

I can see angular-file-upload is posting each file item in the queue with one POST request, while what I want is to post all files and form data with only one http POST.
At the moment, my creation form is submitting many times and as a result, my model is creating many times instead of one time.

**Comment by potray** [comment]
When I need to do that I add the form data to item.formData[0], and in the server it's automatically in the req.body.

**Comment by dedegkaev** [comment]
I also interested in this issue! Urgently!

**Comment by forest90** [comment]
https://github.com/danialfarid/ng-file-upload this one do this. Whole point is that it can easly estimate time of upload. You can store files in session, I do that. Clear on leave or save on submitt

**Comment by nervgh** [comment]
@nargeszmn , you could create two server actions and do something like this:
1. `/create-and-save-model`. Request is your model data. Response is new-model-id
2. `/ulpoad-image-by-model-id`. Request is an image with id from previous response

**Comment by forest90** [comment]
what about addToQueue method and uploadAll ?
These are posting all files separate?

**Comment by nervgh** [comment]
> These are posting all files separate?

Yes, one by one

I think this feature may be implemented in `>=3.0.0` when IE <=10 will not be supported.

**Comment by ggunders** [comment]
need this as well

**Comment by kepoly** [comment]
Any solutions for this? Really like this module but don't want to hack it into single xhr.

**Comment by jpierson** [comment]
Why was this issue closed, is support no longer planned for a later release?

**Comment by kepoly** [comment]
@jpierson I still use this module for other applications but where I needed the single xhr I ended up going with https://github.com/danialfarid/ng-file-upload
