### ISSUE TITLE
Importing in ES6 syntax

### ISSUE THREAD

**Issue by bradmaxs** [nervgh/angular-file-upload#635]
Hello,

I am trying to import this into my main app.js file with the ES6 import syntax but nothing that I have tried has worked.

I have tried:

```es6
import angularFileUpload from '../../node_modules/angular-file-upload/dist/angular-file-upload.js';
import { angularFileUpload } from '../../node_modules/angular-file-upload/dist/angular-file-upload.js';
import { default as angularFileUpload } from '../../node_modules/angular-file-upload/dist/angular-file-upload.js';
```

I have also tried the above with just 'angular-file-upload' instead of the path to the dist folder and no luck.

Every import statement above seems to load the library because if I put it before angular it throws an "angular is not defined' error however when I console.log(angularFileUpload), I get an empty object.

When I try and include it as a dependency in my main module...

```javascript
angular.module('app', [
    angularFileUpload
])
.config(config)
.component('app', appComponent);
```

I get...

Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module {} due to:
Error: [ng:areq] Argument 'module' is not a function, got Object

I am using:

Weback v1.1.13
Angular v1.5.3

Thanks for your help

**Comment by bradmaxs** [comment]
All I had to do was...

import 'angular-file-upload';

Then wrap it in single quotes and viola.

**Comment by nervgh** [comment]
If you installing modules via npm, try this
```js
import angularFileUpload from 'angular-file-upload';
```

**Comment by bradmaxs** [comment]
That worked as well, thank you!

**Comment by casoetan** [comment]
```js
import angularFileUpload from 'angular-file-upload'; 
```
This did not work for me either. Using Webpack

**Comment by Arkanine** [comment]
The same thing, can't import this module using webpack.

**Comment by nuflowx** [comment]
If you look in the source there are no `exports`, therefor `import ... from 'angular-file-upload'` does not work. As mentioned above `import 'angular-file-upload'` (without from) works nicely
