### ISSUE TITLE
what do i put in url ?

### ISSUE THREAD

**Issue by Jefferson210** [nervgh/angular-file-upload#636]
I put in irl this url:'/api/v1/articles/:id', but i get this error
No route matches [POST] "/api/v1/articles/:id"

excuse me i am learning.

**Comment by josencv** [comment]
What are you using on the server side? That looks like a common Rails routing error.

**Comment by Jefferson210** [comment]
yes, i use Rails in the server side..

**Comment by josencv** [comment]
The uploader is not the problem. The uploader is making a POST request to /api/v1/articles/:id, and it looks that Rails detects it, but as the error says, no route matches the url you requested (Note: the http method DOES matter. A GET request and a POST requested to the same url are different routes). Google about Rails routing.

**Comment by Jefferson210** [comment]
ok, maybe do yo have any example??

**Comment by josencv** [comment]
Sorry I don't have any examples of Rails code.

There are a lot of tutorials about Rails routing out there. I'm closing this issue.

**Comment by gerome0123** [comment]
@Jefferson210 did you solve this?
