### ISSUE TITLE
how to detect 302 response header

### ISSUE THREAD

**Issue by Honwhy** [nervgh/angular-file-upload#638]
when user session is invalid, I failed to submit the uploading as expected,
which owed to my backend server had responsed with `HTTP 302` (something) , but the following code
```
uploader.onErrorItem = function (fileItem, response, status, headers) {
  console.info('onErrorItem', fileItem, response, status, headers);
};
```
can't find any `302` information from any variable among `fileItem`, `response`, `status` and `headers` in the callback function of `uploader.onErrorImtem`.

At the moment, I am thinking about hacking `fileItem` object, rewrite fileItem._xhr.onerror callback function(_xhr  is a XMLHttpRequest instance), but I have not got any result yet. 
Thanks.

**Comment by Honwhy** [comment]
my debug result:
different result at these code:

```
xhr.onload = function() {
	var headers = that._parseHeaders(xhr.getAllResponseHeaders()); // 200
	var response = that._transformResponse(xhr.response, headers);
	var gist = that._isSuccessCode(xhr.status) ? 'Success' : 'Error';
	var method = '_on' + gist + 'Item';
	that[method](item, response, xhr.status, headers);
	that._onCompleteItem(item, response, xhr.status, headers);
};

xhr.onerror = function() {
	var headers = that._parseHeaders(xhr.getAllResponseHeaders()); //302
	console.log(xhr);
	console.log(headers);
	var response = that._transformResponse(xhr.response, headers);
	that._onErrorItem(item, response, xhr.status, headers);
	that._onCompleteItem(item, response, xhr.status, headers);
};
```
when faces 302:
```
xhr.getAllResponseHeaders()  is empty
xhr.status equals 0
```
when face 200:
```
xhr.getAllResponseHeaders()  like
Date: Thu, 26 May 2016 10:17:16 GMT
Server: Apache-Coyote/1.1
Transfer-Encoding: chunked
Content-Type: application/json;charset=UTF-8

xhr.status equals 200
```

**Comment by Honwhy** [comment]
I figured out it is a feature of browser.
see code [ajax302](https://gist.github.com/Honwhy/39aff538c1c5019198737d6ac198b46e)
run with node,
visit `http://localhost:9000/`, click `send` button, will see `0` alert.

**Comment by nervgh** [comment]
If your issue was solved, please close this issue.

**Comment by gerome0123** [comment]
@Honwhy my i ask how you figure this out??
