### ISSUE TITLE
Send data in body POST along with file

### ISSUE THREAD

**Issue by Nosthertus** [nervgh/angular-file-upload#641]
I have been trying to send form data along with file on method POST.. for a moment i thought it has to be set in `formData`.. so i tried this:

```Javascript
$scope.uploader = new $uploader({
	queueLimit: 1,
	url: $HOST.REST + '/upload/picture?access_token=' + $user.getToken(),
	formData: [{
		accountId: $user.getId()
	}]
});
```
but server gets the body as undefined.. is there something i am missing here?

**Comment by Nosthertus** [comment]
Just found out the server has no method to gather form data along with files

**Comment by Nosthertus** [comment]
I ended up making my own module for uploading files which also allows me to pass formData. Maybe what i did was wrong. But noone has prooved it otherwise so far

**Comment by v29neil** [comment]
@Nosthertus  I tried sending formdata using your example. 
It works.

**Comment by Nosthertus** [comment]
@v29neil I'm glad it worked for you, that's great news for me
