### ISSUE TITLE
Using multiple uploaders on same page

### ISSUE THREAD

**Issue by celsomtrindade** [nervgh/angular-file-upload#642]
I have a page with a list of products, on each product I have an uploader to send 1 image per product.

How can I use one single uploader to all of the products on the page? Currently, If I send 1 image on one product, all of the others uploaders start the process and I need to wait for it to finish and then continue. 

With this problem, I'm also not able to show the progress bar for that specific product, since it appear in all the items on the page.

This is my declaration:

    <div class="product" ng-repeat="product in vm.productList track by product.id">
        <div class="upload" ng-if="!produto.pro_img" nv-file-drop nv-file-over options="{formData: product.id}" uploader="vm.imgUploader">
            <h4 ng-if="!vm.imgUploader.queue[0].isUploading">Drop image here</h4>

            <div class="progress" ng-if="vm.imgUploader.queue[0].isUploading">
                <p><i class="fa fa-spinner fa-pulse"></i> {{vm.imgUploader.queue[0].progress}}</p>
            </div>
        </div>
    </div>

Is there a way to achieve this result?

> Note: All the uploading functions are working as expected. But instead of animate the progress just on the product I'm uploading an image, it's show the progress bar in all of the items on the `ng-repeat`

**Comment by nervgh** [comment]
Could you make an example in any sandbox?
https://jsfiddle.net/ 
https://plnkr.co/
...

**Comment by celsomtrindade** [comment]
https://plnkr.co/edit/SSykni3Co5v0iUv3FyP7?p=preview

As you can see on this example, when you try to upload one file in one of those 5 boxes, all of them are triggered at the same time. I'd like to know if it's possible to have a grid like this but use the same uploader for each of them separately.

**Comment by celsomtrindade** [comment]
@nervgh Here is the example: https://plnkr.co/edit/SSykni3Co5v0iUv3FyP7?p=preview

As you can see on this example, when you try to upload one file in one of those 5 boxes, all of them are triggered at the same time. I'd like to know if it's possible to have a grid like this but use the same uploader for each of them separately.

**Comment by KGBill** [comment]
Is there an answer to this ? I'm having the same problem. I tried setting options with the uploader index but so far I havent been able to retreive it in my events.

**Comment by nervgh** [comment]
@celsomtrindade 

> How can I use one single uploader to all of the products on the page?

An [example](https://plnkr.co/edit/h69SRXkRjMFiDa3t0fd6?p=preview) which handling a single file. You need handle a situation when user drops multiple files at once.

https://github.com/nervgh/angular-file-upload/wiki/FAQ#3-i-need-custom-options-are-there-any
https://github.com/nervgh/angular-file-upload/wiki/Module-API#directives
