### ISSUE TITLE
How to see error messages from uploader?

### ISSUE THREAD

**Issue by samazary** [nervgh/angular-file-upload#648]
HI when i add a file to the queue and click upload all, the uploader respond with isError:true (see below from the console output), however how do I see what the actual error message is? 

Is there an error message property I can log to the console to see this?

**onBeforeUploadItem** 
n {url: "http://myurlhere.com/apiMethod.json", alias: "file", headers: Object, formData: Array[0], removeAfterUpload: false…}
$$hashKey:"object:510"
_file:File
_input:null
_xhr:XMLHttpRequest
alias:"file"
file:e
formData:Array[0]
headers:Object
index:null
isCancel:false
isError:true
isReady:false
isSuccess:false
isUploaded:true
isUploading:false
method:"POST"
progress:0
removeAfterUpload:false
uploader:r
url:"http://myurlhere.com/apiMethod.json"
withCredentials:false
__proto__:Object

**Comment by nervgh** [comment]
Do you use the latest version of this module? If not, try to update it. See also [that](https://github.com/nervgh/angular-file-upload/blob/master/src/services/FileItem.js#L134)

---

> Is there an error message property I can log to the console to see this?

https://github.com/nervgh/angular-file-upload/blob/v2.3.4/examples/simple/controllers.js#L47
https://github.com/nervgh/angular-file-upload/blob/master/src/services/FileUploader.js#L482
