### ISSUE TITLE
change file problem

### ISSUE THREAD

**Issue by rqx110** [nervgh/angular-file-upload#649]
follow step:
1. config the upload: queueLimit=1,autoUpload=false
2. select file "1.png" (have not upload yet)
3. select file "2.png" (that is what i want to upload)
4. upload the select file. It's strange that the uploaded file is "1.png" not the "2.png"

Is it a bug? or not please give me a solution.

**Comment by nervgh** [comment]
Insert these lines into your code for undestanding
```js
uploader.onWhenAddingFileFailed = function(item /*{File|FileLikeObject}*/, filter, options) {
    console.info('onWhenAddingFileFailed', item, filter, options);
};
uploader.onAfterAddingFile = function(fileItem) {
    console.info('onAfterAddingFile', fileItem);
};
```
https://github.com/nervgh/angular-file-upload/blob/v2.3.4/examples/simple/controllers.js#L26

See also https://github.com/nervgh/angular-file-upload/wiki/FAQ#4-no-file-chosen-or-re-add-same-file

**Comment by Velius5** [comment]
I had the same problem with single file uploading.
My solution:
```
uploader.onWhenAddingFileFailed  = function(item, filter, options) {
	uploader.clearQueue();
	uploader.addToQueue(item);
}
```

**Comment by CodemonkeyTim** [comment]
I had the same problem and tried the solution bu Velius5. Unfortunately it didn't work with canvas image preview so what I ended up doing was removing the queueLimit filter and adding this event callback:

`uploader.onAfterAddingFile = function(item, filter, options) {
   if (uploader.queue.length > 1) {
      uploader.queue.splice(0, 1);
    }
};`

**Comment by arrowing** [comment]
@Velius5 I just use same solution.
But it doesn't work at fact.
Because the item variable is FileItem, not {FileList|File|HTMLInputElement}.
But the "addToQueue" method need {FileList|File|HTMLInputElement} type.
So it doesn't work when I upload. Some data from file are lost.

**Comment by arrowing** [comment]
@CodemonkeyTim Nice job!

**Comment by gerome0123** [comment]
@Velius5 i try your solution but i got rollback in my server file_fingerprint is NULL
