### ISSUE TITLE
How to get uploaded file path

### ISSUE THREAD

**Issue by misty256** [nervgh/angular-file-upload#651]
Hi,
can someone suggest me how can I retrieve the uploaded file path? I mean the path were the file is stored on the disk. Like "c:/myImages/image.jpg".

Regards,
 misty

**Comment by nervgh** [comment]
> You cannot do so - the browser will not allow this because of security concerns

http://stackoverflow.com/a/15201184

**Comment by misty256** [comment]
Thanks for the answer. But isn't it allowed in a standalone javascript app?

Regards

**Comment by josencv** [comment]
As @nervgh, this is not possible to do in modern browsers for security concerns.

See http://stackoverflow.com/questions/15201071/how-to-get-full-path-of-selected-file-on-change-of-input-type-file-using-jav

I don't know what you mean by standalone javascript app. Javascript code have to run somewhere (node server, browser, etc). If your app runs in a browser, then no, it is no possible.

**Comment by misty256** [comment]
Hi,
you can also run it as a standalone app. Take a look at electron: http://electron.atom.io/
I can achieve my goal using html5 and its "File". But I was wondering if it would be possible to get the file's path using this uploader as it's very nice.

Regards,
 misty

**Comment by nervgh** [comment]
> Take a look at electron: http://electron.atom.io/

...node-webkit, cordova and so on.

You could build your app and test the feature that you interesting.
But I think the answer is "no".

Use the google search and will happy https://github.com/electron/electron/issues/1683

**Comment by misty256** [comment]
html5 "file" works as expected. I've already tested it.
Anyway I was able to get the path also using this uploader:

image._file.path

where "image" is the object taken from the queue.
Great :)

Regards and thanks for all replies,
 misty
