### ISSUE TITLE
clear the input content after clearing the queue

### ISSUE THREAD

**Issue by nhack** [nervgh/angular-file-upload#652]
I would like that the input value is cleared (so that I see "No file chosen") after the queue is cleared (`uploader.clearQueue()`), right now the name of the uploaded file still appears and I have to do something like `$('.fileInput).val(null)`

**Comment by nervgh** [comment]
See https://github.com/nervgh/angular-file-upload/wiki/FAQ#4-no-file-chosen-or-re-add-same-file

**Comment by gerome0123** [comment]
i dont get this FAQ T_T
