### ISSUE TITLE
adding multi-dimension array to formData

### ISSUE THREAD

**Issue by obana1990** [nervgh/angular-file-upload#653]
I'm uploading to a PHP server but I want to append additional data to formData so I could access it through $_POST.

Here's the data that I would like to pass to formData:

var data = [{label:'lb1',name:'name1'},{label:'lbl2',name:'name2'},{label:'lbl3',name:'name3'}];

I want it to end up exactly like the structure below 

$_POST['entities'] = array(
0=>array(
          "label"=>"lbl1",
          "name"=>"name1"
    ),
1=>array(
          "label"=>"lbl2",
          "name"=>"name2"
   ),
2=>array(
          "label"=>"lbl3",
          "name"=>"name3"
    )
);

I tried serializing it and passing the entire javascript array object into formData but couldn't get the result I want.

encoding in JSON format is not an option here..

**Comment by nervgh** [comment]
Please, see same issue #658

**Comment by obana1990** [comment]
I know that's one way to do things but I did mentioned "encoding in JSON format is not an option here.."
Anyway, I will ask the back-end developer to parse my request in JSON...

**Comment by alecha** [comment]
why is the usual FormData interface not supported? :/
