### ISSUE TITLE
Not raising on upload error

### ISSUE THREAD

**Issue by alvaromlg** [nervgh/angular-file-upload#654]
I have noticed in this code:

```
        /**********************
         * PUBLIC
         **********************/
        /**
         * Uploads a FileItem
         */
        upload() {
            try {
                this.uploader.uploadItem(this);
            } catch(e) {
                this.uploader._onCompleteItem(this, '', 0, []);
                this.uploader._onErrorItem(this, '', 0, []);
            }
        }
```

The 'e' i ncatch is not being provided to onErrorItem and not being raised. So in Angular you just received blank "" response, status 0, and arguments [] and not idea what's going on.

In my case I had a "TypeError: Cannot read property '_prepareToUploading' of undefined(…)" but I had do unminify the code and debug it in order to figure it out...

Is that intended for any reason?

**Comment by nervgh** [comment]
> Is that intended for any reason?

Looks like there is not reasons for that.
PR welcome! =)

**Comment by mhamdy88** [comment]
@nervgh  I see this issue is already solved, plz remove cw label and close it.

**Comment by nervgh** [comment]
@mhamdy88 thanks!

**Comment by dmlgncn** [comment]
how did resolve this issue?
