### ISSUE TITLE
Is there a way to change the style of the "Choose file" button?

### ISSUE THREAD

**Issue by cmacdonnacha** [nervgh/angular-file-upload#655]
Just wondering if there a way to change the style of the "Choose file" button?

![image](https://cloud.githubusercontent.com/assets/9777763/16997670/56f572d4-4eae-11e6-9070-f192557c7909.png)

**Comment by isidorob** [comment]
YES!

#hide input[type=file] {
	display:none; 
	margin:10px;
}
#hide input[type=file] + label {
	display:inline-block;
	margin:20px;
	padding: 4px 32px;
	background-color: #FFFFFF;
	border:solid 1px #666F77;
	border-radius: 6px;
	color:#666F77;
}
#hide input[type=file]:active + label { 
   background-image: none;
	background-color:#2D6C7A;
	color:#FFFFFF;
}

This is an example, you hide the original button and replace it for a label and give it a style.
Just on html put an input file and right next put a label with the name "BROWSE" or "UPLOAD" and see how it works!!
Take your own CSS style!
Good Luck

**Comment by nervgh** [comment]
See https://github.com/nervgh/angular-file-upload/issues/549#issuecomment-158019523

**Comment by cmacdonnacha** [comment]
Perfect thanks!

**Comment by vb93** [comment]
Thanks. CSS did the trick. Works great !

**Comment by diffiehellman64** [comment]
Thanks for Idea!

And it`s my bootstrap 3 example

CSS

```
#upload_button {
  display: inline-block;
}
#upload_button input[type=file] {
  display:none;
}
```

HTML
```
  <div id="upload_button">
    <label>
      <input type="file" ngf-select ng-model="new_files" ng-change="fs.uploadFiles(new_files)" multiple>
      <span class="btn btn-primary">Upload files</span>
    </label>
  </div>
```

**Comment by amirdy** [comment]
> Thanks for Idea!
> 
> And it`s my bootstrap 3 example
> 
> CSS
> 
> ```
> #upload_button {
>   display: inline-block;
> }
> #upload_button input[type=file] {
>   display:none;
> }
> ```
> 
> HTML
> 
> ```
>   <div id="upload_button">
>     <label>
>       <input type="file" ngf-select ng-model="new_files" ng-change="fs.uploadFiles(new_files)" multiple>
>       <span class="btn btn-primary">Upload files</span>
>     </label>
>   </div>
> ```

Thanks man. It was brilliant
