### ISSUE TITLE
Connection Reset

### ISSUE THREAD

**Issue by pazalvin** [nervgh/angular-file-upload#659]
please help me in this error, it's weird cause the local version is working fine but in my production this is what i encounter.

![connection_reset](https://cloud.githubusercontent.com/assets/2208580/17131978/512671c0-5352-11e6-87d6-5f33823913c8.jpg)

**Comment by nervgh** [comment]
I think your error is not error of FileUploader

**Comment by wallone** [comment]
I am getting this same error. Was the source ever found?
