### ISSUE TITLE
change url path to different server

### ISSUE THREAD

**Issue by krs8785** [nervgh/angular-file-upload#664]
In my app angular-file-upload method uploadAll() calls localhost:port everytime. I want it to change it to some other server ip http://1233.3.3.3:1010/image/SaveFile. How do I do this ?

I tried

```

 vm.uploader = new FileUploader({
        url: "http://1233.3.3.3:1010/" + 'image/SaveFile'
 });



 vm.uploader.onBeforeUploadItem = function (item) {
    item.url  = 'abcd/abcd';
 }
```

Nothing worked. Still localhost is my url.

**Comment by cthiebault** [comment]
See https://github.com/nervgh/angular-file-upload/issues/274#issuecomment-59745004

**Comment by sneilan** [comment]
+1

**Comment by nervgh** [comment]
You need specify the absolute path.
You need consider [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS).
