### ISSUE TITLE
Issue with angular-http-etag

### ISSUE THREAD

**Issue by forcewill** [nervgh/angular-file-upload#665]
When using `angular-http-etag` together with `angular-file-upload` we get the following error:

`Uncaught TypeError: Cannot read property 'transformResponse' of undefined`

The error comes from this piece of code in `angular-file-upload`  FileUploader.js lines 392-398
`_transformResponse(response, headers) {
            var headersGetter = this._headersGetter(headers);
            forEach($http.defaults.transformResponse, (transformFn) => {
                response = transformFn(response, headersGetter);
            });
            return response;
        }`

I've [opened](https://github.com/shaungrady/angular-http-etag/issues/24) this issue here and in [`angular-http-etag`](https://github.com/shaungrady/angular-http-etag)

**Comment by shaungrady** [comment]
I've fixed this is `angular-http-etag` version 2.0.3.

**Comment by nervgh** [comment]
It looks like solved
