### ISSUE TITLE
Unable to upload Zip file.

### ISSUE THREAD

**Issue by sarfarazengglb** [nervgh/angular-file-upload#667]
Its not uploading zip file.

**Comment by nervgh** [comment]
Are you sure? What is a size of your zip file?

**Comment by imbdb** [comment]
+1

**Comment by imbdb** [comment]
Not uploading zip greater than 2MB size

**Comment by nervgh** [comment]
See your server' settings https://github.com/nervgh/angular-file-upload/issues/118#issuecomment-41774321

**Comment by sarfarazengglb** [comment]
Hey guys, Sorry for asking silly question.The problem is on Server side.
We need to change the value of post_max_size at line no 656  in php.ini file.It works fine.
Anyways thanks for the reply.Its working like a beauty.
