### ISSUE TITLE
How can i make the library wait in OnCompleteItem or in OnSuccessItem

### ISSUE THREAD

**Issue by tommarien** [nervgh/angular-file-upload#669]
Hi 

We have a use case where we need to wait on a promise to complete before starting another upload. At the moment we have it hooked into OnSuccessItem but this call does not wait until the callback is done. (So basicly we call an api to upload the item after the item uploaded we want to post to another api)

This causes issue when uploading multiple items in batch (due to a parallism effect)

If you got any clues please advise.

**Comment by nervgh** [comment]
Hi

> We have a use case where we need to wait on a promise to complete before starting another upload

1. you could promisify:
```js
FileItem.prototype.upload(); // --> Promise;
```
2. you could write something like [`{Pipeline}` ](https://github.com/nervgh/angular-file-upload/blob/master/src/services/Pipeline.js). It calls functions consistently.
