### ISSUE TITLE
Drag and drop only one file

### ISSUE THREAD

**Issue by EnchanterIO** [nervgh/angular-file-upload#67]
First of all: awesome script.

I would like to ask how can i allow only one file (no multiple) to drag and drop?

Or maybe in controller

```
  uploader.bind('afteraddingall', function (event, items) {
    console.info('After adding all files', items);
  });
```

Somehow remove all after drop except one?
- formData {Array}: Data to be sent along with the files

And i think i am doing something wrong

```
  var data = new Array();
  data[0] = "/path";

    url: 'upload.php',
    formData: data 
```

In network -> upload i see:

Request payload:
------WebKitFormBoundarycwIxQAfgsJMbgaI5
Content-Disposition: form-data; name="0"

/
------WebKitFormBoundarycwIxQAfgsJMbgaI5
Content-Disposition: form-data; name="1"

u
------WebKitFormBoundarycwIxQAfgsJMbgaI5
Content-Disposition: form-data; name="2"

p
------WebKitFormBoundarycwIxQAfgsJMbgaI5
Content-Disposition: form-data; name="3"

l
------WebKitFormBoundarycwIxQAfgsJMbgaI5
Content-Disposition: form-data; name="4"

o
------WebKitFormBoundarycwIxQAfgsJMbgaI5
Content-Disposition: form-data; name="5"

a
------WebKitFormBoundarycwIxQAfgsJMbgaI5
Content-Disposition: form-data; name="6"

d
------WebKitFormBoundarycwIxQAfgsJMbgaI5
Content-Disposition: form-data; name="7"

s
------WebKitFormBoundarycwIxQAfgsJMbgaI5
Content-Disposition: form-data; name="8"

/

Thank you

**Comment by ubaidazad** [comment]
@nervgh getting uploader.bind is not a function.

**Comment by nervgh** [comment]
@ubaidazad `uploader.bind` was in `<2.0.0`

**Comment by zachehre** [comment]
Hi firends. any body can help me to give a complete sample for angular file upload nervgh. i am very confused about use of this component. tnx so much

**Comment by curkychen** [comment]
@ubaidazad Hi, how do you fix the problem? Thanks!
