### ISSUE TITLE
Any plan to port to Angular 2 

### ISSUE THREAD

**Issue by Axel3232** [nervgh/angular-file-upload#676]
Everything is in the title :)

Thx

**Comment by nervgh** [comment]
I have worked with Angular 2 when it was in alpha/beta stage (~December,2015). I think Angular 1.x or Angular 2.x is not developer friendly. Yes, it is the popular technology, but as developer, I want working with an intuitive library/framework with minimalistic API which does not force me to do what I don't want.
For me that library is [Vue.js](https://medium.com/the-vue-point/vue-2-0-is-here-ef1f26acf4b8). I use Vue.js about 1.1 years and I will plan migrate all my Angular projects to Vue.js.

Thank you for your question.
