### ISSUE TITLE
JWT auth problem [satellizer]

### ISSUE THREAD

**Issue by antonioaltamura** [nervgh/angular-file-upload#678]
Hi, I'm developing a MEAN app. An Express route receive the file using Multer https://www.npmjs.com/package/multer.

The authentication is handled in JSON web token (using Satellizer https://github.com/sahat/satellizer)
So my route can be protected with autentication through an express middleware (it simply decorates the HTTP request with a correct Authentication key).
The fact I'm not sure how send the Authentication token using angular-file-upload (currently when I try to upload a file it's like I'm not logged)
`var uploader = $scope.uploader = new FileUploader({
        url: '/api/storage',
        queueLimit:1,
        autoUpload:true,
        withCredentials:true
    });`

I'm not clear how to use withCredentials flag and if it's what I need

**Comment by josencv** [comment]
angular-file-upload doesn't use angular's $http service, so you have to set the authentication header yourself (either in the uploader configuration or in the file configuration). You can check the documentation on how to set headers.

In OAuth2 you normally have to send an Authorization header like this:

```Authorization: Bearer <your_jwt_here>```

I think the "withCredentials" option is only needed for CORS calls.

**Comment by antonioaltamura** [comment]
Thanks, I solved simply adding
`      headers: { 'Authorization': 'Bearer ' + $window['localStorage'].satellizer_token }, `

**Comment by totalard** [comment]
how i set headers for all request of uploader... means Globally
