### ISSUE TITLE
Passing formData has an illogical structure and should be just a simple object

### ISSUE THREAD

**Issue by devkev16** [nervgh/angular-file-upload#682]
Hi, 

if you want to pass formData, now one has to use a structure like 

`
            formData: [
                {
                    "key": "value"
                }
            ],
`

I think a structure like this would be more logically: 

`
            formData: {
                    "key": "value"
            },
`

If I do it wrong for some reason please tell me. I got this structure from checking the code for the FileUploader service ( https://github.com/nervgh/angular-file-upload/blob/master/src/services/FileUploader.js#L448 ).

Is there a reason why it's done that way and not simply key-value in an object?

**Comment by Stalinko** [comment]
No, because you may want to have several entries with same "key". E.g. when you pass an array like

`[ {'items[]': 'item 1'}, {'items[]': 'item 2'}, {'items[]': 'item 3'}]`

**Comment by devkev16** [comment]
Hi, 

thank you for answering me.

Makes sense to me but I think when you pass an array than it is more logically using it like this:
`{
  items : [
    'item 1',
    'item 2'
  ]
}`

and convert it to the structure provided by you using an extra function in the service.

I suggest the structure above and if you want to be in control of the indices too then you have to pass an object as value with the keys as object-keys (I hope you can understand, otherwise I can provide an example).

Is there any other use case than an array where you want to pass the same key-name more than once?

At least there should be an example in the wiki (regardless of which of the two methods are used) for passing form-data as it took me some time to figure the structure out and I think one can say (at least me can ;) ) that there are more intuitive structures.

At the moment the wiki only states one should pass an array. I think "Array of Objects where the object key is the key that will be sent and the associated value is the value for the key to be sent." is way more precise about that. I think the use case with arrays as it's in your answer should deserve a small explanation there too.

**Comment by Stalinko** [comment]
@devkev16 well I'm agree that it would be cool to have two formats: object like {key1: value1, ...} and an array [{key: key1, value: value1}, ...]
Also arrays in objects like {items: [item1, item2, item3]} could be internally converted into array format.

However all that is a syntax sugar, so it's up to the author of this.

**Comment by nervgh** [comment]
> Is there a reason why it's done that way and not simply key-value in an object?

Historically :smile_cat: 

It looks we need some function which combines these things ([one](https://github.com/nervgh/angular-file-upload/blob/2.4.1/src/services/FileUploader.js#L466), [two](https://github.com/nervgh/angular-file-upload/blob/2.4.1/src/services/FileUploader.js#L535)) together and will implement new syntax sugar.

For example
```js
function addFormData(isHTML5, form, formData) {
   // code here
}
```

**Comment by devkev16** [comment]
You're right, I think I will create a PR concerning this.
