### ISSUE TITLE
Progress property is not accurate

### ISSUE THREAD

**Issue by demonmind** [nervgh/angular-file-upload#684]
I am trying to use the progress property on an upload but it does not reflect the real progress. 

It goes fast to 100% while the file needs 30 more seconds to upload.

How can that be fixed?

**Comment by d4guru** [comment]
Same issue for me.. on **localhost** `onProgressItem` logs 100 then about 10 secs later `onCompleteItem` is called. Tried with many different file size. Still the same behavior.  

            uploader.onProgressItem = function(item, progress) {
                console.log("progress =>", progress)
            };
            uploader.onCompleteItem = function(item, response, status, headers) {
                console.log("upload complete")
            };

**Comment by marcoshmendes** [comment]
Same Problem

**Comment by DavesBrain** [comment]
Was this ever resolved?

I notice that, in the simple demo, the file progress bars do not update.
When I implement this, even with a 6Mb file upload, best I see is progressItem: 100 - no smaller increments.

Progress bars are critical to my app, or I can't use the plugin.

**Comment by theo4u** [comment]
the increment is working @DavesBrain when you try to upload large files and hit on the upload the progress there increments , check the simple example on the demo link

**Comment by DavesBrain** [comment]
This is what I see in Chrome.

![progress-bar](https://cloud.githubusercontent.com/assets/17087484/25029523/3a9dc02c-208c-11e7-83e2-bd28cd99f698.png)

**Comment by theo4u** [comment]
@DavesBrain that's the progress for each of the file on the queue,  it does not disappear , check out mine
![screen shot 2017-04-14 at 10 16 40 pm](https://cloud.githubusercontent.com/assets/10440327/25056334/15dc63a4-2160-11e7-94f6-08f08798eaf9.png)

**Comment by DavesBrain** [comment]
Indeed. You are on a Mac. 
Do you support Chrome?

**Comment by theo4u** [comment]
yes we support both , click on the upload button to see it in action

**Comment by DavesBrain** [comment]
Please see above screenshot for **your demo on your site, in Chrome on PC**.
**After pressing upload**, the file progress bar appears for a fraction of a second then **disappears completely**, never to return.
I can upload a half dozen files, one after another and the same thing happens.  **Progress bar disappears upon completion of upload.**

I'm not sure how much more plainly I can say it.

**Comment by theo4u** [comment]
seriously am trying to replicate this your issue, can't find a way around it. if you can share your source code or initialization of uploader.

**Comment by DavesBrain** [comment]
I'm not making myself clear. That screenshot is a screenshot of your demo *on your site*.

Look at the URL in this screenshot:

![image](https://cloud.githubusercontent.com/assets/17087484/25150090/bdb732c0-244e-11e7-8def-c321e89b206e.png)

**Comment by theo4u** [comment]
oh i get you now, is because the server returned error while uploading the file.
![screen shot 2017-04-18 at 11 28 40 pm](https://cloud.githubusercontent.com/assets/10440327/25155883/585a43a4-248f-11e7-92b6-a0371fdf23c0.png)

**Comment by DavesBrain** [comment]
Is that what it's supposed to do? Fail?

I'm trying to test the _upload a file_ progress bar, but it does not return a 0-100 value the same way _progress all_ does.

**Comment by theo4u** [comment]
it does, check out the image below after selecting a file of 720mb large
![screen shot 2017-04-21 at 10 11 02 am](https://cloud.githubusercontent.com/assets/10440327/25271156/1069074a-267b-11e7-8780-58ee68fb5c5a.png)

**Comment by DavesBrain** [comment]
Your 'simple' demo is still broken. Will it only work if I run it locally? I can't run it on your site?

![image](https://cloud.githubusercontent.com/assets/17087484/25279989/644be012-2676-11e7-80ae-eba8f1b58a36.png)

**Comment by theo4u** [comment]
@DavesBrain  check the onProgressAll that is the percentage sent to server, you will see **0** since github pages can't allow us to do upload that is why we can't really do the upload from our simple test, use from your server  and see
