### ISSUE TITLE
$rootScope.$apply() and terrible performance with multiple files

### ISSUE THREAD

**Issue by maurycyg** [nervgh/angular-file-upload#687]
I've an application where I use file uploader 2.3.4 at some point, I noticed a drop in performance while a list of just 50 `items` was loaded at the same time. After digging a bit I found  that this line is called https://github.com/nervgh/angular-file-upload/blame/master/src/services/FileUploader.js#L342 causing ALL the watchers to be fired way too often. This should be handled differently. In my case, I could remove the `_render` as uploader renders properly and now adding 300+ files has no hiccups

**Comment by nervgh** [comment]
You could just override the `_render` method:
```js
let uploader = new FileUploader(/* options */);

uploader._render = function() {
    // $scope is your scope
    if(!$scope.$$phase) $scope.$apply();
};
```

Also you could improve docs about performance issues.

**Comment by nervgh** [comment]
https://github.com/nervgh/angular-file-upload/wiki/FAQ#11-performance-issues

**Comment by maurycyg** [comment]
Thanks, I'll create extended document on the performance
