### ISSUE TITLE
Online demo doesn't work: errors are 405 or net::ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by fuffalist** [nervgh/angular-file-upload#688]
The online demo at: http://nervgh.github.io/pages/angular-file-upload/examples/simple/ is not working properly.

I tested it on various devices (Safari on Mac, Chrome on Windows, Safari on iOS, Chrome Android) and the file isn't actually uploaded. In the browser console I see a 405 error (Method Not Allowed) or a net::ERR_CONNECTION_RESET.

**Comment by nervgh** [comment]
The online demo hosts on GitHub Pages. It's only frontend code without backend side. You need implement your own backend.
