### ISSUE TITLE
please close this library

### ISSUE THREAD

**Issue by lucastan** [nervgh/angular-file-upload#693]
it seems problematic with so many issues.

pls close this library if you're not maintaining any more .. so people won't be misled into using

**Comment by nervgh** [comment]
> pls close this library if you're not maintaining any more .. so people won't be misled into using

Many people already use this library. What I should do with it on your opinion?

**Comment by OzBob** [comment]
I think @lucastan is trying to say: "please may I be a contributor".

There are issues and pull requests that are waiting for some eager person to accept into the repository.

Nudge @theo4u @denkan maybe even the authors of the pull requests could be promoted to contributors .... @bguezzie @piercus

**Comment by nervgh** [comment]
@OzBob 

> I think @lucastan is trying to say: "please may I be a contributor".

May be yes, may be not. I'm not sure)

> There are issues and pull requests that are waiting for some eager person to accept into the repository.

I can not accept all PRs. One of many reasons for it is what this project (module/component) would be break down. Yes, it is not an ideal but it solves many use cases... and it creates many WTFs for devs who try to integrate this module with their apps :smile_cat: Sorry, guys)))

But I think you are right. I have not enough time for maintaining the project and I should give the freedom to devs who want to improve this project (features/fixes) and make it little better.
