### ISSUE TITLE
how to upload image using avatar??

### ISSUE THREAD

**Issue by gerome0123** [nervgh/angular-file-upload#698]
hi im new in angularjs so please bear with me and thanks in advance if someone help me :)

here's my view for my upload(this is slim format)
`label Upload Image
    input type="file" nv-file-select="true" file-model="ctrl.employee.profile_attributes.avatar" uploader="uploader"

  div layout="row" layout-margin="" class="form-button"
    md-button align="center" flex="20" class="md-primary md-raised" ng-click="ctrl.save()" Save Information

`

this is my controller(coffee script format)

`
$scope.uploader = new FileUploader
      alias: "avatar"
      autoUpload: false
      queueLimit: 1
      removeAfterUpload: true

@employee.profile_attributes.avatar = $scope.uploader
@save = =>
        (@employee).$save (employee) =>
              console.log('Employee Save Success!')
             $location.path('/employees/' + employee.id`

**Comment by nervgh** [comment]
See [that](https://github.com/nervgh/angular-file-upload/tree/master/examples/image-preview) example.
