### ISSUE TITLE
S3 upload: nothing happening?

### ISSUE THREAD

**Issue by mcblum** [nervgh/angular-file-upload#700]
It's quite possible I'm doing this completely wrong -- I couldn't find any examples of S3 uploads. We're using pre-signed URLs from our API. This code hits the correct URL but doesn't include any formData at all. What do I need to do?

```
$ctrl.uploader = new FileUploader(uploaderOptions);
        $ctrl.uploader.onAfterAddingFile = function(item) {
            UploadFactory.getPresignedUrl().then(function(response) {
                item.url = response.data.attrs.action;
                item.formData = response.data.additionalData;
                item.upload();
            }, HandleError);
        };
```
Thank you for your help on this and for working on this package!

**Comment by josencv** [comment]
With #602 you can disable multipart and post a file to S3 directly, but if I recall correctly, no form data is sent with this method.

**Comment by nervgh** [comment]
I'm closing this issue. It looks solved
