### ISSUE TITLE
CHARSET

### ISSUE THREAD

**Issue by jmjdesenvolvimento** [nervgh/angular-file-upload#702]
Hi, i'm brazilian, here we have graphic accentuation and when i try to import a csv file with and ´ or ~ it becames 'tofu', that branc square, and then goes to backend �.
How i can properly set the charset, or fix this problem?

Thanks in advance

**Comment by nervgh** [comment]
```html
<meta charset="utf-8">
```
?

**Comment by jmjdesenvolvimento** [comment]
@nervgh the page has it, i mean how to make this option in the uploader

**Comment by nervgh** [comment]
See http://stackoverflow.com/a/22529662
