### ISSUE TITLE
Why main entry of package.json points to minified script?

### ISSUE THREAD

**Issue by albv** [nervgh/angular-file-upload#703]
It causes problems for our Webpack production build. Specifically after UglifyJsPlugin name mangling angular-file-upload.min.js script is broken. It's all works as expected with non-minified angular-file-upload.js file.
I think it's considered a best practice to set main entry of package.json to non-minified version of your code. So client bundler (webpack or anything else) could take care of concatenation and minification.

**Comment by nervgh** [comment]
Thank you :v:
