### ISSUE TITLE
custom content-type

### ISSUE THREAD

**Issue by jmjdesenvolvimento** [nervgh/angular-file-upload#705]
hi, the default content-type on my uploader is
` 'multipart/form-data; boundary=----WebKitFormBoundaryZiQ9I7JIcwBil3x8`
i need to add `charset=UTF-8` to it, but  but i a set the content type as 
```
  headers: {
                            'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundaryZiQ9I7JIcwBil3x8;charset=UTF-8' // or utf8 not sure, was long ago
                        }
```

it gives me: 

> Required MultipartFile parameter 'file' is not present

anyone had the same problems?

**Comment by nervgh** [comment]
You can not set `content-type` because FormData will override it anyway.

See http://stackoverflow.com/a/22529662
