### ISSUE TITLE
file in server side

### ISSUE THREAD

**Issue by silviotroia** [nervgh/angular-file-upload#710]
i've changed version from 1.1.5 to 2.4.1 and then the server side doesn't work any more

[stackoverflow question](http://stackoverflow.com/questions/41849927/angular-file-upload-server-changed-version-2-x-x)

**Comment by nervgh** [comment]
Since 1.1.5 version the major version has changed.
See [semver](http://semver.org/).

> MAJOR version when you make incompatible API changes
