### ISSUE TITLE
file change detection

### ISSUE THREAD

**Issue by badreal** [nervgh/angular-file-upload#711]
is there a way to detect file change when i select a file ?

**Comment by nervgh** [comment]
Checkout next callbacks: onAfterAddingFile, onWhenAddingFileFailed, onAfterAddingAll

https://github.com/nervgh/angular-file-upload/wiki/Module-API#callbacks

**Comment by alecha** [comment]
In my case the `onAfterAddingFile` is fired only the first time I add a file, not the following ones
