### ISSUE TITLE
question of FormData

### ISSUE THREAD

**Issue by jayrom123** [nervgh/angular-file-upload#716]
how to add FormData to the queue   ,then  upload  this FormData

**Comment by v29neil** [comment]
You can send the formdata like this
      var uploader = $scope.uploader = new FileUploader({
        url: 'http://localhost:9000/create',
        formData: [{
            uploads: JSON.stringify($scope.room)
        }],
        alias: "uploads"
      });

**Comment by nervgh** [comment]
@v29neil thank you :v:
