### ISSUE TITLE
two images with same name

### ISSUE THREAD

**Issue by marianabhud** [nervgh/angular-file-upload#717]
HI , i have a question: If you want to upload multiple images with the same name, how? I'm sorry for my English

**Comment by nervgh** [comment]
What exactly problems you have with uploading multiple images with the same names?

**Comment by marianabhud** [comment]
because uploading the only one picture

I'm adding to upload.php file this code for generate random code>

 function kod($length) {
        $key = '';
        $keys = array_merge(range(0, 9), range('a', 'z'));
        for ($i = 0; $i < $length; $i++) {
            $key .= $keys[array_rand($keys)];
        }
        return $key;
    }

    $knazvu = kod(5);

and put code before $_FILES[ 'file' ][ 'name' ]

and already now upload two photos on server.

but with crazy name. :)

**Comment by nervgh** [comment]
See https://github.com/nervgh/angular-file-upload/wiki/FAQ#4-no-file-chosen-or-re-add-same-file

**Comment by marianabhud** [comment]
i have:

 FileSelect.prototype.isEmptyAfterSelection = function isEmptyAfterSelection() {
	           // return !!this.element.attr('multiple');
                return {Boolean};
            };
	        /**
	         * Event handler
	         */
	
	
	        FileSelect.prototype.onChange = function onChange() {
	            var files = this.uploader.isHTML5 ? this.element[0].files : this.element[0];
	            var options = this.getOptions();
	            var filters = this.getFilters();
	
	            if (!this.uploader.isHTML5) this.destroy();
	            this.uploader.addToQueue(files, options, filters);
	            if (this.isEmptyAfterSelection()) {
	                this.element.prop('value', null);
	                this.element.replaceWith($compile(this.element.clone())(this.scope)); // IE fix
	            }
	        };

but doesnt work
