### ISSUE TITLE
retrying to upload file with same name does not work

### ISSUE THREAD

**Issue by zamrokk** [nervgh/angular-file-upload#723]
1/ I upload a file  A.jpg
2/ I remove the item uploaded
3/ I upload again A.jpg     => nothing happen, no event

If i upload any other file with a different name, it works

**Comment by marianabhud** [comment]
same problem: https://github.com/nervgh/angular-file-upload/issues/717

**Comment by nervgh** [comment]
See https://github.com/nervgh/angular-file-upload/wiki/FAQ#4-no-file-chosen-or-re-add-same-file
