### ISSUE TITLE
max number of uploaded files

### ISSUE THREAD

**Issue by wallone** [nervgh/angular-file-upload#724]
it seems the default number of files that can be uploaded is 10, how do I increase this?

Thanks

**Comment by nervgh** [comment]
All available options are [there](https://github.com/nervgh/angular-file-upload/blob/master/src/values/options.js).

About 10. It's your magic number! :smile_cat: 
Check out your server side settings.

**Comment by wallone** [comment]
I guess I worded this wrong.. I meant the number of files that can be queued up to be uploaded is 10. So for example if I select 12 files, only 10 appear on my screen. This is before going to the server..

**Comment by nervgh** [comment]
Wow. Yes, you are right. You need disable [filters](https://github.com/nervgh/angular-file-upload/blob/master/examples/simple/controllers.js#L15).
