### ISSUE TITLE
Error: Object is not a constructor 

### ISSUE THREAD

**Issue by jdrus** [nervgh/angular-file-upload#725]
Hi, 

I am using this module with angularjs and ionic, and I have this error:

Error: Object is not a constructor (evaluating 'new FileUploader({url: 'js/angular-file-upload/upload.php',alias: 'poster'})')

In another project I already with it but it was without ionic, so is there some incompatibility with ionic or is it coming from something else?

Thank you!

**Comment by nervgh** [comment]
Hi,

Sorry, I don't use Ionic and I cannot help you with it.

**Comment by theo4u** [comment]
@jdrus trying to replicate your issue was unable to, after importing ionic. i guess you use ionic.bundle.js which combines both angular and ionic. if you can try ionic.js and post your feed back
