### ISSUE TITLE
Need maintainers

### ISSUE THREAD

**Issue by nervgh** [nervgh/angular-file-upload#726]
Hi all!

I can't maintain this project properly. I need your help, guys.
I looking for people who could resolve opened issues & PR's.
I'll give them appropriate permissions for it (GitHub, npm)

Please,
+ follow [semver](http://semver.org/). It's _really_ important.
+ follow code style. It didn't declared obviously but there is
+ be friendly :v: 

It is not commercial project and I can't give you profit like :moneybag: 
But you could get experience with tools such as ES6, AngularJS, Webpack, Gulp, etc and make open source community little happy :smiley_cat: 

If you are interested, please, post your comment in this thread.

**Comment by farjadbullet** [comment]
I am interested, I don't want any profit like 💰 and I am only interested in getting experience with tools you mentioned. I have been working on AngularJs for quite some time now and I have always wanted to contribute to open source community... 

I will be looking forward to working on angular-file-upload.

**Comment by nervgh** [comment]
@farjadbullet you are welcome! I created the "angular-file-upload" group in [Telegram](https://telegram.org/) and sent an invite link to your email.

**Comment by nervgh** [comment]
@josencv, @bguezzie, @piercus, @denkan, @theo4u,
Please, let me know if you are need an invite link in "angular-file-upload" Telegram' group.

**Comment by theo4u** [comment]
@nervgh yea need the link

**Comment by nervgh** [comment]
@theo4u I sent it to your email

**Comment by CaosZero** [comment]
Hi! I am interested, to make experience in community and web developing. Please let me know if you need help.

**Comment by mhamdy88** [comment]
Hi, 
I'm interested too, I think I can give it few hours a week

**Comment by piercus** [comment]
Hello @nervgh, Please share the telegram link also :-)

**Comment by nopelluhh** [comment]
Also very interested if you're still looking! I've got time.

**Comment by nervgh** [comment]
Wow. Thank all for you replies! 

+ [x] @CaosZero
+ [x] @piercus
+ [x] @mhamdy88
+ [ ] @nopelluhh, please, email me about it and I will send you an invite link

**Comment by maxnathaniel** [comment]
Hello @nervgh, am keen to help out too :)
