### ISSUE TITLE
Unable to Upload file more than 15MB using ng-file-upload

### ISSUE THREAD

**Issue by poovannan** [nervgh/angular-file-upload#730]
Hi 
We are using ng-file-upload to upload files as per our requirement there is no restriction for Size of the file .When uploading smaller(10MB) files  uploading is working fine, but when trying to upload files of size 50MB its failing. 

ng-file-upload Version 9.0.8 
tried with 12.2.13 as well

**Comment by josencv** [comment]
Can you specify a little more? How exactly is failing? Can you check if an Ajax call is being made?

If you haven't explicitly configured the uploader to reject files over a specific size, this is probably a server configuration issue, and has nothing to do with the uploader.

**Comment by nervgh** [comment]
@poovannan 

> ng-file-upload Version 9.0.8

It looks like you need post your issue to [another](https://github.com/danialfarid/ng-file-upload) project.

By the way, @josencv [that](https://github.com/nervgh/angular-file-upload/issues/726#issuecomment-285850049) proposal has not time limitatoins for the collaboratos
