### ISSUE TITLE
Whether support for Angular 2 available?

### ISSUE THREAD

**Issue by ravirajhalli** [nervgh/angular-file-upload#734]

**Comment by nervgh** [comment]
I have some projects built with Angular 1.x. 
But I have no plans to use Angular 1.x or Angular 2 in the future. 
I think it is very difficult for development. 
I mean it is not follow [KISS](https://en.wikipedia.org/wiki/KISS_principle) on my opinion.

It looks like [ng2-file-upload](https://github.com/valor-software/ng2-file-upload) is a port of my project for using with Angular 2.
I have written about that already on [another forum](http://javascript.ru/forum/438883-post2084.html) (Russian language).
