### ISSUE TITLE
base64

### ISSUE THREAD

**Issue by W-prog** [nervgh/angular-file-upload#737]
Hi, 
Anyone have an example for upload items with base64 encoding
Actually I use https://github.com/adonespitogo/angular-base64-upload who work great but I want use angular-file-upload for multiple files upload and bootstrap integration
Thanks
Regards

**Comment by nervgh** [comment]
Good day,

Check out these issues: #249, #208.

**Comment by W-prog** [comment]
Oh thank you. Isn't the same prob but I have found with this issues.
I post my tips
`
uploader.onAfterAddingFile = function(item) {

        var reader = new FileReader();
        reader.onload = function(event) {
            $scope.$apply(function() {
                item.image = event.target.result;
                var monImage =item.image; // Marche avec autre chose que image bien sur. PDF testé
                // Suppression du début de chaine inutile
                var index = monImage.indexOf(",");
                if (index >= 0) {
                    myEntity.ContenuFichierAEnregistrer = monImage.substring(index + 1);
                }
                var monNom = item.file.name;
                myEntity.NomFichier = monNom;
                // console.log(myEntity); // Ready to checkin
            });
        };
        reader.readAsDataURL(item._file);

    };
`
Regards

**Comment by W-prog** [comment]
Sorry, my code don't format correctly...
This is important
var monImage =item.image;
