### ISSUE TITLE
Dag and drop using IE doesnt seem to work

### ISSUE THREAD

**Issue by wallone** [nervgh/angular-file-upload#738]
I tried using the drag and drop functionality for multiple files and it doesn't seem to work using IE (works for single file). It works on chrome with no issues however. This functionality doesn't work for the demo too. Any help is appreciated. Thanks

**Comment by mhamdy88** [comment]
@wallone 
I've just checked the demo and it is working fine, IE11.
What's your IE version and whats exactly the error?

**Comment by wallone** [comment]
I am using I.E. 11 too. There are no errors. It just doesn't appear in the list. Are you sure you are dragging and dropping multiple files at the same time?

**Comment by mhamdy88** [comment]
![1](https://cloud.githubusercontent.com/assets/3796240/24440214/972ad36c-145b-11e7-9b74-b908d3b588c4.png)
![2](https://cloud.githubusercontent.com/assets/3796240/24440213/972a0824-145b-11e7-9b57-61cd99f3914a.png)

**Comment by wallone** [comment]
[dragnDrop.docx](https://github.com/nervgh/angular-file-upload/files/877947/dragnDrop.docx)

**Comment by wallone** [comment]
![image](https://cloud.githubusercontent.com/assets/7990872/24440548/5c9c534c-141a-11e7-87f7-a032af558298.png)

![image](https://cloud.githubusercontent.com/assets/7990872/24440554/6423dbbc-141a-11e7-8e31-32f7fcdc0d06.png)

**Comment by wallone** [comment]
I am not sure if it matters, but I tried about 5 pdf files. very small files too.

**Comment by mhamdy88** [comment]
![image](https://cloud.githubusercontent.com/assets/3796240/24440819/171b0eea-145f-11e7-9e35-893eee4f1e50.png)

**Comment by wallone** [comment]
Ok I have no idea what's going on now. When you drop and drag, where do you drop them? Base drop zone or the other one?

**Comment by mhamdy88** [comment]
Base drop zone
try to check browser, check Js errors

**Comment by wallone** [comment]
You are right. I tried a different computer and it works. I just have to figure out what the difference is in the browsers. Thank you very much

**Comment by mhamdy88** [comment]
Good luck
