### ISSUE TITLE
upload: 404 not found

### ISSUE THREAD

**Issue by penchiang** [nervgh/angular-file-upload#74]
I am using Node and Express to integrate the angular-file-upload. It is working well. However, there is a slight problem. Even though files are uploaded to server successfully, there is an error message in the Chrome console: "POST http://localhost:3000/upload 404 (Not Found)". Does someone have the similar issues?

I have the server routes defined as following.

module.exports = function(app) {
    app.post('/upload', authorization.requiresLogin, fileuploads.upload);
};

**Comment by vko-online** [comment]
This is still active guys.

My simple `multer` looks like this. 

    exports.upload = multer({ dest: './upload/',
	rename: function (fieldname, filename) {
		return filename+Date.now();
	},
	onFileUploadStart: function (file) {
		console.log(file.originalname + ' is starting ...')
	},
	onFileUploadComplete: function (file) {
		console.log(file);
		console.log(file.fieldname + ' uploaded to  ' + file.path)
	}
    });

And the client side code is taken from example, with url `upload`. File is saved in disk, but response is 404.
