### ISSUE TITLE
Extend FileItem methods

### ISSUE THREAD

**Issue by lordjoker** [nervgh/angular-file-upload#742]
Hi,
is it possible to extend FileItem object and add onRemoveItem callback?

**Comment by theo4u** [comment]
you can extend it  when this event is fired `onAfterAddingFile(fileItem)` then manipulate the fileItem your binded view will still see it e.g 

```
  uploader.onAfterAddingFile = function(fileItem) {
            fileItem.test = "testing";
            console.info('onAfterAddingFile', fileItem);
        };

then your view    <td><strong>{{ item.file.name }}--{{item.test}}</strong></td>
```

but with time we might add that event to it

**Comment by lordjoker** [comment]
Thanks a lot! But I need to add function, not just property. This function - onRemoveItem - must be call when FileItem.remove is called. I have one more question - how to pass additional data with file. I need to send file description and do it as follows:

```
    uploader.onAfterAddingFile = function(fileItem) {
      fileItem.description = "";
    };

     uploader.onBeforeUploadItem = function(fileItem) {
      fileItem.formData = {
        description: fileItem.description
      }
    };
```
but on the server side I receive [object Object]

**Comment by theo4u** [comment]
formData is an array not an object. Do this instead 
push object of {key:value} for it to be seen in your server

 ` item.formData.push({test:"value"},{test2:"value2"}); --js`

` 'test' => $_POST['test'] -- php example`

**Comment by theo4u** [comment]
about the event on  item remove, would be up soon. thanks @

**Comment by lordjoker** [comment]
Thanks a lot once again.
