### ISSUE TITLE
More info on my issue

### ISSUE THREAD

**Issue by mdemarco1234** [nervgh/angular-file-upload#746]
Hi, wanted to give you more info regarding my problem in Fiddler I can see the binary of the file being sent. It looks good but at the server level this is what I get.  Below there is more binary just shortning it. When I try to read the stream I get and empty string. There may be an eof character I don't know in the middle.

------WebKitFormBoundary3w61XdGqTrBEP3AD
Content-Disposition: form-data; name="file"; filename="GeniusPhoto.png"
Content-Type: image/png

 PNG

   
IHDR  I           sRGB       gAMA

**Comment by mdemarco1234** [comment]
Here is one more to help out. This was a packet capture to the server. The port 52094 is the server ip.

host: localhost:52094
connection: keep-alive
content-length: 0
pragma: no-cache
cache-control: no-cache
content-type: multipart/form-data; boundary=----WebKitFormBoundaryC4xlaakB2NfgcNjI
user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3
accept: */*
referer: http://localhost:4400/TrackerGOCRMMobile/AngularJSMVCWebAPI/ClientCustomization/master_page/index.html
accept-language: en-US,en;q=0.8

Xóç  ßr   (   (E  (1–@ €      Ë~ÆxqØ¶ ÌÖÕ¬PMy  Xóç Jà   4   4E  41—@ €      Æy$
^}¬    €  aà  ÿ×Xóç LÔ   (   (E  (1˜@ €      $
Æy    ^}¬P  ¼Ã  Xóç R°   4   4E  41™@ €      Æz$
vä·á    €  =œ  ÿ×Xóç T¤   (   (E  (1š@ €      $
Æz    vä·âP  ˜  Xóç î3   4   4E  41›@ €      Æy$
^}¬    €  aà  ÿ×Xóç î3   (   (E  (1œ@ €      $
Æy    ^}¬P  ¼Ã  Xóç ø
   4   4E  41@ €      Æz$
vä·á    €  =œ  ÿ×Xóç ø
   (   (E  (1ž@ €      $
Æz    vä·âP  ˜  Xóç T¥   0   0E  01Ÿ@ €      Æy$
^}¬    p  uï  ÿ×Xóç T¥   (   (E  (1 @ €      $
Æy    ^}¬P  ¼Ã  Xóç \x   0   0E  01¡@ €      Æz$
vä·á    p  Q«  ÿ×Xóç \x   (   (E  (1¢@ €      $
Æz    vä·âP  ˜  Xóç k´   4   4E  41£@ €      Æ}$
±	¤    €  ±-  ÿ×Xóç mµ   (   (E  (1¤@ €      $
Æ}    ±	¥P    Xóç mµ   4   4E  41¥@ €      Æ~$
ÔrM¸    €  J3  ÿ×Xóç o™   (   (E  (1¦@ €      $
Æ~    ÔrM¹P  ¥  Xóç 	¶   4   4E  41§@ €      Æ}$
±	¤    €  ±-  ÿ×Xóç 	¶   (   (E  (1¨@ €      $
Æ}    ±	¥P    Xóç 	š   4   4E  41©@ €      Æ~$
ÔrM¸    €  J3  ÿ×Xóç 	š   (   (E  (1ª@ €      $
Æ~    ÔrM¹P  ¥  Xóç mÄ   0   0E  01«@ €      Æ}$
±	¤    p  Å<  ÿ×Xóç mÄ   (   (E  (1¬@ €      $
Æ}    ±	¥P    Xóç {ƒ   0   0E  01­@ €      Æ~$
ÔrM¸    p  ^B  ÿ×Xóç }e   (   (E  (1®@ €      $
Æ~    ÔrM¹P  ¥  Xóç H   )   )E  )1¯@ €      à™"¸ª¤(2è$,ªP¾×   Xóç H   4   4E  41°@ €      "¸à™è$,ªª¤(3€ã  
ª¤(2ª¤(3Xóç ‹Ì   4   4E  41±@ €      Æ$
n«šÇ    €  bè  ÿ×Xóç ‹Ì   (   (E  (1²@ €      $
Æ    n«šÈP  ½Ë  Xóç ‘©   4   4E  41³@ €      Æ‚$
Î×•    €  g  ÿ×Xóç ‘©   (   (E  (1´@ €      $
Æ‚    Î×•P  cJ  Xóç 	4Ô   4   4E  41µ@ €      Æ‚$
Î×•    €  g  ÿ×Xóç 	4Ô   (   (E  (1¶@ €      $
Æ‚    Î×•P  cJ  Xóç 	>–   4   4E  41·@ €      Æ$
n«šÇ    €  bè  ÿ×Xóç 	>–   (   (E  (1¸@ €      $
Æ    n«šÈP  ½Ë  Xóç  ”Ó   0   0E  01¹@ €      Æ‚$
Î×•    p  v  ÿ×Xóç  ”Ó   (   (E  (1º@ €      $
Æ‚    Î×•P  cJ  Xóç  ž—   0   0E  01»@ €      Æ$
n«šÇ    p  v÷  ÿ×Xóç  ž—   (   (E  (1¼@ €      $
Æ    n«šÈP  ½Ë  Xóç  		    E 1½@ €      Ë~ÆxqØ¶ ÌÖÕ¬PRÜ  HTTP/1.1 200 OK
Server: Microsoft-IIS/10.0
X-SourceFiles: =?UTF-8?B?QzpcUHJvamVjdHNcVHJhY2tlckdvQ1JNU2Nyb2xsSW5nRm9jdXNlZFBhdGh3YXlzXFRyYWNrZXJHb0NSTVxUcmFja2VyR09DUk1Vbml2ZXJzYWxcV2ViQVBJXGFwaVxmaWxldXBsb2FkXHBvc3Q=?=
X-Powered-By: ASP.NET
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept,Authorization
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
Access-Control-Allow-Credentials: true
Date: Mon, 17 Apr 2017 04:50:24 GMT
Content-Length: 0

Xóç  	   (   (E  (1¾@ €      ÆxË~ÌÖÕ¬qØ·îPK  Xóç  	²   (   (E  (1¿@ €      ÆxË~ÌÖÕ¬qØ·îPKŒ  Xóç  	²   (   (E  (1À@ €      Ë~ÆxqØ·îÌÖÕ­PKŠ  Xóç  	Ž   (   (E  (1Á@ €      Ë~ÆxqØ·îÌÖÕ­PK‰  Xóç  	Ž   (   (E  (1Â@ €      ÆxË~ÌÖÕ­qØ·ïPK‹  Xóç" ³o   4   4E  41Ã@ €      Æ…$
Ú¤qÅ    €  í  ÿ×Xóç" ³o   (   (E  (1Ä@ €      $
Æ…    Ú¤qÆP  zÐ  Xóç" µb   4   4E  41Å@ €      Æ†$
–ÔØÈ    €  ü¸  ÿ×Xóç" µb   (   (E  (1Æ@ €      $
Æ†    –ÔØÉP  Wœ  Xóç" 	Uh   4   4E  41Ç@ €      Æ†$
–ÔØÈ    €  ü¸  ÿ×Xóç" 	Uh   (   (E  (1È@ €      $
Æ†    –ÔØÉP  Wœ  Xóç" 	W]   4   4E  41É@ €      Æ…$
Ú¤qÅ    €  í  ÿ×Xóç" 	W]   (   (E  (1Ê@ €      $
Æ…    Ú¤qÆP  zÐ  Xóç" Qã   )   )E  )1Ë@ €      ÝÀ"¸Ë¹~Î‘î0TPœˆ   Xóç" Qã   4   4E  41Ì@ €      "¸ÝÀ‘î0TË¹~Ï€Ñ_  
Ë¹~ÎË¹~ÏXóç# µq   0   0E  01Í@ €      Æ†$
–ÔØÈ    p  È  ÿ×Xóç# µq   (   (E  (1Î@ €      $
Æ†    –ÔØÉP  Wœ  Xóç# ½A   0   0E  01Ï@ €      Æ…$
Ú¤qÅ    p  3ü  ÿ×Xóç# ½A   (   (E  (1Ð@ €      $
Æ…    Ú¤qÆP  zÐ  Xóç# 
6      E  1Ñ  €      ÂÂ 	}Î Xóç# 
ÝŠ   )   )E  )1Ò@ €      ÝÁ"¸OÒÊóäè™P   Xóç# 
ÝŠ   4   4E  41Ó@ €      "¸ÝÁäè™OÒÊô€¤ê  
OÒÊóOÒÊôXóç% ÉI   4   4E  41Ô@ €      Æ‰$
9ùnä    €  Ãu  ÿ×Xóç% ËM   (   (E  (1Õ@ €      $
Æ‰    9ùnåP  Y  Xóç% ËM   4   4E  41Ö@ €      ÆŠ$
úœÉ     €  ¨´  ÿ×Xóç% Í0   (   (E  (1×@ €      $
ÆŠ    úœÉP  ˜  Xóç% ©   )   )E  )1Ø@ €      Ýº"¸ˆ‡?]’"=P’Ã   Xóç% ©   4   4E  41Ù@ €      "¸Ýº]’"=ˆ‡@€ /#  
ˆ‡?ˆ‡@Xóç% 	nè   4   4E  41Û@ €      ÆŠ$
úœÉ     €  ¨´  ÿ×Xóç% 	nè   4   4E  41Ú@ €      Æ‰$
9ùnä    €  Ãu  ÿ×Xóç% 	nè   (   (E  (1Ü@ €      $
ÆŠ    úœÉP  ˜  Xóç% 	nè   (   (E  (1Ý@ €      $
Æ‰    9ùnåP  Y  Xóç& Ð€   0   0E  01Þ@ €      Æ‰$
9ùnä    p  ×„  ÿ×Xóç& Ð€   0   0E  01ß@ €      ÆŠ$
úœÉ     p  ¼Ã  ÿ×Xóç& Ð€   (   (E  (1à@ €      $
Æ‰    9ùnåP  Y  Xóç& Ð€   (   (E  (1á@ €      $
ÆŠ    úœÉP  ˜  Xóç( ×   4   4E  41â@ €      Æ$
ÖÆ@à    €  T¨  ÿ

**Comment by nervgh** [comment]
I'm closing this issue. You need post this info to the corresponding issue.
