### ISSUE TITLE
What are you talking about?

### ISSUE THREAD

**Issue by mdemarco1234** [nervgh/angular-file-upload#750]
????

**Comment by mdemarco1234** [comment]
Can you be clear in what your asking. Your closing a case and no one knows what your asking us to do? Please give more direction in what your asking.

**Comment by DavesBrain** [comment]
Was this meant to be a reply to some particular issue? At the moment its not associated with any issue.

**Comment by nervgh** [comment]
@mdemarco1234 please follow the simple rule: 1 problem = 1 issue. [It looks you duplicate your question to several issues.](https://github.com/nervgh/angular-file-upload/issues?utf8=%E2%9C%93&q=is%3Aissue%20author%3Amdemarco1234%20)
