### ISSUE TITLE
Missing filename. Request should include a Content-Disposition header with a filename parameter

### ISSUE THREAD

**Issue by edouard-lopez** [nervgh/angular-file-upload#752]
Hi, 
I'm having trouble with `angular-file-upload@^2.5.0` and Django Rest Framework.

### HTML
I took the HTML from the [introduction](https://github.com/nervgh/angular-file-upload/wiki/Introduction)

	<input type="file" nv-file-select uploader="vm.uploader"/>
	<ul>
		<li ng-repeat="item in vm.uploader.queue">
			Name: <span ng-bind="item.file.name"></span><br/>
			<button ng-click="item.upload()">upload</button>
		</li>
	</ul>

### Controller

Put a quick controller together

```
function controller(FileUploader, $q, $cookies, logger) {
	var vm = this;

	function activate() {
		vm.uploader = new FileUploader({
			url: '/api/expense-claim/' + vm.expense.id + '/transport-cost-attachment/',
			headers: {
				'X-CSRFToken': $cookies.get('csrftoken')
			}
		});
		vm.uploader.onBeforeUploadItem = onBeforeUploadItem;
	}

	function onBeforeUploadItem(fileItem) {
		fileItem.formData.push({creator: vm.owner});
		fileItem.formData.push({attachment_file: fileItem.file.name});
	}

	activate();
```

### Request payload

```
------WebKitFormBoundary93NIIdZgPKRvcuFm
Content-Disposition: form-data; name="creator"

3
------WebKitFormBoundary93NIIdZgPKRvcuFm
Content-Disposition: form-data; name="attachment_file"

VPS SSD 1.pdf
------WebKitFormBoundary93NIIdZgPKRvcuFm
Content-Disposition: form-data; name="file"; filename="VPS SSD 1.pdf"
Content-Type: application/pdf


------WebKitFormBoundary93NIIdZgPKRvcuFm--
```

### Error

I got a Status Code:400 Bad Request

    {"detail":"Missing filename. Request should include a Content-Disposition header with a filename parameter."}

### Question

How do I had the ` filename="VPS SSD 1.pdf"` to the first `Content-Disposition`?

**Comment by seansmckinley** [comment]
Lol. I actually have this problem with ng-file-upload and drf

**Comment by seansmckinley** [comment]
What do your viewsets look like?

**Comment by furkick** [comment]
I appear to be having the same problem with a C# Web API 2 uploader. 

The Content-Disposition in the request payload is:
```
------WebKitFormBoundaryoC35XYGTUV57E4ny
Content-Disposition: form-data; name="file"; filename="balloon_flight_plant_91681_1920x1080.jpg"
Content-Type: image/jpeg

------WebKitFormBoundaryoC35XYGTUV57E4ny--
```

Using the following C# code I should be able to extract the filename to perform checks prior to using a MultipartFormDataStreamProvider to write to disk.

```
var contentDisposition = Request.Content.Headers.ContentDisposition;
```

However the Content-Disposition always returns a null.

Any ideas on a fix as currently I am just sending the filename via a parameter in the header of the Post?

**Comment by edouard-lopez** [comment]
I fixed my issue using `alias` field (see [front-end source code](https://github.com/akema-fr/apidae-frontend/blob/acd848159b1fcabe229004b030758ff813998f09/src/components/attachments/attachments.component.js)):

		vm.uploader = new FileUploader({
			url: vm.submitUrl(),
			headers: {
				'X-CSRFToken': $cookies.get('csrftoken')
			},
			alias: 'attachment_file',
			removeAfterUpload: true,
			autoUpload: true
		});

`submitUrl()` is a method to compute the URL to submit.
