### ISSUE TITLE
Re uploading the same uploaded files 

### ISSUE THREAD

**Issue by dhaneshhs** [nervgh/angular-file-upload#754]
i cant re upload the same files once uploaded , i tried copying the FileUploader object into the new object that does not work as the isUploaded property of fileitem is set to true once uploaded. and i tried adding the  Files selected to new FileUploader object files getting added to the queue but not uploading

**Comment by nervgh** [comment]
Hi!

Check out [that](https://github.com/nervgh/angular-file-upload/wiki/FAQ#4-no-file-chosen-or-re-add-same-file).

**Comment by ctellesfe** [comment]
Hello, 

Here's the complete code :

angular.module('App...' ,[....])....
.config(['$provide', function($provide) {
    $provide.decorator('FileSelect', ['$delegate', function(FileSelect) {
	FileSelect.prototype.isEmptyAfterSelection = function(){return true}
        return FileSelect;
    }])
}]);
