### ISSUE TITLE
can we use multiple uploader in same page ?

### ISSUE THREAD

**Issue by samxfido** [nervgh/angular-file-upload#756]
i have a form in which there are multiple fields . each fields will have set of properties so i need to upload single image for each of fields in the form . how can i attain it ?. and on form submit all form details must to sent to api . how can i attain it ?

**Comment by theo4u** [comment]
can you drop a sample code of what you are trying to achieve

**Comment by tjaussoin-luna** [comment]
might help you: https://github.com/nervgh/angular-file-upload/issues/144
