### ISSUE TITLE
There's something wrong with ionic.bundle

### ISSUE THREAD

**Issue by see311** [nervgh/angular-file-upload#760]
```html
    <script src="libs/js/ionic.bundle.min.js"></script>
    <script src="libs/js/angular/angular-file-upload.min.js"></script>
```
If I import js like above, it will throw the error "angular-file-upload.min.js:7 Uncaught SyntaxError: Unexpected token <"

**Comment by theo4u** [comment]
which version of ionic bundle are you using

**Comment by see311** [comment]
ionic 1.3.3
![image](https://user-images.githubusercontent.com/22143374/27017935-0c1ec41a-4f5f-11e7-946e-6ccb487f2413.png)

**Comment by theo4u** [comment]
which version of angular file upload are you using , i just did same test with ionic v1.3.3
![screen shot 2017-06-12 at 9 52 39 am](https://user-images.githubusercontent.com/10440327/27026203-dd6ede98-4f54-11e7-944b-44c67ea72bad.png)

this is the plnkr link [http://embed.plnkr.co/0YMaLS/](http://embed.plnkr.co/0YMaLS/)

**Comment by see311** [comment]
just download from https://github.com/nervgh/angular-file-upload/tree/master/dist

**Comment by theo4u** [comment]
You downloaded the wrong file that was why, the **angular-file-upload.min.js** is not the real file check the picture below of what the file look like 
<img width="1387" alt="screen shot 2017-06-16 at 3 01 43 pm" src="https://user-images.githubusercontent.com/10440327/27229801-e1b203f6-52a4-11e7-9b84-06e7bfe420f3.png">

use this [link](https://github.com/nervgh/angular-file-upload/releases) or goto the **releases** on  https://github.com/nervgh/angular-file-upload to grab the latest one instead
