### ISSUE TITLE
Error: [$injector:unpr] Unknown provider: $stateProvider

### ISSUE THREAD

**Issue by HANNAHANHAN** [nervgh/angular-file-upload#764]
i'm follow the example inject the  angularFileUpload and there have a problem is  .how can i solve it ???

angular
		.module('app',['angularFileUpload'])
		.controller('ProfileModifyController', ProfileModifyController);

Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:unpr] Unknown provider: $stateProvider

**Comment by theo4u** [comment]
did you include the file to your index.html the angular-file-upload.js

**Comment by HANNAHANHAN** [comment]
i did，still wrong ，

**Comment by theo4u** [comment]
state provider is becuase you are using state routing which is not in concern with angular file upload, please check your code, not angular file upload. google the error for better assistance
