### ISSUE TITLE
Filter for Document Files not working

### ISSUE THREAD

**Issue by Mr-Anonymous** [nervgh/angular-file-upload#776]
I am trying to use this file upload plugin to upload documents. I have added the following uploader filters but only the `.pdf` files are being uploaded and nothing happens if any other file types such as docx, pages, etc are added. If I remove the below code, then the upload works but with this filter code, any listed file types other than pdf is not getting added at all. Have I got anything wrong with the filter here? Can someone share please?

```
uploader.filters.push({
                  name: 'fileFilter',
                  fn: function(item, options) {
                      var type = '|' + item.type.slice(item.type.lastIndexOf('/') + 1) + '|';
                      return '|pdf|doc|docx|xls|xlsx|ppt|pptx|pages|numbers|rtf|txt|'.indexOf(type) !== -1;
                  }
              });
```

I am using this plugin in Angular 1.5.

**Comment by theo4u** [comment]
Using item `type` is not too safe as it comes as the `mime-type` of the item, so getting the file extension from the `name` of the item should be better,  here's a sample filter for allowed extensions


 ```js
uploader.filters.push({
            name:'Extensions',
            fn: function(item, options){
                var allowedExtensions = ['pdf', 'doc','jpg'];
                var ext  = item.name.split('.').pop(); //get the file extension
                 
                 return allowedExtensions.indexOf(ext) !== -1;;
            }
        });

```
