### ISSUE TITLE
How to use onSuccessItem

### ISSUE THREAD

**Issue by deniz946** [nervgh/angular-file-upload#778]
Hello, im trying to use onSuccessItem but I'm not sure how to use it, i have this uploader

`
    $scope.uploaderAfter = new FileUploader({
        url: API + 'projects/after',
        method: "POST",
        alias: "after",
    });
`
And 

`
$scope.uploaderAfter.uploadAll();
$scope.uploaderAfter.onSuccessItem(function(blabla){console.log(blabla)}) 
`

but it wont work

**Comment by nervgh** [comment]
Please check out the [examples](https://github.com/nervgh/angular-file-upload/blob/master/examples/simple/controllers.js#L55).
