### ISSUE TITLE
Sending dynamic scope variables in request

### ISSUE THREAD

**Issue by sanjeevkse** [nervgh/angular-file-upload#780]
I got that, I have to do the below code to send more parameters. But my requiremenet is sending dynamic data like, I have a datepicker and I want to send its value through the ajax call.
```

var uploader = $scope.uploader = new FileUploader({
        url: '/upload.php',
        formData: [ { "key1": "value1" },{ "key2": "value2" }],
 });
```

**Comment by theo4u** [comment]
check this issue #742
