### ISSUE TITLE
Adjust context path for upload

### ISSUE THREAD

**Issue by cyt-mn** [nervgh/angular-file-upload#783]
In my dev environment, I can upload a file to my webapp through the endpoint "http://localhost:8080/endpoint". After creating the FileUploader object, I set uploader.url = "endpoint". Works like a charm.

However, on my prod environment, the webapp is deployed under "http://my.domain.com/contextpath". The uploader tries to connect to "http://my.domain.com/contextpath/endpoint", which is not working, as the endpoint is here "http://my.domain.com/endpoint". 

Is there any option to remove "/contextpath" from the url before the upload starts?

Thanks!
Matt

**Comment by nervgh** [comment]
I think you need read about absolute/relative urls (paths) and how they form.

```js
uploader.url = "endpoint"
```
vs
```js
uploader.url = "/endpoint"
```

**Comment by cyt-mn** [comment]
Thanks nervgh for pushing me into that direction. That solved my issue.

I set uploader.url = "/endpoint" which connects to my endpoint "http://my.domain.com/endpoint".

Best
Matt
