### ISSUE TITLE
IE holding onto file after upload

### ISSUE THREAD

**Issue by nathand8** [nervgh/angular-file-upload#785]
It's a known issue that IE holds onto files after they are uploaded. However, there are a few workarounds listed and I would appreciate a workaround for angular-file-upload.

Steps to reproduce:
1. Upload a file using IE. (I used IE 11)
1. Try to rename the folder that held the file
1. See the error. (Mine reads "The action can't be completed because the folder or a file in it is open in another program)

Original IE bug reports:
https://connect.microsoft.com/IE/feedback/details/783267/multiple-http-upload-keeps-file-lock-on-local-filesystem
https://connect.microsoft.com/IE/feedback/details/817183/ie10-and-ie11-keep-files-locked-after-uploading

Workarounds:
https://stackoverflow.com/questions/35055123/ie-11-lock-the-file-when-using-html-input-file-tag
https://connect.microsoft.com/IE/feedback/details/783267/multiple-http-upload-keeps-file-lock-on-local-filesystem (Click on Workarounds)

I haven't been able to get either of these workarounds working with angular-file-upload. I know it's not really angular-file-upload's problem, but I recently had a difficult exchange with a customer because of this. It would be very nice to fix it for them programmatically

**Comment by theo4u** [comment]
@nathand8 you can simply do this on `onAfterAddingFile` hook, for example
```javascript
 uploader.onAfterAddingFile = function (fileItem) {
            console.info('onAfterAddingFile', fileItem);
            console.log(document.getElementById("uploaderTest"));
            document.getElementById("uploaderTest").value=""; // input file field
        }
```
view
```html
Single
<input id="uploaderTest" type="file" nv-file-select="" uploader="uploader" />
```

and thanks for the references

**Comment by nathand8** [comment]
Unfortunately that didn't work. Thanks for the quick response tho

**Comment by nathand8** [comment]
I was unable to get even the simplest example to bypass the problem:

```html
<html>

    <head>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular.min.js"></script>
        <script src="node_modules/angular-file-upload/dist/angular-file-upload.min.js"></script>
        <script>
        var app = angular.module("fileUploadProbs", ["angularFileUpload"]);
        app.controller("mainCtrl", function($scope, FileUploader) {

            $scope.uploader = new FileUploader();
            $scope.uploadedFiles = [];

            $scope.uploader.onAfterAddingFile = function (fileItem) {
                $scope.uploader.uploadAll();
                console.info('onAfterAddingFile', fileItem);
                console.log(document.getElementById("uploaderTest"));
                document.getElementById("uploaderTest").value=""; // input file field
            }

            $scope.uploader.onCompleteItem = function (item, response, status, headers) {
                console.log(item);
                $scope.uploadedFiles.push(item.file.name);
            }
        });
        </script>
    </head>

    <body>
        <div ng-app="fileUploadProbs" ng-controller="mainCtrl">
            Upload File - Single
            <input id="uploaderTest" type="file" nv-file-select="" uploader="uploader" />
            <div>
                <p ng-repeat="file in uploadedFiles">{{file}}</p>
            </div>
        </div>
    </body>

</html>
```

**Comment by theo4u** [comment]
i did and it worked for me , do a [plnkr.co](plnkr.co) of it

**Comment by theo4u** [comment]
chekc this plnkr as it is working as it should, using your code above
http://embed.plnkr.co/Ti1NxY/

**Comment by amit2413** [comment]
theo4u.. i tried the link of Plunker on IE11 but it seems its not working when u Shift+Delete. It works when you Delete the file it goes to Recycle Bin.
