### ISSUE TITLE
get all the selected files

### ISSUE THREAD

**Issue by trinadh93** [nervgh/angular-file-upload#786]
is there a way to get all the selected file list ?

**Comment by theo4u** [comment]
can you be more explicit, to get the files on the queue ?

**Comment by trinadh93** [comment]
I need the full list of selected files not the files which are in the queue.

`FileUploader.prototype.addToQueue = function addToQueue(files, options, filters) {`

in the above method definition, while debugging, if I hover on `files` it is showing all the selected files irrespective of whether they are in queue or failed.

there is no provision to get all the selected / choosen files.

can someone help me on this ?

**Comment by theo4u** [comment]
so @trinadh93 you are trying to get all the files failed, success and on queue right?

**Comment by trinadh93** [comment]
I am selecting multiple files at a time. so I need the count of files that I selected.

I am not concerned about whether the files are failed or success or on the queue.

**Comment by theo4u** [comment]
oh you are using multiple file select and trying to get the total number of files selected , if am right ?

Then you can use this hook `onAfterAddingAll` to handle it 

```javascript
 uploader.onAfterAddingAll = function (addedFileItems) {
            console.info('onAfterAddingAll', addedFileItems);
            console.log("Added multiple files", addedFileItems.length);
        };
```

**Comment by trinadh93** [comment]
```
onAfterAddingAll function(addedItems) {} //gives me all the files on the queue
onWhenAddingFileFailed function(item, filter, options) {} //triggers for individual failed item
```

my intention is to perform some validation on all the failed items (at once). right now there is no method that returns all the failed items at once (as an array or a list).

so even if I have the selected files count, I can perform the validation.

### lets assume this scenario:
- **selected 5 files**
- **3 files passed** all the filters and were added to the queue. with `onAfterAddingAll function(addedItems)`, I can only get the valid files and the length would be 3
- **2 files were failed**. with `onWhenAddingFileFailed function(item, filter, options)`, I can only get individual failed items (one at a time)

I want to get selected files in this case my expected result would be **5**
![git](https://user-images.githubusercontent.com/19210147/29446615-cf28ca5c-840a-11e7-8bfa-a6d3bb822174.jpg)

when I put a debug point in the default API method
```
addToQueue(files, options, filters) {
            let incomingQueue = this.isArrayLikeObject(files) ? Array.prototype.slice.call(files): [files];
            var arrayOfFilters = this._getFilters(filters);
```
the `files `argument in `addToQueue()` is having all the files that I have selected.

I am searching for a way to get it.

is there a way to get those `files` count / length ?

@theo4u thanks in advance

**Comment by theo4u** [comment]
you can listen for FAILED fies and add it to your success files to get the count, like so

```
onAfterAddingAll function(addedItems) {} //gives me all the files on the queue
var failed = [];
onWhenAddingFileFailed function(item, filter, options) {
   failed.push(item);
} //triggers for individual failed item

```

think the above should pretty help you
