### ISSUE TITLE
Large Data with Chunk Using MVC

### ISSUE THREAD

**Issue by smohammedyasin** [nervgh/angular-file-upload#790]
Hello,
This is not an issue, just a question

i have more then 1 GB Size of Each file

how can i get (chunk data) Multi part Form Data Content  with this file upload?
is  any one has used this plugin for large file with chuck  using .net?

Best Regards

Mohammed Yasin

**Comment by nervgh** [comment]
Hello,

Please, check out those issue https://github.com/nervgh/angular-file-upload/issues?utf8=%E2%9C%93&q=chunk

https://github.com/nervgh/angular-file-upload#how-to-ask-a-question
