### ISSUE TITLE
Changing form data before upload

### ISSUE THREAD

**Issue by morganlaneap** [nervgh/angular-file-upload#792]
Attempting to modify the form data before uploading. Code:
```
uploader.onBeforeUploadItem = function() {
    $scope.uploader.formData = [{
       folder: $('#current-folder').html(),
        '_token' : $('meta[name=csrf-token]').attr("content")
    }];
};
```
`$('#current-folder').html()` changes dynamically, so needs to be reflected when uploading.

The default value (0) which is being passed in upon creating the uploader is still being used.

Any ideas why?

**Comment by theo4u** [comment]
have you consider using this hook `onBeforeUploadItem` to do automatically do your `$('#current-folder').html()`, like so 

 ```javascript
uploader.onBeforeUploadItem = function (item) {
            console.info('onBeforeUploadItem', item);
var value = $('#current-folder').html();
        };
```

**Comment by morganlaneap** [comment]
I've tried to use that but for some reason it won't update the `formData` property of the FileUploader class. It stays as how it was when it was created.

**Comment by BigCarrotShow** [comment]
//上传前，添加其他参数
        $scope.uploader.onBeforeUploadItem = function (item) {
            item.formData = [“your data1”,"your data2"];
        }

**Comment by theo4u** [comment]
#369
