### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by DanRamGim** [nervgh/angular-file-upload#794]
How can I change the timeout from the upload using angular-file-upload, I want it to be able to upload big files without the timer running out of time.

**Comment by theo4u** [comment]
#601

**Comment by DanRamGim** [comment]
I have just found my solution, you can add this lines on angular-file-upload.min.js

After this lines:

o = e._xhr = new XMLHttpRequest; if (e.disableMultipart ? t = e._file : (t = new F, f(e.formData, function (e) { f(e, function (e, n) { t.append(n, e) }) }), t.append(e.alias, e._file, e.file.name)), "number" != typeof e._file.size) throw new TypeError("The file specified is no longer valid");

And before this lines:
o.upload.onprogress = function (t) { var o = Math.round(t.lengthComputable ? 100 * t.loaded / t.total : 0);

You can add your code, this is mine: e._xhr.timeout = 3600000; e._xhr.ontimeout= function(){e.isError = true; e.progress = 0; alert('El servidor no ha respondido, favor de intentarlo nuevamente')};

This makes the timeout of an hour long and it deletes the progress and show that you had an error, after that I send an alert.

**Comment by theo4u** [comment]
@DanRamGim going to check it out, nice one.
