### ISSUE TITLE
Async call in onBeforeUploadItem

### ISSUE THREAD

**Issue by th3v0ice** [nervgh/angular-file-upload#801]
Is it possible to do async call in onBeforeUploadItem, wait for it to finish and then upload the file? I need some data from the server which I am sending via POST with actual file upload, but this data is only available once the user clicks on the upload button. I could use the async filter but that is not actually what I want. 

I tried to read all questions in the Issues tab but none answered mine. Sorry if this was asked already. Thanks!

**Comment by nervgh** [comment]
You can do something like this:
```js
performAsyncOperation.then(() => {
  uploader.uploadAll() // or item.upload()
})
```

**Comment by th3v0ice** [comment]
So if I understood You correctly this is how it could be done

```
uploader.onBeforeUploadItem = function(item) {
            $scope.id = 0;
            var json = {action: "upload_start"};            

            getID(json).then(() => {
                item.formData[1] = {"id" : $scope.id};
                item.upload();
              });
            console.info('onBeforeUploadItem', $scope.id);
        };

        function getID(json) {
            $http({
                method : "POST",
                url : "ctrl.php",
                headers: { 'Content-Type': 'application/x-www-form-urlencoded;charset=utf-8' },
                data: json
            }).then(function(response) {
                $scope.id = response.data; 
            });
            return;
          }
```

But the problem is that I am getting this error

```
onCompleteItem RangeError: Maximum call stack size exceeded
onCompleteItem RangeError TypeError:Cannot read property 'then' of undefined undefined RangeError
```

What am I doing wrong? Thanks once again.

**Comment by nervgh** [comment]
I hope the idea is clear:
```js
uploader.yourMethod = function (item) {
  var json = {
    action: "upload_start"
  };
  getID(json).then((response) => {
    item.formData[1] = {"id" : response.data};
    item.upload();
  });
}

function getID(json) {
  return $http({
      method : "POST",
      url : "ctrl.php",
      headers: { 'Content-Type': 'application/x-www-form-urlencoded;charset=utf-8' },
      data: json
  });
}
```

**Comment by th3v0ice** [comment]
I think it is, but the uploader is not waiting for a call to finish before it uploads the file. One more question to be clear, when You said uploader.yourMethod, did You mean method from callbacks that are available for uploader of my choosing or a method that I wrote which in turn overrides the upload button for the item? If later, how can I achieve that?

```
        uploader.onBeforeUploadItem = function(item) {
            var json = {action: "upload_start"};            

            getID(json).then((response) => {
                item.formData[1] = {"id" : response.data};
                item.upload();
              });


            console.info('onBeforeUploadItem', item.formData[1]);
        };

        function getID(json) {
            return $http({
                method : "POST",
                url : "ctrl.php",
                headers: { 'Content-Type': 'application/x-www-form-urlencoded;charset=utf-8' },
                data: json
            });
        }
```

Thanks!

**Comment by theo4u** [comment]
Hey @th3v0ice what @nervgh is trying to say is for you to call the `item.upload()` after an asynchronous method or process,

which invariably means angular-file-upload does not support async process on hooks associated to each item to be uploaded.

Now the best way to do it is to handle the `item.upload()` process your self, and do your async task that is needed like so 

```javascript
$scope.uploadMe = function (item) {
            var asyncTask = new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve("done");
                }, 2000);
            });

            asyncTask.then((message) => {
                // so you can handle your data here to do anything before the you call the main item.upload
                item.upload();
            });

        }

```

then your template would now look like this
```html
 <button type="button" class="btn btn-success btn-xs" ng-click="uploadMe(item)" ng-disabled="item.isReady || item.isUploading || item.isSuccess">
                                        <span class="glyphicon glyphicon-upload"></span> Upload
                                    </button>
```

**Comment by th3v0ice** [comment]
Ok I understand. Thanks. What if I wanted for this action to be triggered once I click on the green upload button that is shown by the file name in the upload queue? So I want to trigger my custom upload action instead of the default one? 

Thanks for all the help!

**Comment by th3v0ice** [comment]
@theo4u thank You very much. Its working now. Please forgive my ignorance.

**Comment by nervgh** [comment]
@tonycoco you cannot perform async operations with sync way:

```js
$scope.assetsUploader.onBeforeUploadItem = function(item) {
    var resp;

  // an async operation which assigns "resp" value
  // it won't work because the operation is ASYNC =)

    item.url = resp;
  };
``` 

One of the possible solutions is https://github.com/nervgh/angular-file-upload/issues/801#issuecomment-335708548

**Comment by tonycoco** [comment]
Yeah, I'm aware that the code I had doesn't work. Just wanted to see if those hooks could potentially take a promise.
