### ISSUE TITLE
Upload content of a file instead of the file itself

### ISSUE THREAD

**Issue by thrinay** [nervgh/angular-file-upload#820]
I would like to upload contents of a .json file instead of file. I tried multiple ways to figure it out but couldn't find any solution despite. Thus would be glad if this is said. Thanks

**Comment by thrinay** [comment]
For those of you who are struggling to upload a JSON data instead of file. 
Kindly do the following.
` var uploader = $scope.uploader = new FileUploader({
              url: 'blabla',
              method: 'POST',
          });

uploader.uploadItem = function (item) {

              reader.readAsBinaryString(item._file);

              reader.onloadend = function(){

                  item.data = reader.result;
}

// Here you can add item.data into your request body.

          };



`

Kindly close this issue as it's solved

**Comment by nervgh** [comment]
> Kindly close this issue as it's solved

Done =)
