### ISSUE TITLE
Upload using Java, not PHP

### ISSUE THREAD

**Issue by wellingtonfoz** [nervgh/angular-file-upload#822]
Hi,

Is there any way for uploading using Java and not a PHP file? Could anyone help me with that?

	var uploader = $scope.uploader = new FileUploader({
		url: 'upload.php'
	});

**Comment by andrei-cacio** [comment]
Hi @wellingtonfoz,

yes, you can, it is a back-end detail. It has nothing to do with angular-file-uploader. The way the browser uploads the file is the same for all back-ends.

If you wish to upload the file via java you should search in that direction.

A quick google search gave me this tutorial: https://docs.oracle.com/javaee/6/tutorial/doc/glraq.html
