### ISSUE TITLE
How can I add hidden form input values?

### ISSUE THREAD

**Issue by edwinjue** [nervgh/angular-file-upload#827]
If I were to use a HTML form, I would be able to add attributes to an upload like so:

`<input type="hidden" name="id" value="1234">`

How can I accomplish this using angular-file-upload so I can send this kind of data to the back-end?
I need to be able to update a database in a way that associates an upload to an id.

Thanks!

**Comment by theo4u** [comment]
u can programmatically check here #123

**Comment by edwinjue** [comment]
@theo4u thank you so much for pointing me in the right direction. I ended up going with this approach:
```
var fileUploader = new FileUploader();

fileUploader.onBeforeUploadItem = function(fileItem) {
    fileItem.formData.push({ data: 'data' });
};
```
