### ISSUE TITLE
Async call in onBeforeUploadItem with uploader.uploadAll()

### ISSUE THREAD

**Issue by BriceN** [nervgh/angular-file-upload#831]
Hello,
First of all, thank you for this amazing library !
I searched all the issues on this repo but I can't wrap my head around this.
I have the same problem as referenced in #801 , but I don't think that the trick to write my own wrapper around fileitem.upload() like below works for me :

```javascript
$scope.uploadMe = function (item) {

            var asyncTask = new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve("done");
                }, 2000);
            });
            asyncTask.then((message) => {
                // so you can handle your data here to do anything before the you call the main item.upload
                item.upload();
            });
        }
```

Because my form button triggers uploader.uploadAll(), and I have to attach a JWT for each item of the queue. Sometimes the JWT expires during the upload process, and I have to do some API requests in order to get a new one and attach it to the next request of the upload queue.

This could have been so much easier if the library used $http, because my interceptor automatically append the JWT to the next request, or get a new one if the current one is expired.
But hey, thats not the case here and I will have to find a workaround ;)

So my question here is : how can I do some async stuff inside onBeforeUploadItem, for each fileitem inside the upload queue.

Thank you for your time !

**Comment by alba94** [comment]
mkmkmkm ...!
