### ISSUE TITLE
Clicking on label associated to the input does not work on IE11

### ISSUE THREAD

**Issue by mingca** [nervgh/angular-file-upload#839]
Implementation looks like this - 

```
<div nv-file-drop uploader="setup.uploader" ng-class='{"drag_here": showDragDrop}'>
    <form name="imageUpload1" style="display: inline-block">
      <div class="button fileinput-button">
        <input id="{{'fileUploader' + uploadId}}" class="hidden" type="file" nv-file-select uploader="setup.uploader" multiple/>
        <label id="file_upload_label" for="{{'fileUploader' +uploadId}}" >{{label}}</label>
      </div>
    </form>
  </div>
```
So I am trying to click on the label to open the file dialog.
I click on the label and it opens the file dialog on chrome and Edge. Clicking on label doesn't open file dialog on IE11. Any ideas?

Not sure if this is the right place to post the issue, but can someone look at if file uploader is preventing the event to occur?

**Comment by ygj6** [comment]
I tried it myself and found no problems with IE11. Is your problem still there?

![70885133-ee6f6780-2012-11ea-904f-e7fad9504fa9](https://user-images.githubusercontent.com/7699524/70887392-cc78e380-2018-11ea-96d1-ca35b1225825.gif)

**Comment by mingca** [comment]
I am no longer working on the project. Might have been solved with recent updates. I close this issue.
