### ISSUE TITLE
Rename file according to input name

### ISSUE THREAD

**Issue by Beiusxzw** [nervgh/angular-file-upload#873]
In my html:
```html
<a href="javascript:;" class="file_a">
     <input type="file" name="file1" nv-file-select uploader="uploader"  />
</a>
```
and my uploader:
```javascript
   uploader.onAfterAddingFile = function(fileItem, e) {
        var fileName = fileItem.file.name.split('.');
        if (fileName.length < 2) {
            alert("Uploaded file must have a valid extension! For more information see the Supported Formats")
        }
        var fileExtension = "." + fileName.pop();
        fileItem.file.name = e + fileExtension;
        console.info('onAfterAddingFile', fileItem);
    }
```
I wonder if I can retrieve the name of the input and rename the uploaded file? Thanks!

**Comment by ygj6** [comment]
Your method can modify the file name.
Does this example meet your requirements: https://github.com/nervgh/angular-file-upload/pull/875/commits/c7891da3bafc5e1890b564fd245588538766efcd
The final server receives the modified name：
![aaaa](https://user-images.githubusercontent.com/7699524/86353536-faaecf80-bc99-11ea-8a05-ef77d54eb571.jpg)

**Comment by Beiusxzw** [comment]
problem solved. Thanks!
