### ISSUE TITLE
How to handle file upload server side with Node.js and Express

### ISSUE THREAD

**Issue by ghost** [nervgh/angular-file-upload#89]
The example use php, but I'm not familiar with that framework.  How would I go about saving the uploaded files in a Node server?

**Comment by HCastano** [comment]
Hey, sorry if I'm a *slightly* late to the party, but I figure someone might find this of use. I went with [Multer](https://github.com/expressjs/multer) as my middleware of choice. I'm working with: *Angular 1.5.6*, *angular-file-upload 2.3.3*, *Express 4.13.1*, and *Multer 1.1.0*. 

In your Angular controller: 

```js
// controller.js
...
uploader = $scope.uploader = new FileUploader({
    url: '/upload' // POST request will be handled by Multer
})
...
```

This will make sure that when a file is uploaded from the queue on the Angular side, it gets sent to the backend to be dealt with appropriately. 

I decided to put the upload logic in a seperate module, so you'll want to load the router module in the app: 
```js
// app.js
var upload = require('./routes/upload')
...
app.route('/upload', upload)
```

Now, here is where the upload is taken care of: 
```js
// upload.js
var express = require('express')
var router = express.Router()
var multer = require('multer')

// Storage option can be changed - check Multer docs 
var storage = multer.diskStorage({
    destination: function(req, file, cb) {
        var path = './uploads' // Make sure this path exists 
        cb(null, path)
    }})
    
var upload = multer({
    storage: storage
})

// Will handle POST requests to /upload
router.post('/', upload.single('file'), function(req, res) {
    res.status(204).end()
})

module.exports = router
```

I've decided to go with disk storage, but Multer gives you a couple different storage choices. The `upload.single('file')` can be swapped out depending on your needs, and you can also set some limits and filters for the upload files.

And there you have it, a Node + Express back-end. Hope that helps!
