### ISSUE TITLE
Change http headers of request

### ISSUE THREAD

**Issue by ghost** [nervgh/angular-file-upload#92]
In my application I have token-based security setup.  For this to work I setup an http interceptor in angular that appends an authentication token to any `$http` request.  However, angular-file-upload doesn't use `$http` and instead relies on XHR.  How would I go about intercepting an XHR request or just specifying headers to be send with the upload request?  Thanks in advance.

**Comment by markzolotoy** [comment]
I need exactly the same thing. I need to intercept an upload and refresh a token when it expires. But my interceptor does not intercept the upload call. What can I do?

**Comment by tomcrusader** [comment]
For all my other request, seting headers on `$http` is sufficient. I wonder why this doesn't seem to work for FileUpload?


`http.defaults.headers.common["Authorization"] = "Bearer " + tokenInfo.accessToken;`

**Comment by josencv** [comment]
This is because the uploader doesn't use the $http service. It uses native javascript xhr object. Maybe in the future the $http service will be supported. For now, you'll have to add the authorization headers in the uploader directly:

``` javascript
var uploader = new FileUploader();
uploader.headers["Authorization"] = "Bearer " + tokenInfo.accessToken;
```

Hope it helps,

**Comment by tomcrusader** [comment]
Yeah, that worked great. Thanks!

**Comment by mrgoos** [comment]
@josencv - are we in the future yet? 😉

**Comment by theo4u** [comment]
coming up soon i guess @josencv

**Comment by theo4u** [comment]
#434

**Comment by theo4u** [comment]
#434

**Comment by tusharwalzade216** [comment]
@josencv, your solution worked great! Thanks a lot
