### ISSUE TITLE
Add formData before upload

### ISSUE THREAD

**Issue by iruindegi** [nervgh/angular-file-upload#97]
Hi, this is my controller:

```
    var uploader = $scope.uploader = $fileUploader.create({
        scope: $scope,                          
        url: '/doUpload',
        formData: [
            {
                key: 'value',
                izena:''
            }
        ]
    });
```

What I need is to include a new field called "izena" where I have my upload path and more data.

This is all the stuff I tried on "beforeupload" event:

```
    uploader.bind('beforeupload', function (event, item) {
        console.info('Before upload', item);
        var temp_izena = items[0].file.name;
        var izena = temp_izena.substr(0, temp_izena.lastIndexOf('.'));
        izena = izena + datuGuztiak;
        $('#izena').val(izena);
        $('#izena').text(izena);
        uploader.formData.push({ izena: izena });
        uploader.formData.izena = "jejejjejej";
        item.izena = "jajajjaj";
    });
```

but it is not working.. I can not see this param on my request on node.js

Whitch is the correct way to add new fields to upload?

thanks in advance

**Comment by onlypradeep** [comment]
Hi, 
We are unable to add/upload a second file when using IE9. No problems when uploading first file.
Works good in >IE9 and other browsers. Is it a known issue? How to fix this?

**Comment by philecom** [comment]
I am lst to where to place this code 
uploader.bind('beforeupload', function (event, item) {
    item.formData.push({some: 'data'});
});
I get undefined is not a function,

I hope you can help me.

**Comment by JimmyFarcy** [comment]
Hi i have try to add into the formData my token to certify the right to access to that url from the user.
To do so i try to use
```javascript
    uploader.bind('beforeupload', function (event, item) {
    item.formData.push({some: 'data'});
});
```

But i got this error

" TypeError: $scope.uploader.bind is not a function" 

Thank for you help

**Comment by Silver360** [comment]
Hi, i have the same problem. 
uploader.bind is not a function
Any idea what is wrong?

**Comment by Kiranrajkathula** [comment]
if i enter any formdata part in the code, im getting this problem.. pls help!

![321](https://cloud.githubusercontent.com/assets/13016029/8396223/d4fcf9c0-1dba-11e5-90ac-f99cf681584f.png)

**Comment by quangnhatt** [comment]
Hi, how can I get formData in controller (asp.net mvc)?

**Comment by parsipixel** [comment]
" TypeError: $scope.uploader.bind is not a function"

I solved the problem by using this function instead of bind :
`$scope.uploadImage = function (item) {
        item.formData.push({id: $scope.data._id});
        item.upload();
    };`

push formdata before uploading the item.

**Comment by ainasiart** [comment]
@quangnhatt Hi, how can I get formData in controller (asp.net mvc)?
After "pushing" you data in the formData, you can get it from you MVC controller using 
<code>Request.Form</code>

**Comment by stangudu1808** [comment]
How can i read the physical path location of the each file? and How can i read the bytearray or stream of the each file to store into the DB? Any help on this is appreciate

**Comment by vivek1108** [comment]
How can i add an image clicked from mobile directly into the uploader queue for uploading

**Comment by Libu-Mathew** [comment]
Now i'm facing some error when i pass a array into the formData.

When i am passing data like the following : 

`var arr = [ {  id : 1001, Price : 500 } ,{ id : 1008, Price : 800 } ];
item.formData.push({ 
        ClientId  : 'XSRT589633', 
        UserType  : 'CX102', 
        _Array    : arr
 });`

Here everything working fine but the key '_Array' returns a string [object object]
When i'm calculating the length of _Array it return 15 i.e, the length of string '[object object]'

**Comment by JiabinYuan** [comment]
@JimmyFarcy 
Hi, I got the same error, " TypeError: $scope.uploader.bind is not a function"
 do you kown how to fix it?
Thank for you help

**Comment by IanYoder** [comment]
I was able to update the form data using onBeforeUploadItem():

```
var fileUploader = new FileUploader();

fileUploader.onBeforeUploadItem = function(fileItem) {
    fileItem.formData.push({ data: 'data' });
};
```

**Comment by vamsivarikuti** [comment]
`onBeforeUploadItem` is going into infinite loop, any idea?

**Comment by evaldo1992** [comment]
uploader.onBeforeUploadItem=function(item){
            item.formData.push({ref:$scope.nuevo.ref});
        }
